web-infra-dev/rspress

- packages/core/src/theme-default/components/Sidebar/index.module.scss
> fix: rspress-sidebar-group divider style in dark mode

- .changeset/strong-dolls-occur.md
- packages/cli/src/index.ts
- packages/cli/src/modern-app-env.d.ts
Fix `isProduction()` is `false` when running the `build` command.
> fix(cli): incorrect node env when build

- .changeset/strong-bulldogs-talk.md
- packages/core/src/node/createBuilder.ts
Enable deterministic chunkIds of Rspack, it can reduce the length of filename and HMLT file size.
This config can be removed after upgrading Rspack v0.4: https://github.com/web-infra-dev/rspack/issues/3096
- https://github.com/web-infra-dev/rspress/issues/62
> perf: enable deterministic chunkIds of Rspack

- packages/plugin-preview/src/codeToDemo.ts
- packages/plugin-preview/src/index.ts
调用了`@rspress/shared`中的`normalizePosixPath`来比较plugin-preview中的路径
`normalizePosixPath` in `@rspress/shared` was called to compare the paths in plugin-review
在windows环境下启用插件仍然没有效果
plugin in the Windows environment has no effect
原因是在进行路径比较时没有正确匹配
the reason is the path comparison did not match correctly
PR替换了plugin-preview中涉及比较的路径
PR replaced the path involved in comparison in plugin review
> fix: 不同平台plugin-preview插件path比较

- .changeset/silly-pillows-tan.md
- packages/cli/src/index.ts
- packages/core/src/node/runtimeModule/routeData.ts
- packages/core/src/theme-default/layout/DocLayout/docComponents/pre.tsx
- packages/document/docs/en/api/commands.mdx
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/en/guide/basic/static-assets.mdx
- packages/document/docs/en/guide/start/getting-started.mdx
- packages/document/docs/en/guide/start/introduction.mdx
- packages/document/docs/zh/api/commands.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/docs/zh/guide/basic/static-assets.mdx
- packages/document/docs/zh/guide/start/getting-started.mdx
- packages/document/docs/zh/guide/start/introduction.mdx
- packages/document/rspress.config.ts
Optimize root config experience:
1. Support relative path in `config.root` param.
2. Support specifying root through command param such as `rspress dev docs`.
3. Add docs for root config.
> feat: more flexible root config

- .changeset/chilly-parents-tease.md
- packages/plugin-api-docgen/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- pnpm-lock.yaml
Before:
- `@rspress/core` depends on `rspack-plugin-virtual-module@0.1.2` (deps, not bundled)
- `@rspress/plugin-preview` depends on `rspack-plugin-virtual-module@0.1.1` (devDeps, bundled)
- `@rspress/plugin-playground` depends on `rspack-plugin-virtual-module@0.1.1` (devDeps, bundled)
- `@rspress/plugin-api-docgen` depends on `rspack-plugin-virtual-module@0.1.1` (devDeps, not used)
After:
- These three packages depend on `rspack-plugin-virtual-module@0.1.2` (deps, not bundled)
> chore(deps): unify rspack-plugin-virtual-module version

- .changeset/red-schools-shop.md
- packages/shared/package.json
- pnpm-lock.yaml
Ref: https://github.com/rspack-contrib/rslog/releases/tag/v1.1.0
> fix(shared): bump rslog@1.1.0 to fix color support detection

- packages/core/src/theme-default/components/Nav/NavBarTitle.tsx
Change the size of the icon to adapt based on the height instead of the width, as the length of the logo text varies slightly.
> style: Logo icon adaptation.

- .changeset/lucky-meals-sin.md
- packages/core/src/theme-default/components/HomeHero/index.tsx
Limit the max width of hero tagline.
Before:
After:
> fix(style): limit the max width of hero tagline

- .changeset/cuddly-cars-worry.md
- packages/core/src/theme-default/components/Overview/index.module.scss
- packages/core/src/theme-default/components/Overview/index.tsx
Keep overview h1 size same as other pages.
Before:
After:
> fix(style): keep overview h1 size same as other pages

- .changeset/early-books-share.md
- packages/core/src/node/createBuilder.ts
Align the default browserslist with anther community tools.
- before: `lib-polyfill.js` —— 231.8 kB minified, 69.6 kB gzipped
- after: `lib-polyfill.js` —— 161.7 kB minified, 45.9 kB gzipped
Note that the polyfill size will be greatly reduced after Rsbuild supports `polyfill: 'usage';
The `optimization.chunkIds` is removed because it is the default config of Modern.js Builder now.
https://github.com/web-infra-dev/rspress/issues/62
> perf(core): reduce polyfills by adjusting browserslist

- .changeset/eighty-apes-help.md
- packages/create-rspress/template/package.json
The new project should depend on rspress v1.
> fix(create-rspress): should depend on rspress v1

- .github/PULL_REQUEST_TEMPLATE.md
Copilot PR has not been enabled in the Rspress repo and the current template is a bit confusing, so we should remove the copilot summary from the PR template.
> chore(workflow): remove copilot summary from PR template

- .changeset/friendly-boxes-peel.md
- packages/document/docs/en/plugin/official-plugins/preview.mdx
- packages/document/docs/zh/plugin/official-plugins/preview.mdx
> fix: jsx tag missed in document

- .changeset/poor-camels-taste.md
- packages/core/src/node/initRsbuild.ts
fix `@theme` resolve error in v1.3.0
> fix: @theme alias not found

- .changeset/kind-penguins-burn.md
- packages/core/src/runtime/App.tsx
Change runtime code require theme alias path `@theme` instead of `@rspress/theme-default`.
https://github.com/web-infra-dev/rspress/issues/310
> fix: custom theme not working

- .changeset/nice-buttons-exercise.md
- packages/core/src/node/runtimeModule/prismLanguages.ts
- packages/document/docs/en/api/config/config-build.mdx
- packages/document/docs/zh/api/config/config-build.mdx
markdown hightlight default support bash syntax
https://github.com/web-infra-dev/rspress/issues/272
> feat: markdown hightlight default support bash syntax

- .changeset/angry-impalas-mix.md
- packages/theme-default/src/logic/utils.ts
This PR solves the issue as the title states
The root cause is if `hero.xx` does not exist, the `renderHtmlOrText` function will receive `undefined` as its parameter, and later bypass it to `htmr()`, which makes the whole page crash
Repro steps:
1. `pnpm create rspress@latest`
2.  replace `docs/index.md` with
```markdown
---
pageType: home
hero:
name: hello
---
```
3. `pnpm run dev`, and the app goes white screen
> fix(theme-default): Homehero comp crashes when hero field value is undefined

- .changeset/pretty-points-develop.md
- packages/theme-default/src/logic/sideEffects.ts
> fix: fix right aside nav item doesn't highlight automatically while opening in a new tab

- .changeset/perfect-tomatoes-dance.md
- packages/core/src/node/initRsbuild.ts
Using polyfill `usage` mode to reduce bundle size. 
Rsbuild use `usage` mode by default, so we do not need any extra configurations.
before:
after:
https://github.com/web-infra-dev/rspress/issues/62
> perf: using polyfill usage mode to reduce bundle size

- .changeset/wild-tigers-sip.md
- packages/theme-default/src/logic/sideEffects.ts
The calculation of `scrollTop` after clicking the bar on the right will produce decimals due to `target.getBoundingClientRect().top`. 
However, when calculating the activation status of bar, there is no decimal because offsetTop is used.
```js
if (scrollTop >= currentAnchorTop && scrollTop < nextAnchorTop) {
activate(links, i);
break;
}
```
So, round `scrollTop`.
#335
> fix: fix the activation status update error after clicking on the right navigation bar

- .changeset/smart-owls-care.md
- packages/shared/src/utils/index.test.ts
- packages/shared/src/utils/index.ts
> fix: replaceLang should handle the url ends with a slash

- .changeset/stupid-rats-glow.md
- packages/shared/src/utils/index.ts
> fix: reserve existed extension in normalizeHref

- packages/theme-default/src/components/Search/logic/util.ts
To make it searchable in Korean, the text that was normalized to NFD must be normalized to NFC.
so I changed it to NFC only if it is Korean.
```js
const cjkRegex =
/[\u3131-\u314e|\u314f-\u3163|\uac00-\ud7a3]|[\u4E00-\u9FCC\u3400-\u4DB5\uFA0E\uFA0F\uFA11\uFA13\uFA14\uFA1F\uFA21\uFA23\uFA24\uFA27-\uFA29]|[\ud840-\ud868][\udc00-\udfff]|\ud869[\udc00-\uded6\udf00-\udfff]|[\ud86a-\ud86c][\udc00-\udfff]|\ud86d[\udc00-\udf34\udf40-\udfff]|\ud86e[\udc00-\udc1d]|[\u3041-\u3096]|[\u30A1-\u30FA]/giu;
const kRegex = /[\u3131-\u314e|\u314f-\u3163|\uac00-\ud7a3]/u;
function originNormalizeTextCase(text) {
return text
.toLowerCase()
.normalize('NFD')
.replace(/[\u0300-\u036f]/g, '');
}
function fixedNormalizeTextCase(text) {
const result = text
.toLowerCase()
.normalize('NFD') …
```
> fix: support for Korean language search

- packages/create-rspress/template/rspress.config.ts
The code style of template config file is not the same.
No
> fix(create-rspress): code style of template config file is not the same

- .changeset/few-walls-dress.md
- packages/theme-default/src/logic/sideEffects.ts
> fix: reset prevActiveLink when unbinding AsideScrol

- .changeset/soft-days-film.md
- packages/core/src/node/initRsbuild.ts
the middleware order is [unshift]->[internal]->[push].  If [push] is used, the request ends with 404.
The proposed change prioritizes the handling of public resources and search index data. 
Please review the changes and let me know if any further modifications are required.
> fix: devServer use searchIndexMiddleware first.

- .changeset/tidy-geckos-taste.md
- packages/core/src/node/build.ts
Fixes the final build ignoring the user config setting `themeConfig.darkMode: false` (whereas it was previously respected in dev mode).
https://github.com/web-infra-dev/rspress/issues/372
> fix: remove dark mode script during build when disabled in config

- packages/document/docs/en/guide/basic/deploy.mdx
- packages/document/docs/zh/guide/basic/deploy.mdx
When following the steps in the documentation, GitHub Actions displays a warning about an unexpected input 'cache'.
This pull request removes this input to prevent the warning from appearing.
> docs: remove redundant 'cache' parameter from pnpm installation step.

- .changeset/weak-fishes-sparkle.md
- packages/core/src/node/runtimeModule/globalUIComponents.ts
If we use `globalUIComponents` in windows, we will get a error:
This change will fix it.
> fix(core): stringify global components path

- .changeset/forty-onions-shout.md
- packages/theme-default/src/layout/DocLayout/index.module.scss
CSS values wrapped in quotes are not recognized by browsers.
```scss
& {
overflow: 'scroll';
}
```
The changes in this MR remove these unrecognizable CSS values to prevent devtools warning.
Please review and provide any feedback.
> fix: remove unuse css that is not recognized by browsers.

- .changeset/hip-scissors-happen.md
- packages/core/modern.config.ts
- packages/core/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
`jsdom` is declared in the dependency but never used by Rspress.
Remove `jsdom` can fix the deprecation warnings and reduce 9MB install size.
```text
 WARN  2 deprecated subdependencies found: abab@2.0.6, domexception@4.0.0
```
https://packagephobia.com/result?p=jsdom@20.0.3
> perf(deps): remove unused jsdom dependency

- .changeset/neat-tools-give.md
- packages/modern-plugin-rspress/src/features/lanchDoc.ts
It still exists problems in module plugin when autoSidebar.
This is the impactful way.
> fix(modern-plugin): support auto sidebar when is bilingual

- .changeset/dirty-rice-accept.md
- packages/runtime/src/utils.ts
- packages/shared/src/utils/index.ts
When building with `pnpm run build`, ssg incorrectly adds a slash at the beginning of inline image resources in the generated HTML.
This pull request addresses this issue by checking if the URL is a data URL. If it is, the URL will be returned as is, without adding a slash.
This should ensure that inline image resources are correctly referenced in the generated HTML. Please review and provide any feedback.
> fix: inline image data url start with slash prefix.

- .changeset/nine-bulldogs-wait.md
- packages/modern-plugin-rspress/src/features/lanchDoc.ts
- packages/modern-plugin-rspress/src/utils.ts
The code block have supported dark mode, we can remove the limit about it.
> fix(modern-plugin): remove the limit to enable darkmode

- .changeset/giant-gorillas-visit.md
- packages/core/src/node/initRsbuild.ts
This pull request addresses an issue where the page title displays as "Rsbuild App" during page load when not in static site generation (SSG) mode. 
The proposed change sets the default page title to the current site's title attribute. 
This should provide a more accurate and user-friendly title during page load.
Please review and provide any feedback.
> feat: use config.title as html title.

- .changeset/thick-birds-care.md
- packages/plugin-preview/src/codeToDemo.ts
- packages/plugin-preview/src/index.ts
When we set defaultRenderMode, we still process the code block in remark plugin, this fix it.
> fix(plugin-preview): add defaultRenderMode to remark plugin

- .changeset/shiny-dancers-kiss.md
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/components/Search/index.module.scss
页面尺寸被压缩到一定宽度后，导航栏中，Logo图片会被挤压，搜索按钮和其他菜单项的文案会被挤压换行
> style(Nav): fix styling issues for specific sizes

- .changeset/perfect-chairs-fold.md
- packages/create-rspress/src/index.ts
- packages/create-rspress/src/utils.ts
Hi~ I noticed that create-rspress cannot exit during creation. I hope this could help.
> feat(create_rspress): support cancel operation

- .changeset/chilled-gifts-do.md
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/components/SourceCode/index.module.scss
- packages/theme-default/src/components/SourceCode/index.tsx
- packages/theme-default/src/index.ts
- packages/theme-default/src/logic/useLocaleSiteData.ts
code:
```mdx
import { SourceCode } from '@theme';
<SourceCode href="/" />
```
preview:
customize source text:
```js
import { defineConfig } from 'rspress/config';
export default defineConfig({
themeConfig: {
sourceCodeText: "My Source Text"
},
});
```
#230
> feat: support SourceCode component

- .changeset/slimy-deers-prove.md
- packages/plugin-auto-nav-sidebar/src/index.ts
The error in #453 was caused by the `@rspress/plugin-auto-nav-sidebar`, which can't generate configs correctly if `locales` are not configured. [Promise here](https://github.com/web-infra-dev/rspress/blob/main/packages/plugin-auto-nav-sidebar/src/walk.ts#L56-L118) is rejected because the value of the name field is `undefined`
Not sure if we should add this to the suitable part of the documentation and where the "suitable part" is
#453
> feat: improve errors outputted to console

- .changeset/fluffy-jars-jump.md
- packages/theme-default/src/logic/useNav.ts
Close nav screen when route changed, so that users do not need to manually close nav after navigation.
https://github.com/web-infra-dev/rspress/assets/7237365/639c368d-5971-4ca3-9be3-c8044a2d3c11
> feat: close nav screen when route changed

- .changeset/young-tables-occur.md
- packages/plugin-playground/src/cli/index.ts
The two plugins are mutually conflicting.
So we need in playground remove another plugin.
> fix(plugin-playground): remove preview plugin when use playground

- .changeset/warm-keys-live.md
- packages/plugin-playground/src/cli/index.ts
- packages/plugin-playground/src/cli/remarkPlugin.ts
> fix(plugin-playground): add defaultRenderMode to remark plugin

- .changeset/mean-parents-pull.md
- packages/core/src/node/mdx/remarkPlugins/toc.ts
When I write the following content:
```mdx
```
I will get a error:
This PR fix the error and support inline code type too.
And I add a judge for the children type
> fix(core): toc can collect strong and inline code from header, and judge if it is text type when collect value

- .changeset/ninety-carrots-yawn.md
- packages/modern-plugin-rspress/src/types.ts
> fix(modern-plugin): add useModuleSidebar to plugin option

- .vscode/settings.json
https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
The setting values were also updated, with the current boolean values to be deprecated in favor of the string equivalent.
> chore: update vscode setting

- packages/document/docs/en/guide/default-theme/i18n.mdx
- packages/document/docs/zh/guide/default-theme/i18n.mdx
Default lang based on locales, so we need configure locales first!
Here is the change commit. https://github.com/web-infra-dev/rspress/pull/391/files#diff-ca2dde319beb6f6b3cd12a0dbe21569c4b89adb8c0cd50b9cac1197522d3ec10R54
> docs: adjust i18n step

- .changeset/dirty-apples-promise.md
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/src/node/searchIndex.ts
> fix: search index file not found when i18n is not set

- .changeset/fluffy-jobs-vanish.md
- packages/plugin-api-docgen/static/global-components/API.tsx
> fix(api-docgen): add opitional chaining operator when read apiDocMap

- .changeset/wicked-rivers-bow.md
- packages/plugin-preview/src/index.ts
- packages/plugin-preview/static/global-components/Device.tsx
If we import virtual-meta in device, we will import all code demo, the global style may be overwrite by demo.
So we need remove it.
In fact, we can get demoMeta and add it to page by 'extendPageData', so I do it.
> fix(plugin-preview): remove virtual demo and get it from pageData in Device

- .changeset/fuzzy-bulldogs-know.md
- packages/cli/src/index.ts
> fix: `-c` unknown option in rspress cli

- .changeset/unlucky-lamps-wink.md
- packages/theme-default/src/components/Search/SearchPanel.tsx
If the search query text is not cleared and the search box is closed, `No result` is displayed when the search box is opened again.
> fix: clear query text when search box opens again

- .changeset/pink-falcons-wink.md
- packages/theme-default/src/components/Link/index.tsx
Clicking on the same current internal link of sidebar item or navBar title multiple times, will cause `navigate` to trigger multiple times, which normally shouldn't be triggered.
> fix: avoid pushing to history when clicking on the same current link

- .changeset/thirty-maps-remember.md
- packages/plugin-shiki/src/shiki/pluginShiki.ts
Export PluginShikiOptions type from `@rspress/plugin-shiki`.
```ts
import type { PluginShikiOptions } from '@rspress/plugin-shiki';
```
> types: export PluginShikiOptions type

- .changeset/wise-carpets-tie.md
- packages/core/package.json
- packages/core/src/node/build.ts
- packages/core/src/node/initRsbuild.ts
- pnpm-lock.yaml
Rsbuild provides `server.publicDir` to serve the public folder, Rspress can use it and do not need to depend on `sirv`.
Tested in `e2e/fixtures/production`.
https://rsbuild.dev/config/server/public-dir
> feat: serve publicDir via Rsbuild

- .changeset/pretty-hornets-battle.md
- packages/shared/package.json
- packages/shared/src/logger.ts
- pnpm-lock.yaml
Reuse logger from Rsbuild. Rsbuild now provides logger as a public API see: https://rsbuild.dev/api/javascript-api/core#logger.
This change can also upgrade rslog to latest version (v1.2.0) and fix some bug, see https://github.com/rspack-contrib/rslog/releases
> feat: reuse logger from Rsbuild

- .changeset/twenty-points-remember.md
- packages/core/src/node/initRsbuild.ts
publicDir mkdir conflict when repeat call build with promise.all
> fix: publicDir mkdir conflict

- .changeset/five-avocados-cheat.md
- packages/core/src/node/dev.ts
In rsbuild, when we called `builder.startDevServer`, the compile process doesn't finished. So we should execute `afterBuild` hook of Rspress in the `onDevCompileDone` hook of Rsbuild to ensure the compile process done.
> fix: ensure afterBuild executed after dev compile done

- packages/plugin-playground/src/cli/remarkPlugin.ts
@rspress/plugin-playground 插件在windows系统下不能正常的工作，排查原因为: windows系统下getRouteMeta() 与 remarkPlugin 中得到的绝对路径使用不同的路径分隔符导致。
当两个路径比较时，须要抹平不同系统之间的差异。
> fix: When using strict equality comparison for absolute paths, smooth the path separators of different systems.

- .changeset/curly-ravens-tap.md
- packages/theme-default/src/layout/DocLayout/docComponents/table.tsx
Allow table scrolling to avoid breaking work. Breaking a word can cause difficulty reading the word.
such as:
https://rsbuild.dev/guide/start/features
> feat: allow table scrolling to avoid breaking work

- packages/document/package.json
- packages/document/theme/index.tsx
- pnpm-lock.yaml
Integrate rsfamily nav icon.
https://github.com/rspack-contrib/rsfamily-nav-icon
> docs: integrate rsfamily nav icon

- packages/plugin-auto-nav-sidebar/src/walk.ts
If someone sets rspress as the root directory for special purposes, it will read the node_modules directory at the same level.
I know it's recommended to designate a separate directory as root.
but, My special-purpose case is when I choose to place my .mdx files in the same place as my script files, like .stories.js, .styles.js, or .test.js, for greater cohesion.
`rspress.config.ts`
```
{
root: path.join(__dirname, '..', 'my-rspress'),
...
}
```
This causes a lot of unnecessary navigation and warnings, which is not comfortable.
(The warnings are proportional to the number of packages installed.)
```
warn    Can't find the file: /Users/haydnhkim/my-rspress/node_modules/abort-controller/LICENSE, please check it in "/Users/haydnhkim/my-rspress/node_modules/abort-controller/_meta.json".
warn …
```
> fix: sidebar walk excludes node_modules

- .changeset/gentle-tomatoes-raise.md
- packages/plugin-playground/src/cli/remarkPlugin.ts
> fix(plugin-playground): fix spelling error which break render mode

- .changeset/violet-falcons-listen.md
- packages/plugin-preview/src/codeToDemo.ts
- packages/plugin-preview/static/global-styles/web.css
When use html code element with isMobile prop, it renders wrongly because the `isMobileMode` variable should be boolean but is an object. This commit forcibly convert `isMobileMode` to boolean type.
> fix(plugin-preview): Convert isMobileMode variable to boolean

- .github/workflows/test-macOS.yml
Using new M1 macOS runner to make CI faster.
see: https://github.com/web-infra-dev/rsbuild/pull/1486
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> test(workflow): using new M1 macOS runner

- packages/runtime/package.json
fix rspack-ecosystem-ci problem: require module error
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7737817821/job/21097458012
> fix: require module error in next rspack version

- .changeset/curly-bottles-own.md
- .changeset/nice-masks-drum.md
- packages/plugin-preview/src/virtual-demo.tsx
We can find that this logic was broken by https://github.com/web-infra-dev/rspress/pull/244/files#diff-9558abcf9793ab81c8610c64e732478c5ec3533d56a02a333e71fd38cfb843d7L11
> fix(plugin-preview): fix demo id and avoid 404 in production

- .changeset/clever-ladybugs-suffer.md
- packages/core/src/node/searchIndex.ts
The use of `fs.readFileSync` in middleware to read a local file and then send it to the client using `res.end` can potentially lead to performance issues.
The `fs.readFileSync` function is a synchronous operation, which means it will block the Node.js event loop until the file read operation is complete. If the file is large or the file system is slow, this can significantly delay the response time of your server, and during this time, your server will not be able to handle any other requests. This can lead to poor performance and scalability issues, especially under high load.
A better approach would be to use the asynchronous version of the function, `fs.readFile`, which does not block the event loop. Or even better, you can use `fs.createReadStream` to read the file as a stream and …
> perf: use stream to serve search index

- .changeset/rare-rice-smoke.md
- packages/plugin-auto-nav-sidebar/src/walk.ts
When use `type: 'file'` in _meta.json, can not extract h1 title
> fix(plugin-auto-nav-sidebar): use logical OR instead of nullish coalescing when label is empty

- packages/core/src/node/PluginDriver.ts
- packages/core/src/node/initRsbuild.ts
- packages/document/rspress.config.ts
- packages/document/tsconfig.json
- packages/theme-default/modern.config.ts
- packages/theme-default/package.json
- packages/theme-default/src/components/Aside/index.tsx
- packages/theme-default/src/components/HomeFeatures/index.tsx
- packages/theme-default/src/components/Link/index.tsx
- packages/theme-default/src/components/Nav/NavBarTitle.tsx
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/NavScreen/index.tsx
- packages/theme-default/src/components/Search/index.tsx
- packages/theme-default/src/components/Toc/index.tsx
- packages/theme-default/src/global.d.ts
- packages/theme-default/src/layout/DocLayout/docComponents/link.tsx
- packages/theme-default/src/layout/Layout/index.tsx
- packages/theme-default/src/node/source-build-plugin.ts
- packages/theme-default/tailwind.config.ts
- packages/theme-default/tsconfig.json
1. use bundled theme-default files for document production build
3. fix tailwind config for document dev(`DOC_DEBUG`)
4. refactor: move `DOC_DEBUG`-related codes to standalone rspress plugin in `theme-default`
fixes #551
> fix(document): style duplicating issue of rspress.dev #551

- .changeset/khaki-olives-confess.md
- packages/theme-default/src/assets/copy.svg
- packages/theme-default/src/assets/success.svg
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.module.scss
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
https://github.com/web-infra-dev/rspress/assets/69188140/f2426fd8-caad-45e7-af85-f19eb5e03d3b
resolves #612
> feat(theme-default): Updated codeblock - fix copyBtn Icons && updated wordWrapBtn animations for equality between both buttons

- packages/theme-default/src/components/NavScreen/index.module.scss
> fix(nav_screen): visibility on docs layout for smaller screens

- packages/theme-default/src/styles/code.css
> Ik it may broke some words but it would fix extra overflow
https://rspress.dev/zh/guide/basic/deploy
> patch(code.css): fix website overflow because of ` code `

- .changeset/sweet-zoos-boil.md
- packages/theme-default/src/components/Tabs/index.module.scss
- packages/theme-default/src/components/Tabs/index.tsx
> fix(tab-list):overflown tabs not showing on mobile fixed

- packages/theme-default/src/components/HomeHero/index.tsx
This would have to get better visibility of hero actions on smaller screen, and looks better than before, proper padding and uniformity
> feat(repress-hero-actions): better visibility on mobile/small screens!

- .changeset/hungry-kangaroos-compare.md
- packages/document/docs/404.mdx
- packages/document/public/netlify.toml
- packages/document/rspress.config.ts
followed https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling for csutom 404 solution
resolves #621
> fix(documentation)!!: tried to configure 404 page on netlify hosting 

- .changeset/grumpy-flowers-bow.md
- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/components/ScrollToTop/index.module.scss
- packages/theme-default/src/components/ScrollToTop/index.tsx
- packages/theme-default/src/layout/DocLayout/index.tsx
feat(theme-default): Scroll to top button on docs | enableScrollToTop
chore(docs): weixin -> wechat
https://github.com/web-infra-dev/rspress/assets/69188140/fbe8e384-680e-4d5b-9245-eec2c2f468fb
> feat(theme-default): Scroll to top button on docs | enableScrollToTop

- .changeset/orange-cooks-pay.md
- packages/theme-default/package.json
When we use `#theme/logic` to redirect to the module in `@rspress/theme-default/src/logic`, we cannot resolve the path because the src modules missed in production.
> fix: private import not work in production

- .changeset/brown-actors-brake.md
- packages/theme-default/src/layout/DocLayout/docComponents/code/PrismSytaxHighlighter.tsx
https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use-custom-components-syntax-highlight
Fix `props.children.trim` is not a function
> fix(doc-components): change code children to string

- .changeset/early-pots-act.md
- packages/plugin-preview/static/global-components/Device.tsx
- packages/theme-default/src/components/Sidebar/index.module.scss
- packages/theme-default/src/components/Sidebar/index.tsx
- packages/theme-default/src/layout/DocLayout/index.module.scss
- packages/theme-default/src/logic/useUISwitch.ts
This pr fix theme style issues when navbar or outline not display.
1. change css variable `--rp-aside-width` and `--rp-sidebar-width` from `0` to `0px` 
while chrome tract `calc(100% - 0px)` as invalid property value
2. move sidebar padding property to a sub container
while sidebar width set to 0 still has padding-right remind.
3. `.rspress-doc` and `.rspress-doc-footer` change `box-sizing: content-box` to `box-sizing:border-box` in screen 1280px because of `content-width + padding > 100vw`
4. increase outline `max-height` for reduce the gap between outline bottom and page bottom.
> fix: fix some theme style issues.

- .changeset/wise-rivers-deny.md
- packages/theme-default/src/components/Search/SearchPanel.tsx
> feat: set min time of initing search index as 1s

- .changeset/orange-beans-matter.md
- packages/theme-default/src/components/Link/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/link.tsx
This pr will pass through HTMLAnchorElement props to Link component. To use props like `title` in `<Link />`
```jsx
function Example() {
return (
<Link href="https://rspress.dev/" title="A Great Static Site Generator" />
)
}
```
> feat: pass through HTMLAnchorElement props to Link component.

- .changeset/late-kangaroos-do.md
- packages/theme-default/src/components/LastUpdated/index.tsx
To fix the collapsed space, I moved the last updated time `<span>` element into the paragraph that contains the text, so that the space is _shown_.
Closes #645
> fix(theme-default): Fix collapsed space between last updated text and time

- .changeset/mighty-pets-occur.md
- packages/plugin-auto-nav-sidebar/src/walk.ts
> fix(plugin-auto-nav-sidebar): avoid error which caught by type divider

- packages/document/docs/en/fragments/useI18n.mdx
- packages/document/docs/zh/fragments/useI18n.mdx
```ts
export declare function useI18n<T = Record<string, Record<string, string>>>(): (key: keyof T) => any;
```
> docs: fix types in `useI18n` hook

- packages/theme-default/src/components/SocialLinks/index.module.scss
Mobile/Safari:
PC/Safari:
The alternative way to fix the issue is add width/height to the SVG files.
> fix: add explicit height to social link icons, which is needed on Safari

- .changeset/thick-shrimps-agree.md
- packages/theme-default/src/components/SwitchAppearance/index.tsx
- packages/theme-default/src/logic/useAppearance.ts
When we open two tab in browser, found:
1. Change dark mode in one tab.
2. In another tab, appearance is changed, but component theme is not changed.
> fix(theme-default): update theme when change storage

- .changeset/eleven-tomatoes-collect.md
- packages/runtime/src/hooks.ts
This makes it possible to use in hook dependencies, works with ESLint, and to avoid unnecessary re-render.
> fix: memoize the callback in `useI18n` hook

- .changeset/breezy-pugs-guess.md
- packages/theme-default/src/components/Overview/index.module.scss
Fix overview links margin not work as `display: block` of a tag has been removed in https://github.com/web-infra-dev/rspress/commit/7c3cd1593c7b40dd8d103ddd5971852d241f703e.
- main branch: 
- expected:
> fix(style): overview links margin not work

- .changeset/flat-suns-tap.md
- packages/core/src/node/initRsbuild.ts
Extract all CSS into a single file, ensure CSS in async chunks can be loaded for SSG.
The same as docusaurus and vuepress:
- https://github.com/facebook/docusaurus/blob/0589b1475d56b0b541348aa56f201ec7c56c56d5/packages/docusaurus/src/webpack/base.ts#L182-L189
- https://github.com/vuejs/vuepress/blob/087f8a199de4436366aba8f8bf44571117612e53/packages/%40vuepress/core/lib/node/webpack/createBaseConfig.js#L293-L306
Fix styles in SSG pages, such as https://modernjs.dev/en/guides/get-started/introduction.html
> feat: extract all CSS into a single file

- .changeset/shy-eagles-laugh.md
- packages/theme-default/src/layout/DocLayout/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.tsx
- packages/theme-default/src/styles/vars.css
This PR adds style `overflow-hidden` to the doc container to ensure the code block scrolls correctly when there is no wrap.
https://github.com/web-infra-dev/rspress/pull/677#issuecomment-1971280511
> fix: make outline have a well width

- .changeset/early-horses-itch.md
- packages/theme-default/src/layout/DocLayout/index.tsx
The `overflow-hidden` style cause the api page width collapsed. The preview after removing it:
In the meantime, the expanding problem of doc content has been solved by #693 through setting an appropriate outline width:
#643
> fix: remove useless overflow style, which cause api page width collapsed

- .changeset/lucky-cooks-admire.md
- packages/modern-plugin-rspress/src/lanchDoc.ts
- packages/plugin-preview/src/index.ts
Fix that can not resolve @rspress/core/theme.css when use modern plugin
> fix(modern-plugin): modernjs plugin alias problem in iframe

- e2e/fixtures/modern-js/package.json
- e2e/fixtures/view-transition/package.json
- pnpm-lock.yaml
Remove legacy modern.js dependencies from the `e2e` folder, use the root dev dependency instead.
Reduced dependncies:
> chore: remove legacy modern.js dependencies

- .changeset/kind-insects-develop.md
- packages/core/package.json
- packages/core/src/node/initRsbuild.ts
- pnpm-lock.yaml
Remove the built-in SVGR plugin since Rspress does not rely on this plugin.
The SVGR feature is not mentioned in the documentation, but some users who have used custom React components may rely on this behavior, so this could be a potentially breaking change.
The benefits of removing the SVGR plugin are obvious, it can significantly reduce the number of dependencies (-80), and it also allows the use of different SVGR syntax or config, so we will remove it in the next minor version of Rspress.
Users who have SVGR needs can manually use the [@rsbuild/plugin-svgr](https://rsbuild.dev/plugins/list/plugin-svgr):
1. run `pnpm add @rsbuild/plugin-svgr -D`
2. register this plugin in `rspress.config.ts`:
```js
import { pluginSvgr } from '@rsbuild/plugin-svgr';
export default defineConfig({ …
```
> perf: remove the builtin @rsbuild/plugin-svgr

- .changeset/short-rats-happen.md
- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/runtimeModule/siteData/extractPageData.ts
- packages/core/src/node/utils/flattenMdxContent.ts
Fix doc fragment hmr invalid.
#727
> fix: doc fragment hmr invalid

- .changeset/orange-waves-admire.md
- packages/theme-default/src/components/Overview/index.tsx
- packages/theme-default/src/index.ts
Add support for sub dir overview, we can filter the sidebar groups by link.
> feat(theme): support custom overview and sub overview

- .changeset/mean-rings-cover.md
- packages/theme-default/src/components/Nav/index.tsx
update isMobile when resize to keep the same behavior.
> fix(theme): update nav when resize

- .changeset/short-wolves-impress.md
- packages/plugin-medium-zoom/src/components/MediumZoom.tsx
> feat: set mask color of image preview to be black #000 in dark mode (#730)

- .changeset/popular-masks-bow.md
- packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
When Use getCustomMDXComponent, pre code will not be rendered correctly. 
After #642 , we need support array in pre, too.
> fix(theme): support format pre code when children is array

- packages/document/docs/zh/guide/basic/custom-page.mdx
https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/theme-default/styles/vars.css is 404 ---->>
https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/styles/vars.css
> dosc: fix link in zh/guide/basic/custom-page.mdx

- packages/document/docs/en/guide/basic/custom-page.mdx
https://github.com/web-infra-dev/rspress/blob/main/packages/core/src/theme-default/styles/vars.css is 404 --->>>
https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/styles/vars.css
> dosc: fix link in en/guide/basic/custom-page.mdx

- .changeset/calm-bananas-fail.md
- packages/plugin-shiki/src/shiki/pluginShiki.ts
- packages/plugin-shiki/src/shiki/transformers/line-number.ts
Support line number in shiki highlight mode:
> feat: support showing line numbers in shiki plugin

- .changeset/khaki-falcons-act.md
- packages/plugin-shiki/shiki.css
- packages/plugin-shiki/src/shiki/rehypePlugin.ts
- packages/theme-default/src/components/PackageManagerTabs/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
> fix: shiki plugin space style

- .changeset/curly-seahorses-try.md
- packages/theme-default/src/components/Sidebar/index.tsx
https://github.com/web-infra-dev/rspress/assets/18117084/eeffe26f-5e8e-4428-9880-9f7db3bfac29
- relate: https://github.com/web-infra-dev/rsbuild/issues/1798
- fixes: #770
> fix(theme-default): sidebar begining top items was unchanged after page switch

- packages/theme-default/src/components/Sidebar/index.tsx
Reverts web-infra-dev/rspress#768
The PR changes the id of sidebar group and makes the following logic crash and page broken:
> Revert "fix(theme-default): sidebar begining top items was unchanged after page switch"

- .changeset/fuzzy-pugs-occur.md
- packages/theme-default/src/styles/base.css
Prevent in-page jump elements from being blocked by nav.
> fix(theme): add scroll padding top

- .changeset/mean-worms-fix.md
- packages/theme-default/package.json
- packages/theme-default/src/components/LocalSideBar/index.scss
- packages/theme-default/src/components/LocalSideBar/index.tsx
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/Toc/index.tsx
- pnpm-lock.yaml
Optimize ui and interaction for nav in mobile device:
1. Make the toc list scrollable.
2. Optimize the interaction between the first nav and the second nav menu when user scrolls the page.
3. Add transition animation for the toc component enters when user click the `On this page`  button.
preview:
https://github.com/web-infra-dev/rspress/assets/39261479/8866bac6-ef0b-4904-b903-b53e46dc3e50
#799
> feat: optimize ux of the 2nd sticky nav on mobile

- .changeset/silver-ants-know.md
- packages/core/package.json
- pnpm-lock.yaml
related to https://github.com/web-infra-dev/mdx-rs/pull/24
> fix: avoid panic when relative path in markdown links point outside root path

- .github/workflows/release.yml
No need to trigger update for rsbuild, as rsbuild uses renovate to update dependencies.
- https://github.com/web-infra-dev/rsbuild/pull/1861
- https://github.com/web-infra-dev/modern.js/pull/5545
> chore(workflow): no need to trigger update for rsbuild

- .changeset/little-dots-compete.md
- packages/theme-default/src/components/Nav/menuDataHooks.tsx
It's useful when you use custom filter/tabs in your site and you want to keep the state on locale change.
The hash could be preserved as well, but it's not common as the query string. (eg. when using Docusaurus, the query string and hash are both preserved: https://docusaurus.io/docs/markdown-features/tabs?current-os=android#query-string)
> feat(theme-default): preserve query string on locale change

- .changeset/clean-apricots-explode.md
- packages/theme-default/src/components/Aside/index.tsx
- packages/theme-default/src/components/HomeFeature/index.tsx
- packages/theme-default/src/components/Link/index.tsx
- packages/theme-default/src/components/LocalSideBar/index.tsx
- packages/theme-default/src/components/Nav/NavBarTitle.tsx
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/NavScreen/index.tsx
- packages/theme-default/src/components/Search/index.tsx
- packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
- packages/theme-default/src/components/Sidebar/SidebarSectionHeader.tsx
- packages/theme-default/src/components/Sidebar/index.tsx
- packages/theme-default/src/components/Toc/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/CopyCodeButton.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/link.tsx
- packages/theme-default/src/layout/DocLayout/index.tsx
- packages/theme-default/src/layout/Layout/index.tsx
When we use #theme, we will get the same module id in dist/bundle.js.
Use relative path instead, and bundle it by module-tools.
> chore(theme): remove imports, use relative path instead

- .changeset/soft-horses-greet.md
- packages/theme-default/src/components/Link/index.tsx
Support internal link can keep url params.
`keepCurrentParams` is false by default, later we maybe change it to `true`
We can customize it in theme/index.tsx like this:
```jsx
import { Link } from 'rspress/theme';
const myLink = (props) => {
return <Link keepCurrentParams={true} {...props} />;
};
export { myLink as Link };
```
> feat(theme): support link keep current params and navigate

- .changeset/nice-planets-invent.md
- packages/core/package.json
- packages/core/src/node/searchIndex.ts
- packages/runtime/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
Remove `@modern-js/types` dependency, this is an internal package of Modern.js and we should avoid depending on it.
> chore: remove @modern-js/types dependency

- .changeset/angry-coins-drum.md
- packages/cli/package.json
- packages/cli/src/config/loadConfigFile.ts
- packages/cli/tests/config/config-basic.test.ts
- pnpm-lock.yaml
This PR uses the public `loadConfig` API of Rsbuild to load the config file, instead of `@modern-js/node-bundle-require`.
The `loadConfig` is based on jiti and offers better performance and less dependencies. The motivation is basically the same as https://github.com/web-infra-dev/rspress/pull/144.
After this change, Rspress will no longer depend on `@modern-js/node-bundle-require` and `esbuild`, so the install size can be reduced by 9+ mB.
- https://rsbuild.dev/api/javascript-api/core#loadconfig
> perf: remove node-bundle-require dependency

- .changeset/serious-boxes-tickle.md
- packages/plugin-container-syntax/container.css
Improve bg opacity of container blocks, make the transparency more consistent and moderate.
- light
- dark
- https://github.com/web-infra-dev/rspress/commit/7b6eea0472f84c8338341d38a6d8a597b3fd3af2
- https://github.com/web-infra-dev/rspress/pull/699
> feat: improve bg opacity of container blocks

- .changeset/hot-falcons-smoke.md
- packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Fix the capitalization issue of X in socialLinks presetIcons
No Issue
> fix(theme-default): fix the capitalization issue of X in socialLinks presetIcons

- .github/pr-labeler.yml
- .github/workflows/pr-label.yaml
Add PR labeler to workflow (the same as Rspack/Rsbuild/Rsdoctor), this allows to:
- add label for PR
- generate CHANGELOG via GitHub release.
> chore(workflow): add PR labeler

- .changeset/metal-papayas-live.md
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
The website's logo icon has a logo id, which will cause `const target=document.getElementById(header.id);` get wrong dom. So, I set the custom id (`## logo \{#logo-1}`) for logo sidebar. 
Close #853
> fix(doc): fix logo sidebar cannot be used properly.

- packages/document/docs/en/guide/basic/custom-page.mdx
- packages/document/docs/zh/guide/basic/custom-page.mdx
Translate Tailwind CSS setup to Chinese.
https://github.com/web-infra-dev/rspress/pull/754
> docs: translate Tailwind CSS setup

- .changeset/chilly-pumpkins-remember.md
- e2e/fixtures/basic/doc/content.mdx
- e2e/fixtures/basic/doc/index.mdx
- e2e/fixtures/basic/rspress.config.ts
- e2e/tests/basic.test.ts
- packages/core/package.json
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/mdx/loader.ts
- packages/theme-default/package.json
- pnpm-lock.yaml
In #640 , we will flatten mdx content in mdx loader, and then replace-string-loader failed.
So removed it and replace in mdx loader.
> fix(core): replace flattened mdx content by rules

- e2e/fixtures/api-docgen/doc/index.mdx
- e2e/fixtures/api-docgen/package.json
- e2e/fixtures/api-docgen/rspress.config.ts
- e2e/fixtures/api-docgen/src/Button.ts
- e2e/tests/api-docgen.test.ts
- packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
- packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
- pnpm-lock.yaml
Add an E2E case for the api-docgen plugin.
> test(e2e): add case for api-docgen plugin

- .changeset/pink-knives-compare.md
- e2e/fixtures/api-docgen/src/Button.ts
- e2e/tests/api-docgen.test.ts
- packages/plugin-api-docgen/src/docgen.ts
- packages/plugin-api-docgen/static/global-components/API.scss
Allow multiple lines description in the api-docgen plugin.
- input:
- before:
- after:
> fix(api-docgen): allow multiple lines description

- .github/release.yml
Add GitHub release yaml config to use GitHub release note generator.
The same as https://github.com/web-infra-dev/rsbuild/blob/main/.github/release.yml
> chore(workflow): add GitHub release yaml config

- .changeset/swift-needles-tickle.md
- packages/core/src/node/build.ts
> fix(core): set ssg:false in plugin not work in build mode

- .changeset/real-beans-cheer.md
- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/logic/useRedirect4FirstVisit.ts
1. Redirecting is unexpected when sharing the specific locale.
2. It's hard to write a match function for every case, even if there is a guideline (such as https://datatracker.ietf.org/doc/html/rfc4647#section-3.4), locale codes may be too complex.
> feat: add `localeRedirect` option to theme config

- e2e/fixtures/modern-js/package.json
- pnpm-lock.yaml
Clean up the modern-js fixture, remove some unused dependencies.
close https://github.com/web-infra-dev/rspress/pull/885
> test(e2e): clean up modern-js fixture

- packages/document/docs/en/plugin/official-plugins/overview.mdx
- packages/document/docs/zh/plugin/official-plugins/overview.mdx
- Improve community plugins document
- Add `rspress-plugin-font-open-sans`
> docs: improve community plugins

- .changeset/eighty-experts-camp.md
- .changeset/great-boats-notice.md
- packages/core/src/node/build.ts
- packages/core/src/node/constants.ts
- packages/core/src/node/initRsbuild.ts
> fix: avoid flash of theme appearance in dev mode

- .changeset/perfect-islands-shave.md
- packages/core/src/runtime/clientEntry.tsx
- packages/theme-default/src/components/SwitchAppearance/index.tsx
- packages/theme-default/src/logic/index.ts
- packages/theme-default/src/logic/useAppearance.ts
- packages/theme-default/src/logic/useHandler.ts
- packages/theme-default/src/logic/useMediaQuery.ts
- packages/theme-default/src/logic/useStorageValue.ts
Splits:
- #878 also add `color-scheme` on root element, this is useful for theme styling based on native CSS media queries or `light-dark()` function, third-party libraries and creators may use this feature
- #879 
In this PR,  all the appearance related codes are refactored to a single React Hook, the checklist:
After these are done, we can use two patterns to display elements without flash:
```html
<MyComponent className="dark:hidden" />
<MyComponent className="hidden dark:block" />
<picture>
<source srcset="dark.svg" media="(prefers-color-scheme: dark)" />
<source srcset="light.svg" media="(prefers-color-scheme: light)" />
</picture>
```
> feat: respond to the change of system theme appearance

- packages/plugin-rss/package.json
- packages/shared/package.json
Fix invalid exports.types field in package.json, the `types` should be the first.
> fix: invalid exports.types field

- packages/document/docs/en/plugin/official-plugins/rss.mdx
- packages/document/docs/zh/plugin/official-plugins/rss.mdx
- Add multiple links example to RSS plugin documentation.
- Prettier the md files.
see https://github.com/web-infra-dev/rspress/issues/828
> docs(plugin-rss): add multiple links example

- e2e/tests/plugin-rss.test.ts
- packages/document/docs/en/plugin/official-plugins/rss.mdx
- packages/document/docs/zh/plugin/official-plugins/rss.mdx
- packages/plugin-rss/static/global-components/FeedsAnnotations.tsx
`<link rel="alternative">` is invalid, we should use `<link rel="alternate">` 
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#alternate
https://github.com/web-infra-dev/rspress/issues/828
> fix(plugin-rss): invalid link rel type

- packages/core/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
vite is not directly dependent on rspress as devDependencies (only indirectly dependent in vitest).
> chore(deps): remove useless vite devDeps

- .changeset/moody-frogs-end.md
- .changeset/nasty-carrots-share.md
- packages/theme-default/src/components/HomeHero/index.module.scss
- packages/theme-default/src/components/HomeHero/index.tsx
Make the homepage mask vertically centered based on the logo.
Now the height of the mask is fixed, I'm not sure if this needs to be changed or not.
[#897](https://github.com/web-infra-dev/rspress/issues/897) [Bug]: The position of the homepage mask is offset from the logo
> fix(theme): homepage mask based on logo vertical centering

- .changeset/config.json
Disable changeset changelog, we now use GitHub releases to generate changelog.
https://github.com/web-infra-dev/rspress/pull/918
> chore(workflow): disable changeset changelog

- packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
- packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
add missing parseToolOptions options in `@rspress/plugin-api-docgen` doc
> docs: parseToolOptions in @rspress/plugin-api-docgen

- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/src/node/searchIndex.ts
- packages/shared/src/types/index.ts
- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
- packages/theme-default/src/components/Search/logic/types.ts
- packages/theme-default/src/logic/useFullTextSearch.ts
- added new `search.versioned` option to config
- removed redundant `.filter` by lang in `LocalProvider`
- fetch new index on version change (if enabled) in `SearchPanel`
#947
> feat: support separate search indexes by version

- packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
- packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
- packages/plugin-api-docgen/package.json
- packages/plugin-api-docgen/src/docgen.ts
- packages/plugin-api-docgen/src/types.ts
If the parser is `react-docgen-typescript`, the `withDefaultConfig` method is used by default to create a parser instance. If `tsconfigPath` or `compilerOptions` is configured, the `withCompilerOptions` and `withCustomConfig` methods are used to create the parser instance respectively. See [Custom Parsers](https://github.com/styleguidist/react-docgen-typescript/blob/b7ea0a235efb7c78a1158ca12d864de2bc2ee30e/README.md#usage) for details.
> feat(api-docgen): support more config to init parser instance

- .changeset/spotty-pumas-travel.md
- packages/shared/src/runtime-utils/index.test.ts
- packages/shared/src/runtime-utils/index.ts
This PR fixes an issue where URLs containing dots were not correctly appended with the `.html` extension.
```text
/guide/version-0.1
expect:
/guide/version-0.1.html
actual:
/guide/version-0.1
```
https://github.com/web-infra-dev/rspress/issues/933
> fix: url containing dots were not correctly normalized with .html extension

- packages/core/src/node/route/RouteService.ts
handle `.html` extension separately, because `extensions` can be overridden via config, but it's always present in the output.
closes #965
> fix: checkDeadLinks when mdxRs is set to false

- e2e/fixtures/tabs-component/doc/index.mdx
- e2e/fixtures/tabs-component/package.json
- e2e/fixtures/tabs-component/rspress.config.ts
- e2e/tests/tabs-component.test.ts
- packages/theme-default/src/components/Tabs/index.tsx
- pnpm-lock.yaml
Fix page crashes if Tabs has single Tab child.
https://github.com/web-infra-dev/rspress/issues/971
> fix: page crashes if Tabs has single Tab child

- packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
- packages/theme-default/src/styles/vars.css
Add divider border for h2 title.
This is a common design in software documents (such as [next.js doc](https://nextjs.org/docs)), which can make the boundaries of paragraphs clearer and help read long documents.
Preview:
> feat: add divider border for h2 title

- e2e/fixtures/tabs-component/doc/index.mdx
- e2e/tests/tabs-component.test.ts
- packages/theme-default/src/components/Tabs/index.tsx
fix tabs component children contains linebreak or with no tab
> fix: Tabs component children contains linebreak or with no tab

- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
remove flex-center in sidebar item to avoid unexpected display of white-space
before:
after:
> chore: remove flex-center in sidebar item

- .changeset/green-eagles-hide.md
- packages/theme-default/src/components/LocalSideBar/index.tsx
- packages/theme-default/src/layout/DocLayout/index.tsx
> fix(theme): set outline title in mobile view to `themeConfig.outlineTitle`

- .changeset/real-cobras-double.md
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/NavScreen/index.tsx
> fix(theme): remove invalid `className`

- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/index.md
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/index.md
- packages/shared/src/types/index.ts
- packages/theme-default/src/layout/Layout/index.tsx
Updated the logic for generating the home page title to include the titleSuffix from frontmatter if available, using the format ${mainTitle} - ${frontmatter.titleSuffix}, or defaulting to mainTitle if titleSuffix is not present.
> ✨ feat(route): Update home page title with frontmatter titleSuffix

- packages/theme-default/src/layout/DocLayout/docComponents/table.tsx
Improve table border style in dark mode, the current table border color is too "light" and can be more soft.
- Before:
- After:
> feat: improve table border style in dark mode

- packages/shared/src/runtime-utils/index.test.ts
- packages/shared/src/runtime-utils/index.ts
sidebar not display using cleanUrls: true when visit with .html suffix
closes: #933
> fix: sidebar not display using cleanUrls: true when visit with .html suffix

- packages/document/docs/en/guide/start/introduction.mdx
- packages/document/docs/zh/guide/start/introduction.mdx
- packages/document/rspress.config.ts
Enable cleanUrls for website to make the URL shorter.
https://rspress.dev/api/config/config-basic.html#routecleanurls
> docs: enable cleanUrls for website

- packages/theme-default/src/styles/base.css
change the global styles of `font-synthesis` from `none` to `style`
Consistent with Vitepress: https://github.com/vuejs/vitepress/blob/7ed5148260052840c44bae64a670d8d610999dbe/src/client/theme-default/styles/base.css#L42
closes: #984
> style: modify font-synthesis from none to style

- packages/document/docs/en/api/config/config-build.mdx
- packages/document/docs/zh/api/config/config-build.mdx
Improve `markdown.highlightLanguages` document:
- Add the default value.
- Add `html` because it is supported by default.
- Add plugin Shiki link.
> docs: improve `markdown.highlightLanguages`

- .changeset/serious-ways-kneel.md
- packages/theme-default/src/components/LocalSideBar/index.scss
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/styles/base.css
- packages/theme-default/src/styles/preflight.css
Fix the style pollution of tailwind preflight for buttons in all kinds of component library such as `antd`, `@douyinfe/semi`， etc.
> fix: tailwind preflight style pollution

- packages/theme-default/src/components/Search/SearchPanel.tsx
> feat: apply i18n searchPlaceholderText to SearchPanel component

- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/fragments/internal-components.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/fragments/internal-components.mdx
Add hero text line breaks guide to document.
See: https://github.com/web-infra-dev/rspress/issues/184
> docs: add hero text line breaks guide

- .github/workflows/lint.yml
add `.github/workflows/lint.yaml` action
Maybe it will be harsh in some e2e, but we can avoid it by `--ignore-path`
#999
> chore(action): add check-dependency-version action

- e2e/tests/title-suffix.test.ts
Fix title suffix case occasionally failed, check the generated HTML files instead of go to the pages.
https://github.com/web-infra-dev/rspress/actions/runs/8832509957/job/24249962993
> test(e2e): fix title suffix case occasionally failed

- e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
- e2e/fixtures/auto-nav-sidebar/doc/api/single-page.mdx
- e2e/tests/auto-nav-sidebar.test.ts
- packages/theme-default/src/components/Overview/index.tsx
support single file overview in order
> feat: support single file overview in order

- .changeset/famous-bees-care.md
- packages/theme-default/src/logic/TabDataContext.ts
> fix: tabData undefined when syncIndex

- e2e/fixtures/auto-nav-sidebar/doc/api/config/_meta.json
- e2e/fixtures/auto-nav-sidebar/doc/api/config/config-extname.json.mdx
- e2e/tests/auto-nav-sidebar.test.ts
- packages/plugin-auto-nav-sidebar/src/utils.ts
- packages/plugin-auto-nav-sidebar/src/walk.ts
> fix: filename contain extname like suffix

- packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
click here can not toggle collapse of the sidebar which with link for navigate
> fix: sidebar with link collapse

- e2e/tests/auto-nav-sidebar.test.ts
- packages/plugin-auto-nav-sidebar/src/utils.ts
when a sidebar dir not have the same name file or index file, we should return undefined
> fix: sidebar navigate link error

- packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
Merge duplicated border CSS to reduce the CSS size.
> fix: merge duplicated border CSS

- e2e/fixtures/modern-js/package.json
- e2e/tests/modern-js.test.ts
> test: add modern-js module doc fixed iframe test

- e2e/fixtures/modern-js/package.json
- e2e/tests/modern-js.test.ts
- packages/core/src/node/initRsbuild.ts
In a module project, the sideEffects usually be
```
"sideEffects": [
"**/*.css",
"**/*.less",
"**/*.sass",
"**/*.scss"
],
```
when we use module doc plugin, it will build a web project, the sideEffects config will influence the tree-shaking behaviour of global styles virtual module, which caused some styles broken in the current version of rspress.
> fix: globalStyles being shaked when config some sideEffects

- e2e/tests/page-type-home.test.ts
- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/fragments/internal-components.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/fragments/internal-components.mdx
- packages/shared/src/types/index.ts
- packages/theme-default/src/components/HomeHero/index.tsx
hero page image src supports light and dark
> feat: hero page image src supports light and dark

- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
- packages/core/tests/prismLanguages.test.ts
- packages/core/tests/prismLanguages/index.mdx
> fix: sort for prism runtime module export to pass test

- packages/core/src/node/runtimeModule/routeData.ts
Generate route virtual modules based on `isSSR` in different build modes. 
Not generate ssr route runtime module when client build.
This avoids the SSR routing virtual module generated by client build from affecting the module number calculation of lazy compilation.
When ssr build, the client route runtime module still generated since some route match logic function need this structure.
https://github.com/web-infra-dev/rspack/pull/5915
> fix: not generate ssr route runtime module when client build

- packages/theme-default/src/components/Search/SearchPanel.tsx
the ResultItem has been normalized to display, when use enter, we use `currentSuggestionIndex` to locate, so the normalize behaviour should be align with it.
> fix: link error when use keyboard to enter search result

- packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.module.scss
Fixed #1092 
This issue also exists without sidebar.
This is because the area size of the content `padding-left` is `24px`, and due to the `font-size` of h1 being `1.875em`, which is `30px`, the size of the anchor's `margin-left` is `26.1px`, so exceeding it will be hidden. In contrast, the `font-size` of h1 in `vitepress` is fixed at `28px`, so this issue will not occur.
The solution is as follows:
1. Change the baseline `font-size` of the title
2. Expand the content area `padding-left` to `26px`
#1092
> fix(theme-default): heading anchor doesn't display when no sidebar or minimum content area

- packages/create-rspress/template/tsconfig.json
- packages/document/tsconfig.json
Enable MDX type hints to provide better DX:
https://github.com/mdx-js/mdx-analyzer?tab=readme-ov-file#typescript
> feat(create-rspress): enable mdx type hints by default

- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/components/Search/NoSearchResult.tsx
- packages/theme-default/src/logic/useLocaleSiteData.ts
support custom searchNoResultsText and searchSuggestedQueryText
> feat: support custom searchNoResultsText and searchSuggestedQueryText

- packages/theme-default/src/components/Search/SearchPanel.tsx
we should use lodash.isEqual to judge whether two object-element array is same.
> fix: search item click target set

- packages/theme-default/src/components/Search/SearchPanel.tsx
fix the search panel cannot be open and close normally when use cmd+k
> fix: cmd+k search issue

- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
There may be duplicate search results when there are multiple languages ​​in the search keyword
> fix: search result duplicate when keyword contains multiple langs

- packages/theme-default/src/components/Search/SearchPanel.tsx
Since rspack supports `exportPresence: error`, the rspress build will fail with a virtual-search-hooks import error.
fix rspack ci: https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/9297474700/job/25587743282
> fix: virtual-search-hooks import error

- packages/theme-default/src/components/HomeHero/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
- packages/theme-default/tailwind.config.ts
Increase the title font size to distinguish from the main text, especially for h3 / h4.
> feat: increase title font size to distinguish from main text

- packages/plugin-playground/src/web/editor.tsx
- packages/plugin-playground/src/web/index.ts
Above issue arises after updating Rsbuild version.
> fix(plugin-playground): export EditorProps error

- e2e/utils/runCommands.ts
optimize error log, should print error log when process unexpected exit
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/9479241139/job/26117554452
> test: should print error log when process unexpected exit

- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/runtimeModule/i18n.ts
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
Format JSON in generated virtual modules.
This can help to display readable code frames when there are some syntax errors in the virtual modules.
For example:
- before
- after
> feat: format JSON in generated virtual modules

- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
- packages/core/tests/prismLanguages.test.ts
- packages/plugin-preview/src/index.ts
highlightLanguages analysis is built-in in mdx-rs, we need to add extraHighlightLanguages in preview plugin which using mdx-js to perform code block
> fix: code highlight in preview plugin

- e2e/tests/custom-headers.test.ts
- packages/core/src/node/build.ts
https://github.com/web-infra-dev/rspress/issues/1164#issuecomment-2160793685
close #1164
> fix(core): duplicate html title tags during ssg

- packages/runtime/src/utils.ts
Only append base to internal non-relative urls, to prevent conflict between `base` and `output.assetPrefix` when using relative urls.
> fix: only append base to internal non-relative urls

- packages/cli/src/index.ts
Actively exit the process when gracefully shutdown.
> feat: better gracefully shutdown

- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/fragments/internal-components.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/fragments/internal-components.mdx
Fix OG tags examples, should use `property` and `content`.
https://ogp.me/
> docs: fix OG tags examples

- packages/theme-default/src/components/Search/SearchPanel.tsx
fix async request race condition
搜索框的请求，提交结果时，应遵循 "后发出优先" 
For the request of the search box, when submitting the results, you should follow the "post priority"
> fix: search panel race condition

- packages/core/src/node/build.ts
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/runtimeModule/index.ts
- packages/shared/src/runtime-utils/index.ts
make clientBuilder and serverBuilder merged into one rsbuild builder
some benefits
1. make DEBUG mode align with Rsbuild, and debug the ssg build easily
2. performance better (to be measured)
3. more maintainable
close #1167
> refactor: when ssg build, init only one rsbuild instance

- packages/document/rspress.config.ts
enable `dev.lazyCompilation` to improve dev start performance.
> chore: enable dev.lazyCompilation in website

- packages/theme-default/src/components/HomeFooter/index.tsx
Should not render an empty footer if `footer.message` is not set:
> fix: should not render empty footer

- packages/theme-default/src/logic/utils.ts
closes: #1258 
replace `<list>` to prevent disappearing in dom, but not replace \<number\>
**source code**
**origin**
**now**
> fix: replace < in render inline markdown

- e2e/fixtures/modern-js/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/create-rspress/package.json
- packages/document/package.json
- packages/modern-plugin-rspress/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-auto-nav-sidebar/package.json
- packages/plugin-client-redirects/package.json
- packages/plugin-last-updated/package.json
- packages/plugin-medium-zoom/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/plugin-rss/package.json
- packages/plugin-shiki/package.json
- packages/plugin-typedoc/package.json
- packages/runtime/package.json
- packages/shared/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
bump TypeScript v5.5 to support more tsconfig.json options like `moduleResolution: 'bundler'`.
> chore(deps): bump TypeScript v5.5

- packages/modern-plugin-rspress/package.json
No `types` declared in current `exports` field, it will break in ESM project. And since we're only publishing single CJS entry. We don't need to use exports field.
> build(@modern-js/plugin-rspress): remove exports field

- .changeset/chilly-cycles-agree.md
- packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
Adjust the font size of the 'dir' sidebar to be the same as the 'title' sidebar
before:
after:
> fix(theme): adjust the dir sidebar font size

- packages/theme-default/package.json
- pnpm-lock.yaml
globby is pre-compiled in `@rspress/core` and not used in `@rspress/theme-default`
closes: #1286
> fix(theme-default): remove globby in deps

- e2e/fixtures/custom-layout-ui-switch/doc/index.mdx
- e2e/fixtures/custom-layout-ui-switch/package.json
- e2e/fixtures/custom-layout-ui-switch/rspress.config.ts
- e2e/fixtures/custom-layout-ui-switch/theme/index.tsx
- e2e/fixtures/custom-layout-ui-switch/tsconfig.json
- e2e/tests/custom-layout-ui-switch.test.ts
- packages/theme-default/src/layout/Layout/index.tsx
- pnpm-lock.yaml
Fix the `uiSwitch` prop of Layout component not work.
> fix(theme-default): uiSwitch prop of Layout component not work

- packages/theme-default/src/node/source-build-plugin.ts
tailwindcss is a devDependency, and this logic only used to debug.
https://github.com/web-infra-dev/rspress/pull/600/files
https://github.com/web-infra-dev/rspress/pull/471/files
> fix: catch can not found tailwindcss error when debug

- .npmrc
- packages/core/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-client-redirects/package.json
- packages/plugin-medium-zoom/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/plugin-rss/package.json
- packages/plugin-typedoc/package.json
- packages/theme-default/package.json
- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
- pnpm-lock.yaml
flexsearch 0.7.x designed new API for document search this commit adopted the new API
> feat(search): upgrade flexsearch 0.7 and adopt the new API design

- .changeset/thick-moons-cry.md
- packages/cli/src/index.ts
before:
1. rspress will watch all file in doc root dir, but only handle some config file.
2. all the `_meta.json` in cwd are watched.
now
1. only watch `_meta.json` files in doc root dir.
> fix(watch): improve watch solution, ignore _meta.json out of doc root dir

- .changeset/cyan-yaks-pull.md
- packages/cli/src/index.ts
some patch for #1312 .
we should watch whole doc root. cause user will add or delete `md` file.
> fix: should watch whole doc root dir for add/delete file

- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/en/guide/default-theme/navbar.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/document/docs/zh/guide/default-theme/navbar.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/components/SocialLinks/LinkContent.tsx
- packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Replacing `twitter` with `X`, with new logo and config name
SKIP
> feat(theme): replace twitter with x in soicalLinks config

- e2e/fixtures/page-type-home/doc/index.md
- e2e/tests/page-type-home.test.ts
- packages/theme-default/src/components/HomeFeature/index.tsx
`normalizeHrefInRuntime(withBase(rawLink, routePath))` will generate a `/index`, which will cause unexpected window href if user click a feature component without link configured.
> fix: window unexpected href when feature link is not configured

- packages/theme-default/src/logic/useRedirect4FirstVisit.ts
When the request comes from a bot (such as Google's crawler), Rspress should not redirect the page.
This change should fix the "Page with redirect" warning of Google:
The RegExp is referenced from https://www.npmjs.com/package/isbot
> fix: should not redirect when page is visited by bot

- packages/document/docs/en/guide/advanced/custom-theme.mdx
- packages/document/docs/en/guide/basic/use-mdx.mdx
- packages/document/docs/zh/guide/advanced/custom-theme.mdx
- packages/document/docs/zh/guide/basic/use-mdx.mdx
Add link and example for `using components` in pages.
<details>
<summary> Preview `en` </summary>
</details>
<details>
<summary> Preview `cn` </summary>
</details>
close: #1284
> docs: link and example on using components

- packages/document/docs/en/guide/basic/use-mdx.mdx
- packages/document/docs/zh/guide/basic/use-mdx.mdx
- packages/plugin-container-syntax/container.css
Re-design container colors:
Before this PR, `tip` `note` and `info` are all green, with no distinction between them. So this PR re-adjusts the colors, Note is gray, Tip is green, and Note is blue.
- before (light):
- after (light):
- before (dark): 
- after (dark):
> feat: re-design container colors

- e2e/fixtures/package-manager-tabs/doc/index.mdx
- e2e/fixtures/package-manager-tabs/package.json
- e2e/fixtures/package-manager-tabs/rspress.config.ts
- e2e/tests/package-manager-tabs.test.ts
- packages/theme-default/src/components/PackageManagerTabs/index.tsx
- pnpm-lock.yaml
Do special treatment for `yarn create` command, do not use `@latest`
#1357
> fix: yarn create command in PackageManagerTabs

- packages/theme-default/src/components/Overview/index.module.scss
- packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
The `word-break: break-all` has been deprecated, see https://developer.mozilla.org/en-US/docs/Web/CSS/word-break.
Using `overflow-wrap: break-word` is more conservative, it only breaking words when necessary, while `word-break: break-all` is more aggressive and will break words at any opportunity.
- https://github.com/web-infra-dev/rspress/pull/369
> fix(style): improve work break for a tags

- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/SuggestItem.tsx
- packages/theme-default/src/components/Search/index.module.scss
fix the problem that when switching the search data up and down by the keyboard's arrow keys, the highlighting effect conflicts with the mouse hover effect, and the highlighted elements are messed up.
closes: [#1364](https://github.com/web-infra-dev/rspress/issues/1364)
> fix(theme): fix highlight effect when operating with keyboard (#1364)

- packages/plugin-auto-nav-sidebar/src/index.ts
- packages/plugin-auto-nav-sidebar/src/utils.ts
- packages/plugin-auto-nav-sidebar/src/walk.ts
closes #1327 
closes #1349
closes #1365
> fix(plugin-auto-nav-sidebar): auto generated sidebar should consider `route.extensions` when `_meta.json` don't exists

- packages/core/src/node/dev.ts
problem: dev command make search_index.json write to default outDir when outDir is set in plugin, when search trigger, dev server will halt because search_index.json not exists in final outDir.
> fix(core): fix writeSearchIndex function use userConfig instead modifiedConfig

- packages/theme-default/src/components/Search/logic/search.ts
This commit fixes #1372
[](https://github.com/web-infra-dev/rspress/issues/1372)
> fix(theme-default): search logic stop when header matches

- packages/theme-default/src/components/SocialLinks/index.module.scss
This commit fixes an issue where a single <a> tag in the SocialLinks component would have an unwanted margin-left, causing misalignment. The issue is resolved by using the :only-child pseudo-class to remove the margin-left when there is
only one <a> tag.
Updated index.module.scss to include the necessary CSS selector.
> fix: remove margin-left for single a tag in SocialLinks component

- packages/theme-default/src/components/Aside/index.scss
- packages/theme-default/src/components/Aside/index.tsx
- packages/theme-default/src/logic/sideEffects.ts
The structure of the toc dom was modified to highlight the differences between the spacing of toc's items and the text spacing within each item.
closes #1385
> feat(theme-default): display complete content of toc in aside component

- packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/Search/index.module.scss
- packages/theme-default/src/logic/useNav.ts
Use a compact layout when there are many nav items, this ensures that nav items can be displayed as much as possible on small screens.
- before:
- after:
> feat(style): use a compact layout when there are many nav items

- packages/document/docs/en/guide/start/introduction.mdx
- packages/theme-default/src/styles/vars.css
Improve the color contrast of default theme in dark mode.
According to [WebAIM](https://webaim.org/resources/contrastchecker/), the default color contrast for Rspress is low at 11, which makes the docs difficult to read. Here I changed the default theme color to improve the contrast ratio to 16.
Here i changed the default theme color to improve the contrast to 16. 
Some data for reference:
|Site| Contrast (by WebAIM)|
|----|--------------|
|NextJS|17.93|
|ReactJS|13.95|
|Rspress (before this PR)|11.65|
|Rspress (after this PR)| 16.9|
> feat(theme-default): adjust the color contrast in dark mode

- packages/core/src/node/initRsbuild.ts
Enable the Rsbuild CLI shortcuts feature:
https://rsbuild.dev/config/dev/cli-shortcuts
> feat: enable Rsbuild CLI shortcuts

- packages/document/docs/en/api/client-api/api-components.mdx
- packages/document/docs/en/fragments/builtin-components.mdx
- packages/document/docs/en/guide/default-theme/components.mdx
- packages/document/docs/zh/api/client-api/api-components.mdx
- packages/document/docs/zh/fragments/builtin-components.mdx
- packages/document/docs/zh/guide/default-theme/components.mdx
- packages/theme-default/src/components/Badge/index.module.scss
- packages/theme-default/src/components/Badge/index.tsx
> Shout out to shadcn/ui and Vitepress for inspiration.
- Custom children: this is particularly useful for adding icons.
- `outline` support: more variations!
- Style tweak:
- use CSS variables from containers to look consistent.
- fixes default badge being invisible in Dark mode.
- better vertically aligned with different headings.
- Changes to `type` props:
- add `info` type to be consistent with containers.
- `tip` is added as the new default.
Do note that even though this kept untyped `<Badge>` unchanged, it
does introduce a **benign** breaking change to `<Badge type="info">`.
Light mode:
Dark mode:
- Badges docs are updated to reflect the new usages and new types.
- This MR correct "Internal Components" to be "Built-in Components".
(does not involve URL changes due to the use of …
> feat(theme-default): children, outline and fixes for Badge

- modern.config.js
Remove unused modern config file as `@modern-js/monorepo-tools` has been removed:
https://github.com/web-infra-dev/rspress/pull/918
> chore: remove unused modern config file

- packages/core/src/node/runtimeModule/siteData/extractPageData.ts
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/runtime/src/hooks.ts
closes: #1475 
https://github.com/web-infra-dev/rspress/pull/1472
> fix(perf): remove the _html size in runtime module

- packages/core/src/node/runtimeModule/i18n.ts
> fix: load i18n source without cache

- e2e/tests/i18n.test.ts
- packages/theme-default/src/components/Overview/index.tsx
- pnpm-lock.yaml
This PR adds a filtering functionality to the Overview component in the default theme to help with Rspress sites with a large number of APIs.
> feat(theme-default): Support Filter for API Overview

- packages/theme-default/src/components/PrevNextPage/index.tsx
In the previous/next page links at the bottom of docs pages, the text used to read "Previous Page" (title case) and "Next page" (sentence case). This changes the "Next Page" link to title case so that the two links match style.
> fix(theme-default): Capitalise the 'P' in 'Next page'

- package.json
Our project use pnpm to manage dependencies and requires corepack installed and enabled:
corepack enable
corepack enable npm
https://github.com/web-infra-dev/rspress/issues/1496
> Update prepare target in package.json to use pnpm

- .changeset/blue-fireants-rescue.md
- packages/document/docs/en/api/index.mdx
- packages/document/docs/en/guide/default-theme/overview-page.mdx
- packages/document/docs/zh/api/index.mdx
- packages/document/docs/zh/guide/default-theme/overview-page.mdx
- packages/theme-default/src/components/Overview/index.tsx
A solution to fix https://github.com/web-infra-dev/rspress/pull/1493#discussion_r1804705782
> fix: use front matter as overview page title

- .changeset/breezy-islands-argue.md
- .changeset/hip-bulldogs-build.md
- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/components/Overview/index.tsx
- packages/theme-default/src/logic/useLocaleSiteData.ts
> feat: support location of overview and search docs

- packages/core/src/node/PluginDriver.ts
When calling modifyConfig, if some plugins call `removePlugin` or `addPlugin`, the index of the plugin in `this.#plugins` will change. Since `addPlugin` uses `push`, it will not affect the index of other plugins. If it is `removePlugin`, it is necessary to consider whether the plugin to be removed is before the current traversal index. If so, the plugins after the index will move forward 1 in `this.#plugins`. If not, there will be no impact.
Closes #1487
> fix: correctly iterate over plugins when using `removePlugin`

- .changeset/tender-hornets-obey.md
- packages/document/docs/en/fragments/builtin-components.mdx
- packages/document/docs/zh/fragments/builtin-components.mdx
- packages/theme-default/src/components/Card/index.tsx
- packages/theme-default/src/components/LinkCard/index.module.scss
- packages/theme-default/src/components/LinkCard/index.tsx
- packages/theme-default/src/components/index.tsx
> feat: support Card and LinkCard components

- packages/core/src/node/initRsbuild.ts
close: #1514 
Use default value of browserslist of Rsbuild, see https://rsbuild.dev/guide/advanced/browserslist#default-browserslist.
Now users can set browserslist in `builderConfig.output.overrideBrowserslist`.
> fix: remove built-in override browserslist

- .changeset/cool-lobsters-decide.md
- packages/theme-default/src/components/Nav/NavBarTitle.tsx
logo dom only display when logo exists
> fix: logo dom only displays when logo exists

- packages/theme-default/src/logic/useLocaleSiteData.ts
`langRoutePrefix` is used at https://github.com/web-infra-dev/rspress/blob/ae1bf881bbed54b13c7f31d457eb9984806c50d3/packages/theme-default/src/components/Nav/NavBarTitle.tsx#L47
Without the trailing slash, for located pages, it renders `/zh` for example, which means `/zh.html` but it should be `/zh/index.html` actually. And this change matches the default `langRoutePrefix` (`/`).
> fix: langRoutePrefix should end with slash

- packages/theme-default/src/components/Overview/index.tsx
align with margin-bottom of h1 in basic page
> chore: add margin bottom for overview page h1

- packages/cli/bin/rspress.js
Enable Node.js 22 new compile cache in Rspress CLI, this makes Node.js startup faster.
- before:
- after:
- https://nodejs.org/id/blog/release/v22.8.0
- https://github.com/nodejs/node/pull/54501
- https://github.com/web-infra-dev/rsbuild/pull/3627
- https://github.com/web-infra-dev/rspack/pull/8331
> perf(cli): enable Node.js compile cache

- packages/theme-default/src/styles/code.css
Fix incorrect code link color.
- Input:
```md
[`This is code link`](https://rsbuild.dev/)
[This is link](https://rsbuild.dev/)
`This is code`
```
- before this PR:
- with this PR:
We have fixed this issue in https://github.com/web-infra-dev/rspress/pull/1016, but it is broken again. I think LightningCSS changed the CSS priority and caused this bug.
> fix: incorrect code link color

- .changeset/khaki-chefs-deliver.md
- packages/theme-default/src/logic/utils.ts
> fix: remove lookbehind syntax to compatibile with Safari

- packages/theme-default/src/components/Aside/index.scss
> fix: aside text should break word

- e2e/tests/auto-nav-sidebar-dir-convension.test.ts
- packages/theme-default/src/components/Sidebar/index.tsx
- packages/theme-default/src/index.ts
- packages/theme-default/src/logic/useSidebarData.ts
- packages/theme-default/src/logic/utils.ts
fix(sidebar): index convention /api/index.html /api/index /api should show same sidebar
https://github.com/web-infra-dev/rspress/pull/1572
https://github.com/web-infra-dev/rspress/pull/1575
> fix(sidebar): /api/index.html /api/index /api  should show same sidebar

- packages/cli/package.json
- packages/document/docs/en/guide/start/getting-started.mdx
- packages/document/docs/zh/guide/start/getting-started.mdx
- packages/document/package.json
- packages/shared/package.json
- pnpm-lock.yaml
Rspress uses Rsbuild's `loadConfig` method to load config, so `ts-node` is no longer required.
> docs: ts-node is no longer required

- .github/workflows/lint.yml
- .github/workflows/release-nightly.yml
- .github/workflows/release-pull-request-with-modernjs.yml
- .github/workflows/release-pull-request-without-modernjs.yml
- .github/workflows/release.yml
- .github/workflows/test-Windows.yml
- .github/workflows/test-macOS.yml
Update to Node 22 (current LTS) to make CI faster.
> chore(CI): update to Node 22

- .github/workflows/test-Windows.yml
- .github/workflows/test-macOS.yml
Reduce playwright install time, only `chromium` is required.
https://playwright.dev/docs/browsers#install-system-dependencies
> chore(CI): reduce playwright install time

- .changeset/new-students-promise.md
- packages/core/package.json
- packages/modern-plugin-rspress/package.json
- packages/modern-plugin-rspress/src/lanchDoc.ts
- packages/modern-plugin-rspress/src/utils.ts
- packages/plugin-api-docgen/package.json
- packages/plugin-api-docgen/src/docgen.ts
- packages/plugin-api-docgen/src/index.ts
- pnpm-lock.yaml
`@modern-js/utils` is an internal package of [Modern.js](https://github.com/web-infra-dev/modern.js), Rspress should not depend on it.
> fix: remove `@modern-js/utils` dependency

- e2e/fixtures/custom-plugin/package.json
- e2e/fixtures/plugin-preview/package.json
- packages/theme-default/package.json
- packages/theme-default/src/components/LocalSideBar/index.scss
- packages/theme-default/src/components/LocalSideBar/index.tsx
- pnpm-lock.yaml
Remove `react-transition-group` dependency to reduce bundle size.
- before (550kB)
- after (543kB)
> perf: remove `react-transition-group` dependency

- package.json
https://github.com/pnpm/pnpm/issues/7951#issuecomment-2438065169
Latest version of pnpm changed some behaviour, and the renovate generated PR will remove `pnpmfileChecksum` filed in lockfile which will cause no frozen lockfile error that breaks CI.
> chore: downgraden pnpm to 9.12.0 to avoid renovate break

- e2e/fixtures/inline-markdown/doc/index.mdx
- e2e/tests/inline-markdown.test.ts
- packages/theme-default/package.json
- packages/theme-default/src/logic/utils.ts
- pnpm-lock.yaml
use a lighter solution to check html validity in the browser
close: #1582 
close: #1592
> fix: remove htmlparser2 and use reg to check valid html elements

- packages/core/src/node/PluginDriver.ts
- packages/shared/src/runtime-utils/index.ts
Avoid to influence normal debug behaviour at users side.
This is a temporary solution.
> fix: use rspress-dev as debug mode for source build plugin

- packages/plugin-preview/static/global-components/common/index.scss
> fix(plugin-preview): dark mode card border color

- e2e/fixtures/inline-markdown/doc/inline/all.mdx
- e2e/tests/inline-markdown.test.ts
- packages/theme-default/src/logic/utils.ts
performace regression of check html regex
> fix: performance regression of check html regex

- packages/document/docs/en/guide/advanced/custom-theme.mdx
- packages/document/docs/zh/guide/advanced/custom-theme.mdx
- packages/theme-default/src/layout/DocLayout/index.tsx
- packages/theme-default/src/layout/Layout/index.tsx
The `DocLayout` uses internal components to render MDX nodes. There is no documented way (as far as I can tell) to override these nodes without providing an entirely custom `DocLayout` component altogether.
To address this, allow the user to provide `components` to the `Layout` component. In the future, maybe the DocLayout could be extended to handle arbitrary nodes as well.
Related to #1362 because this feature will allow the user to override and customize known MDX nodes.
- ~[ ] Tests updated (or not required).~
> feat: custom doc-layout components

- packages/core/package.json
- packages/core/src/index.ts
- packages/runtime/package.json
- packages/shared/package.json
- packages/shared/src/node-utils.ts
- packages/shared/src/node-utils/merge.ts
- packages/shared/src/runtime-utils/index.ts
- pnpm-lock.yaml
`mergeDocConfig` is only used by Node.js code, so it can be moved from `shared/src/runtime-utils` to `shared/src/node-utils`. This can reduce runtime code and remove lodash methods.
This PR also removed some unused `bin` from `files` field.
- before (464kB):
- after (453kB):
> perf(shared): move `mergeDocConfig` to node utils

- packages/plugin-client-redirects/package.json
- pnpm-lock.yaml
Fix plugin-client-redirects missing `@rspress/shared` dependency:
> fix(plugin-client-redirects): missing `@rspress/shared` dependency

- packages/core/src/node/initRsbuild.ts
- packages/document/docs/en/api/config/config-build.mdx
- packages/document/docs/zh/api/config/config-build.mdx
- packages/modern-plugin-rspress/src/lanchDoc.ts
- packages/theme-default/src/node/source-build-plugin.ts
chore: use `resolve.alias` instead of `source.alias`
> chore: use `resolve.alias` instead of `source.alias`

- .changeset/gold-spiders-hide.md
- e2e/fixtures/nested-overview/rspress.config.ts
- e2e/tests/nested-overview.test.ts
- packages/plugin-auto-nav-sidebar/src/walk.ts
- packages/shared/src/runtime-utils/index.ts
- packages/theme-default/src/components/Overview/utils.ts
empty Overview when using base together
> fix(theme): Overview component cannot be used when using base

- packages/theme-default/src/styles/base.css
Add `overflow-wrap` CSS to break long words.
resolve https://github.com/web-infra-dev/rsbuild/issues/4166
> fix: add overflow-wrap to break long words

- .changeset/gold-spiders-hide.md
- .changeset/loud-fans-wait.md
- packages/cli/package.json
- packages/core/package.json
- packages/create-rspress/package.json
- packages/document/package.json
- packages/modern-plugin-rspress/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-auto-nav-sidebar/package.json
- packages/plugin-client-redirects/package.json
- packages/plugin-container-syntax/package.json
- packages/plugin-last-updated/package.json
- packages/plugin-medium-zoom/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/plugin-rss/package.json
- packages/plugin-shiki/package.json
- packages/plugin-typedoc/package.json
- packages/runtime/package.json
- packages/shared/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
* feat: enable incremental by default by @ahabhgk in https://github.com/web-infra-dev/rspress/pull/1631
* feat: add support for React 19 by @chenjiahan in https://github.com/web-infra-dev/rspress/pull/1643
* fix(theme): Overview component cannot be used when using base by @SoonIter in https://github.com/web-infra-dev/rspress/pull/1642
* fix: add overflow-wrap to break long words by @chenjiahan in https://github.com/web-infra-dev/rspress/pull/1650
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rspress/pull/1644
* chore(deps): update dependency framer-motion to v11.13.1 by @renovate in https://github.com/web-infra-dev/rspress/pull/1646
* chore(deps): update dependency nx to v20.2.1 by @renovate in …
> Release v1.38.0

- .changeset/old-rings-warn.md
- packages/plugin-preview/src/index.ts
The preview components is located in `node_modules/.rspress/virtual-demo/`.
We should watch `node_modules` to enable hot update in preview block.
fix: #1652 
https://github.com/web-infra-dev/rsbuild/pull/4058
> fix(plugin-preview): do not ignore node_modules in `watchOptions`

- packages/plugin-preview/src/index.ts
Fix plugin-preview dev-server close, but not assign empty, next afterBuild close error.
> fix(plugin-preview): dev-server is not running

- packages/shared/src/node-utils/merge.ts
> fix(shared): `mergeDocConfig` should dynamic import lodash-es

- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
update docs, `head` config only takes effect in production mode.
> docs: `head` config only takes effect in production mode

- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/en/guide/default-theme/i18n.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/docs/zh/guide/default-theme/i18n.mdx
- packages/shared/src/types/index.ts
The `lang` config is missing from the documentation.
This pull request includes changes to add the `lang` configuration, and specifying default values for various configuration options.
> docs: add `lang` config

- packages/cli/bin/rspress.js
- packages/core/package.json
- packages/core/src/node/searchIndex.ts
- packages/plugin-api-docgen/package.json
- packages/plugin-playground/package.json
- pnpm-lock.yaml
Remove node-fetch polyfill to reduce 7.45MB install size:
- In Node.js >= 18, `fetch` is builtin and enabled by default.
- In Node.js 16, `fetch` can be enabled by the `--experimental-fetch` flag, I have updated the `bin` file to enable it.
- In Rspress 2.0 we can remove this flag from the bin file.
This PR also removed `mdast-util-mdxjs-esm` from two packages because they never use it:
I think the remote search should be redesigned in Rspress 2.0 as it is now a ByteDance SCM only feature.
See: https://github.com/web-infra-dev/rspress/blob/a373b32a6c5fc4db4c11201e2ea1e06b10dd86bc/packages/core/src/node/searchIndex.ts#L42
> perf: remove `node-fetch` polyfill

- e2e/tests/plugin-shiki.test.ts
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
related #1619, #1670
---
@Timeless0911 
Sorry, I didn't test on real-word project previously, and just found
So setting `whiteSpace` on `pre` will not work as expected, this PR fixed it.
And this time, I've tested on my own project by copying the `bundle.js` into `node_modules`.
> fix: codeWrap code element instead

- e2e/tests/heading-title.test.ts
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
- packages/theme-default/src/logic/useSidebarData.ts
1. fix sidebar bug in dev
sidebar hmr has been invalid for a long time... so these codes are useless, we'll support sidebar hmr later by refactoring hmr (updating virtual-modules site-data json)
2. add `rspress-doc-title` to h1
related to https://github.com/web-infra-dev/rspress/issues/1556
> fix(siderbar): sidebar is not stable in dev and sometimes is set by h1 in md

- .github/ISSUE_TEMPLATE/bug-report.en-US.yml
- .github/ISSUE_TEMPLATE/feature-request.en-US.yml
- .github/workflows/pr-label.yaml
1. Since the `pr-labeler` workflow adds labels to pull requests, it needs the `pull-requests: write` permission.
2. The GitHub issue types work well and we can remove the issue label to reduce duplicated information.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#overview
> chore(CI): correct permissions for issue labeler

- .github/workflows/pr-label.yaml
- .github/workflows/release.yml
Provenance generation in GitHub Actions requires "write" access to the "id-token" and I should not delete it.
I have added comment to prompt the role of this permission.
> chore(CI): fix missing permission for provenance

- .changeset/config.json
- e2e/fixtures/modern-js/modern.config.ts
- e2e/fixtures/modern-js/package.json
- packages/modern-plugin-rspress/package.json
- pnpm-lock.yaml
In this PR, `@modern-js/plugin-rspress` package which used to generate module doc in Modern.js Module projects is renamed to `@rspress/modern-js-plugin` for better npm permission management.
Since we no longer recommend creating new Modern.js Module projects, as we have developed Rslib based on Rsbuild, which is the next-generation Library development tool that will provide better build performance and plugin ecosystem, we will remove `@rspress/modern-js-plugin` in Rspress 2.0.
Users who previously used this plugin can continue to use the old version or switch to the new package name.
> chore: rename `@modern-js/plugin-rspress` to `@rspress/modern-js-plugin`

- packages/cli/bin/rspress.js
Remove the node flag from shebang as it may not work in some environments.
https://github.com/web-infra-dev/rspress/pull/1662#issuecomment-2561590553
> fix(CLI): remove node flag from shebang

- e2e/fixtures/nav-link-item-with-hash/doc/index.mdx
- e2e/fixtures/nav-link-item-with-hash/rspress.config.ts
- e2e/tests/nav-link-item-with-hash.test.ts
- packages/theme-default/src/components/Link/index.tsx
- packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
- packages/theme-default/src/components/Nav/index.tsx
- packages/theme-default/src/components/NavHambmger/index.tsx
- packages/theme-default/src/components/NavScreen/index.tsx
When we click on an item in an hamburger menu, we should close the menu after click event.
Fixes: https://github.com/web-infra-dev/rspress/issues/1711
> fix: close hamburger menu when click on item on mobile

- packages/plugin-preview/src/index.ts
Should use correct default `previewMode`.
`isMobile` should be removed in Rspress 2.0
closes: #1714
> fix(plugin-preview): should use correct default previewMode

- e2e/tests/api-docgen.test.ts
- e2e/utils/search.ts
- packages/plugin-api-docgen/src/index.ts
- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/SuggestItem.tsx
Regex was used incorrectly.
https://github.com/web-infra-dev/rspress/blob/5ec4787e7d993c924595e3d342211990e87f792f/packages/plugin-api-docgen/src/index.ts#L46-L48
> fix(plugin-api-docgen): search index should include generated API doc

- packages/core/src/node/route/RouteService.ts
This TODO comment was introduced in https://github.com/web-infra-dev/rspress/commit/ac0bfb0e2838ccbfd7482e830c2ca39a18f07df3#diff-ca2dde319beb6f6b3cd12a0dbe21569c4b89adb8c0cd50b9cac1197522d3ec10R236-R245.
I tried to add the `/* webpackChunkName: "${route.pageName}" */` back, but it caused two problems:
1. The async chunk name may conflict with the initial chunks.
2. The generated chunk name is quite long and increases the bundle size:
Therefore, I prefer to remove this TODO comment and keep using the default deterministic chunkId of Rspack.
- https://rspack.dev/config/optimization#optimizationchunkids
> chore: remove chunk name TODO

- e2e/fixtures/github-alert-mdxjs/doc/index.mdx
- e2e/tests/github-alert-mdxjs.test.ts
- packages/core/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-container-syntax/package.json
- packages/plugin-container-syntax/src/remarkPlugin.ts
- packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
- packages/plugin-container-syntax/tests/index.test.ts
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/theme-default/package.json
- pnpm-lock.yaml
> feat: support nested container syntax in list and component in mdx-js

- e2e/fixtures/github-alert-mdxrs/doc/index.mdx
- e2e/tests/github-alert-mdxrs.test.ts
- packages/core/package.json
- pnpm-lock.yaml
close #1513
related https://github.com/web-infra-dev/mdx-rs/pull/69
> feat: support nested container syntax in list in mdx-rs

- packages/theme-default/src/components/LinkCard/index.module.scss
- packages/theme-default/src/components/LinkCard/index.tsx
fix: dark mode when hover CardLink component
> fix: dark mode when hover LinkCard component

- packages/cli/src/update.ts
- packages/cli/tsconfig.json
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/src/node/utils/flattenMdxContent.ts
- packages/core/tsconfig.json
- packages/modern-plugin-rspress/tests/tsconfig.json
- packages/modern-plugin-rspress/tsconfig.json
- packages/plugin-api-docgen/tsconfig.json
- packages/plugin-auto-nav-sidebar/tsconfig.json
- packages/plugin-client-redirects/tsconfig.json
- packages/plugin-container-syntax/tsconfig.json
- packages/plugin-last-updated/tsconfig.json
- packages/plugin-medium-zoom/tsconfig.json
- packages/plugin-playground/tsconfig.json
- packages/plugin-preview/tsconfig.json
- packages/plugin-rss/tsconfig.json
- packages/plugin-rss/tsconfig.runtime.json
- packages/plugin-rss/tsconfig.tools.json
- packages/runtime/tsconfig.json
- packages/shared/modern.config.ts
- packages/shared/src/execa.ts
- packages/shared/tsconfig.json
- packages/theme-default/tsconfig.json
this is a trick for implementing "click to reference" of ts-language-server
tsc will build the `.d.ts.map` in memory
so we need to set `rootDir: "src"` `"outDir: "dist""` `composite: true` and tsconfig.reference just like Rsbuild repo
BTW, fix some type error when debugging references
> chore(infra): implement click to reference by tsconfig.reference

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test-Windows.yml
- .github/workflows/test-macOS.yml
Add `npm install -g corepack@latest --force` before `corepack enable` to fix corepack key id mismatch issue.
> `--force` to prevent windows install error
https://github.com/nodejs/corepack/issues/612
> ci(corepack): fix corepack key id mismatch

- packages/cli/tsconfig.json
- packages/core/src/node/PluginDriver.ts
- packages/core/tsconfig.json
- packages/create-rspress/tsconfig.json
- packages/document/tsconfig.json
- packages/modern-plugin-rspress/tsconfig.json
- packages/plugin-api-docgen/tsconfig.json
- packages/plugin-auto-nav-sidebar/tsconfig.json
- packages/plugin-client-redirects/tsconfig.json
- packages/plugin-container-syntax/tsconfig.json
- packages/plugin-last-updated/tsconfig.json
- packages/plugin-medium-zoom/tsconfig.json
- packages/plugin-playground/tsconfig.json
- packages/plugin-preview/tsconfig.json
- packages/plugin-rss/tsconfig.json
- packages/plugin-shiki/tsconfig.json
- packages/plugin-typedoc/tsconfig.json
- packages/runtime/tsconfig.json
- packages/shared/chalk.d.ts
- packages/shared/logger.d.ts
- packages/shared/node-utils.d.ts
- packages/theme-default/tsconfig.json
- tsconfig.json
this is a hack to set `@rspress/shared/chalk` types, after using `"moduleResolution": "bundler"`, it works
it is hard to be understood
https://github.com/web-infra-dev/rspress/pull/1773
> refactor: remove prebundle package's `.d.ts`

- packages/theme-default/src/components/Search/SearchPanel.tsx
Currently Rspress only fetches the search index file when the user focused on the search panel.
This PR allows Rspress to preload the search index when the page is idle, which should improve the search experience.
> feat: preload search index when page is idle

- packages/core/src/node/utils/getSocialIcons.ts
- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
https://github.com/web-infra-dev/rspress/blob/6e66f159b91c3fdedeb935590d752c528a140b59/packages/core/src/node/utils/getSocialIcons.ts#L30
because of https://github.com/web-infra-dev/rspress/pull/1788, we have already remove 'twitter' type... so just remove it completely
https://github.com/web-infra-dev/rspress/pull/1788
> fix: remove socialLinks twitter in redirect and document

- packages/core/loader.cjs
- packages/core/package.json
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/mdx/loader.ts
- packages/plugin-preview/package.json
Rspack supports esm loader now, so let us migrate the cjs loader to esm loader
> refactor: use esm mdx-loader rather than cjs

- .github/workflows/test-Windows.yml
- .github/workflows/test-macOS.yml
- nx.json
- packages/core/src/node/route/RouteService.ts
Use the nx default cache directory `.nx/cache` instead of `.nx-cache`.
This change will reduce the number of folders in the root directory.
- https://nx.dev/recipes/running-tasks/change-cache-location
> chore(workflow): use nx default cache directory

- packages/document/docs/en/fragments/builtin-components.mdx
- packages/document/docs/zh/fragments/builtin-components.mdx
- packages/theme-default/src/components/Tabs/index.module.scss
Improve the style of tabbed code blocks to align them with normal code blocks:
- before:
- after:
> feat: improve tabbed code block style

- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
- packages/theme-default/src/components/Sidebar/index.tsx
- packages/theme-default/src/components/Sidebar/utils.ts
- packages/theme-default/src/components/index.tsx
- packages/theme-default/src/logic/useFullTextSearch.ts
- packages/theme-default/src/logic/useSidebarData.ts
assumes that user's sidebar is as below
```ts
sidebar: {
"/guide/": [
{
"text": "指南",
"items": [
{
"text": "快速上手",
"link": "/guide/quick-start"
},
{
"text": "安装",
"link": "/guide/install"
}
],
"link": "",
"collapsed": false,
"collapsible": true
}
]
}
```
the route which hits `matchPath("/guide/", currentPathname)` `/guide/*`  would be shown
e.g: under `'/guide/quick-start.html'`  would show the `sidebar["/guide"]`
if route hits one item in this config
e.g: `"/guide/quick-start/index.html"` hits `{"text": "快速上手", "link": "/guide/quick-start" }`
and `sidebar["/guide"]` would be shown
In fact, the new algorithm will be more fast in performance, and I think there aren't cases that's not be covered
> refactor(theme): new sidebar match algorithm and export `SidebarList` UI only component

- packages/cli/package.json
- packages/cli/src/index.ts
- packages/core/package.json
- packages/core/src/node/build.ts
- packages/core/src/node/runtimeModule/siteData/highlightLanguages.ts
- packages/core/src/node/searchIndex.ts
- packages/shared/modern.config.ts
- packages/shared/package.json
- packages/shared/src/chalk.ts
- pnpm-lock.yaml
for bundle size, and maintainability
44.2 kB -> 6kb
We currently do not integrate prebundle. When integrating prebundle after migrating Rslib, we can consider picocolors.
https://github.com/web-infra-dev/rspress/pull/1773
https://github.com/web-infra-dev/rspress/pull/1787
https://github.com/web-infra-dev/rspress/pull/1809
https://github.com/web-infra-dev/rspress/pull/1805
> refactor(deps): migrate chalk to picocolors

- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Improve search index fetching with error handling, the error logs will be like:
- https://bsky.app/profile/andrewvijay.bsky.social/post/3lhlbiqbqjk2x
> fix(search): improve search index fetching with error handling

- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/logic/getSidebarDataGroup.test.ts
- packages/theme-default/src/logic/getSidebarDataGroup.ts
- packages/theme-default/src/logic/useFullTextSearch.ts
- packages/theme-default/src/logic/useSidebarData.ts
if sidebar has `'/'`, all the sidebar would match the first one, so we need to sort the key first
```ts
{
'/': [],
'/guide': [
{
text: 'Getting Started',
link: '/guide/getting-started',
},
],
'/guide/item': []
},
```
https://github.com/web-infra-dev/rspress/pull/1780
> fix: sidebar always matches "/"

- packages/core/src/node/initRsbuild.ts
- packages/runtime/src/Content.tsx
Previously, `virtual-routes` and `virtual-routes-ssr` will be bundled in either SSR and non SSR, which will make the routes be eager imported by SSR, although routes are dynamic imported in non SSR.
```js
var __webpack_modules__ = {
"virtual-routes": function(module) {
module.exports = require("virtual-routes");
},
"virtual-routes-ssr": function(module) {
module.exports = require("virtual-routes-ssr");
}
};
```
In this PR, determine the correct module ID as we already know it when initiating the config, which could also remove `require` from ESM code.
> fix(runtime): determine virtual routes by config file

- packages/theme-default/rslib.config.ts
`query: /.*/` works, but I do not recommend this usage which is not written in doc
https://github.com/web-infra-dev/rslib/pull/741
https://rsbuild.dev/zh/plugins/list/plugin-svgr#%E5%85%B7%E5%90%8D%E5%AF%BC%E5%85%A5
> chore(infra): svgr config modification

- packages/theme-default/src/components/Overview/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.module.scss
- Limit the max width for API overview groups.
- Reduce the content width for readability, see:
- https://baymard.com/blog/line-length-readability
- https://www.quora.com/What-is-the-optimal-width-to-use-for-the-text-in-the-body-of-a-website-to-allow-for-easiest-reading
> style(theme-default): adjust layout and media query breakpoints

- packages/document/docs/en/guide/advanced/custom-theme.mdx
- packages/document/docs/zh/guide/advanced/custom-theme.mdx
fix error of using custom search component
close: https://github.com/web-infra-dev/rspress/issues/1818
> docs: fix error of using custom search component

- packages/core/src/node/searchIndex.ts
Serve search json will be failed when `config.outDir` is a absolute path, use same path join strategy from `writeSearchIndex` function instead.
> fix(core): search json path is incorrect when config.outDir is absolute

- packages/theme-default/src/components/Button/index.module.scss
Text should display in center of button
- before
- after
> fix(theme): text in button should center

- packages/core/rslib.config.ts
- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/runtimeModule/siteData/highlightLanguages.ts
Remove possible `require` statement reserved in ESM output, and clean Rslib config by the way.
> fix(core): supersede require with import statement in ESM output

- packages/plugin-shiki/src/shiki/pluginShiki.ts
Provides completion without breaking change, still supports `string` type.
> chore(plugin-shiki): Add completion

- packages/core/src/node/initRsbuild.ts
- packages/runtime/package.json
- packages/runtime/rslib.config.ts
- packages/theme-default/src/logic/useRerender.ts
- packages/theme-default/src/logic/utils.ts
https://github.com/web-infra-dev/rspress/pull/1858
remove
1. global window event listener and `.setup`
- click <a />
- onscroll
- reload
we should use `useLocation` to watch the href change 
2. remove some useless code that is never used
---
updated, only remove some useless code
> refactor(infra): 🔥remove some useless code

- packages/core/src/runtime/App.tsx
- packages/core/src/runtime/clientEntry.tsx
- packages/plugin-preview/static/global-components/common/mobile-operation.tsx
- packages/runtime/rslib.config.ts
- packages/runtime/src/Content.tsx
- packages/runtime/src/index.ts
- packages/runtime/src/route.test.ts
- packages/runtime/src/route.ts
- packages/runtime/src/utils.ts
- packages/runtime/tsconfig.json
- packages/theme-default/src/components/Link/index.tsx
- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
- packages/theme-default/src/components/Sidebar/utils.ts
- packages/theme-default/src/global.d.ts
- packages/theme-default/src/logic/getSidebarDataGroup.test.ts
- packages/theme-default/src/logic/getSidebarDataGroup.ts
- packages/theme-default/src/logic/utils.ts
We currently have two matching algorithms for sidebar
```ts
{
'/': [],
'/guide': [
{
text: 'Getting Started',
link: '/guide/getting-started',
},
],
},
```
decide which **sidebarGroup** would show, and it will calculate with these keys `'/'`, `'/guide'` one by one
https://github.com/web-infra-dev/rspress/blob/fb81b996c5630b826ee6f5df7e1a6920d9d48e52/packages/theme-default/src/logic/getSidebarDataGroup.ts#L22-L42
decide which **sidebarItem** is active,
to match `item.link` recursively
```ts
{
text: 'Getting Started',
link: '/guide/getting-started',
},
```
1. unify all `pathname -> routePath` logic to `pathnameToRouteService`
it is a core function which bridge `Route` and `Sidebar`
2. use `pathnameToRouteService` to decide which sidebar is active
In rspress, we calculating it repeatedly
This …
> refactor(theme): `Sidebar` isActive algorithm should be same with `Route` match

- package.json
- packages/core/src/node/runtimeModule/siteData/extractPageData.test.ts
- packages/core/src/node/runtimeModule/siteData/extractPageData.ts
- pnpm-lock.yaml
- scripts/test-helper/vitest.setup.ts
- vitest.workspace.ts
a mistake in https://github.com/web-infra-dev/rspress/pull/1867
`encodedHtml` should be `<code>${encodedHtml}</code>`
https://github.com/web-infra-dev/rspress/pull/1867
> fix(search): for #1867, search codeBlock: false should work

- packages/plugin-client-redirects/rslib.config.ts
- packages/plugin-playground/rslib.config.ts
fix rsbuild eco-ci problem:
https://lib.rsbuild.dev/config/lib/shims#shimsesm__dirname
https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/13469849196/job/37642002320
> fix: shim `_dirname` in esm output

- packages/cli/package.json
- packages/core/package.json
- packages/create-rspress/package.json
- packages/modern-plugin-rspress/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-auto-nav-sidebar/package.json
- packages/plugin-client-redirects/package.json
- packages/plugin-container-syntax/package.json
- packages/plugin-last-updated/package.json
- packages/plugin-medium-zoom/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/plugin-preview/rslib.config.ts
- packages/plugin-rss/package.json
- packages/plugin-shiki/package.json
- packages/plugin-typedoc/package.json
- packages/runtime/package.json
- packages/shared/package.json
- packages/shared/rslib.config.ts
- packages/theme-default/package.json
- pnpm-lock.yaml
Rslib v0.5.2 support bundle DTS of multiple entries
https://github.com/web-infra-dev/rslib/releases/tag/v0.5.2
> chore(deps): bump Rslib v0.5.2 and modify some build configurations

- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Currently the `searchIndex.add` is quite slow and will block the main thread.
This PR uses `addAsync` to replace `add` to avoid blocking the main thread.
- before:
- after:
- https://github.com/nextapps-de/flexsearch?tab=readme-ov-file#api-overview
- https://github.com/nextapps-de/flexsearch/blob/5bcbc72dac5118c049aac040a7621d5677c7e0d6/index.d.ts#L388
> perf(search): add index async to avoid blocking the main thread

- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/logic/search.ts
- packages/theme-default/src/components/Search/logic/types.ts
- packages/theme-default/src/components/Search/logic/util.ts
- packages/theme-default/src/logic/useFullTextSearch.ts
The `getSidebarDataGroup` can be very slow when there are thousands of routes.
This PR removed the group calculation and use `item.title` to group the search results.
In the future, the sorting of search results should be better implemented (for example, according to some weight indicators we agree on, such as title > content > code).
Performance regression since https://github.com/web-infra-dev/rspress/pull/1863
> perf(search): remove group calculation

- packages/runtime/src/index.ts
- packages/runtime/src/route.ts
- packages/theme-default/src/components/Overview/index.tsx
- packages/theme-default/src/components/Sidebar/index.tsx
- packages/theme-default/src/logic/getSidebarDataGroup.test.ts
- packages/theme-default/src/logic/getSidebarDataGroup.ts
- packages/theme-default/src/logic/usePrevNextPage.ts
- packages/theme-default/src/logic/useSidebarData.ts
1. remove group.title, related to https://github.com/web-infra-dev/rspress/pull/1893
2. perf: use `matchPath` rather than `matchRoutes`, these apis come from `react-router-dom`
in Sidebar active, matchPath is more suitable O(n2) -> O(n)
> perf: use `matchPath` rather than `matchRoutes`, remove unused group.title

- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/logic/Provider.ts
- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
- packages/theme-default/src/components/Search/logic/providers/RemoteProvider.ts
- packages/theme-default/src/components/Search/logic/search.ts
- scripts/dictionary.txt
For large sites, initializing the search while the page is idle may cause the page to render slowly.
To address this issue, this PR splits search init into two steps: prefetch and init:
- prefetch the search index when the page is idle
- init the search when the search bar is focused.
> perf(search): improve initialization and prefetching logic

- packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
We should use `index.searchAsync` as it doesn't make sense to use `Promise.all` to run sync methods.
> fix(search): should use `index.searchAsync`

- packages/document/docs/en/api/client-api/api-runtime.mdx
- packages/document/docs/zh/api/client-api/api-runtime.mdx
Adding type information for several hooks and providing additional details on using the `useDark` hook during the SSG process.
> docs: enhance runtime API with types and dark mode usages

- packages/theme-default/src/components/Nav/NavMenuGroup.tsx
Add a delay to the dropdown menu closing behavior to improve user experience when moving the cursor diagonally. This prevents the menu from closing immediately when the cursor briefly leaves the button area while moving towards the dropdown content, making the navigation more smooth and user-friendly.
> feat(nav): improve dropdown menu interaction

- e2e/tests/hide-nav-bar.test.ts
- packages/theme-default/src/components/LocalSideBar/index.scss
- packages/theme-default/src/components/LocalSideBar/index.tsx
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/components/NavHamburger/index.tsx
- packages/theme-default/src/components/Sidebar/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.tsx
- packages/theme-default/src/layout/Layout/index.tsx
- packages/theme-default/src/logic/utils.ts
> fix: display outline correctly on >=960px <=1280px screen width

- packages/modern-plugin-rspress/package.json
- packages/plugin-algolia/package.json
- pnpm-lock.yaml
Correct the peer dependency version of `plugin-algolia`.
Fix rsbuild-ecosystem-ci: https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/13745538869/job/38439970095
> chore(plugin-algolia): correct peer dependency version

- packages/theme-default/src/components/HomeHero/index.tsx
Remove outdated hero default values. If the title or tagline in the hero is empty, the corresponding elements should not be rendered.
Fix:
> fix: remove outdated hero default values

- e2e/tests/hide-nav-bar.test.ts
- packages/theme-default/src/components/LocalSideBar/index.scss
- packages/theme-default/src/components/LocalSideBar/index.tsx
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/components/NavHamburger/index.tsx
- packages/theme-default/src/components/Sidebar/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.module.scss
- packages/theme-default/src/layout/DocLayout/index.tsx
- packages/theme-default/src/layout/Layout/index.tsx
- packages/theme-default/src/logic/utils.ts
introduced in https://github.com/web-infra-dev/rspress/issues/1914
1. fix wrong style in mobile style
2. fix Overview Page style
3. fix overflow when first screen entered is large size
> fix: Revert "fix: display outline correctly on >=960px <=1280px screen width (#1914)"

- packages/core/src/node/runtimeModule/globalStyles.ts
Occasionally rspack website does not bundle the global-style file during deployment.
> fix: remove async fs to avoid empty global style

- packages/cli/src/index.ts
Should catch build errors when running the `build()` method.
> fix(cli): should catch build errors

- packages/theme-default/src/components/Sidebar/index.tsx
unset overflow style when sidebar destroy
close https://github.com/web-infra-dev/rspress/issues/1828
> fix(theme): unset overflow style when sidebar destroy

- e2e/fixtures/search-algolia/doc/index.mdx
- e2e/fixtures/search-algolia/package.json
- e2e/fixtures/search-algolia/rspress.config.ts
- e2e/fixtures/search-algolia/theme/index.tsx
- e2e/fixtures/search-algolia/tsconfig.json
- e2e/tests/search-algolia.test.ts
- e2e/utils/search.ts
- packages/document/docs/en/plugin/official-plugins/_meta.json
- packages/document/docs/en/plugin/official-plugins/algolia.mdx
- packages/document/docs/zh/plugin/official-plugins/_meta.json
- packages/document/docs/zh/plugin/official-plugins/algolia.mdx
- packages/document/rspress.config.ts
- packages/document/theme/index.tsx
- packages/plugin-algolia/package.json
- packages/plugin-algolia/rslib.config.ts
- packages/plugin-algolia/src/index.ts
- packages/plugin-algolia/src/runtime/Search.css
- packages/plugin-algolia/src/runtime/Search.tsx
- packages/plugin-algolia/src/runtime/index.ts
- packages/plugin-algolia/src/runtime/locales.ts
- packages/runtime/src/index.ts
- packages/theme-default/src/components/Search/SearchButton.tsx
- packages/theme-default/src/components/Search/SearchPanel.tsx
- packages/theme-default/src/components/Search/index.tsx
- packages/theme-default/src/components/SwitchAppearance/index.tsx
- packages/theme-default/src/index.ts
- playwright.config.ts
- pnpm-lock.yaml
- scripts/dictionary.txt
Based on [docsearch](https://docsearch.algolia.com), this plugin replaces Rspress's built-in search with [algolia](https://www.algolia.com/).
npm add @rspress/plugin-algolia -D
First, add the following configuration to your config file:
```ts
// rspress.config.ts
import path from 'path';
import { defineConfig } from 'rspress';
import { pluginAlgolia } from '@rspress/plugin-algolia';
export default defineConfig({
plugins: [pluginAlgolia()],
search: false, // Disable the default search index generation
});
```
Then override the `Search` component with an algolia-supported search box via [Custom Theme](/guide/advanced/custom-theme).
```tsx
// theme/index.tsx
import { Search as PluginAlgoliaSearch } from '@rspress/plugin-algolia/runtime';
const Search = () => {
return (
<PluginAlgoliaSearch …
```
> feat(plugin-algolia): add plugin-algolia and optimize some DX on customizing Search

- packages/core/rslib.config.ts
fix
```json
{
"name": "react-helmet-async",
"version": "2.0.5",
"description": "Thread-safe Helmet for React 16+ and friends",
"sideEffects": false,
"main": "./lib/index.js",
"module": "./lib/index.esm.js",
"typings": "./lib/index.d.ts",
}
```
"./lib/index.esm.js" does not end with 'mjs' extension so that "main" field is used, there is a problem in interop process
> fix(deps): update react-helmet-async 2.0.0

- e2e/fixtures/search-code-blocks/rspress.config.ts
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
We added `search.codeBlocks` option in https://github.com/web-infra-dev/rspress/pull/1797.
After a period of trial, this feature has been proven to be stable and has brought better search results. So this PR enables `search.codeBlocks` by default.
> feat: enable `search.codeBlocks` by default

- packages/document/i18n.json
- packages/document/rspress.config.ts
- Update i18n messages to use `Rstack` instead of `Tool Stack`
- Remove `enableContentAnimation: true` config as switching from the API overview page to other pages will cause a horizontal shift effect.
> docs: update i18n messages

- packages/plugin-algolia/src/runtime/Search.css
- packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/components/Nav/index.tsx
> fix(style): unset the navItem bg color

- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
Add configuration for `editLink` and `outline` to the doc based on the type definition.
BTW, `docFooter` is not documented and does not seem to be used.
https://github.com/web-infra-dev/rspress/blob/a9cdd91364ba44a80b149f09a862b9ac34e70d75/packages/shared/src/types/defaultTheme.ts
> docs: add `editLink` and `outline` config

- packages/core/package.json
- packages/core/src/node/mdx/options.ts
- packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
- packages/core/tests/__snapshots__/md.test.ts.snap
- packages/core/tests/md.test.ts
- packages/shared/src/node-utils/getNodeAttribute.ts
- pnpm-lock.yaml
Sorry this is a critical regression introduced by #1877, it's weird that TS didn't complain about `Object.assign(string, ...)`
cc @Timeless0911 @chenjiahan
> fix: normalize jsx img src attribute correctly

- packages/document/docs/en/api/commands.mdx
- packages/document/docs/zh/api/commands.mdx
> docs: format command bash space

- e2e/fixtures/ssg-fail-strict/rspress.config.ts
- packages/core/src/node/build.ts
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/index.ts
Rspress now requires ssg to be successful
It means rspress would emit error if ssg generation fails. The process will be directly terminated, rather than fallback to the csr products
Remove `ssg.strict` and add `ssg.fallback` in Rspress v2, see https://github.com/web-infra-dev/rspress/discussions/1105#discussioncomment-10324815
https://github.com/web-infra-dev/rspress/issues/1317
> feat(config)!: force successful SSG generation,  remove `ssg.strict` and add `ssg.fallback`

- packages/plugin-playground/static/global-components/Playground.tsx
目前 monaco-editor 还不能很好支持 tsx，相关 issue：https://github.com/microsoft/monaco-editor/issues/264  
可以临时禁用 monaco-editor 对 ts 的校验保持语法高亮并不报错。
https://github.com/web-infra-dev/rspress/issues/1324
> fix(plugin-playground): disable monaco editor ts check for supporting tsx

- packages/core/src/runtime/App.tsx
- packages/core/src/runtime/ClientApp.tsx
- packages/core/src/runtime/clientEntry.tsx
- packages/core/src/runtime/initPageData.ts
- packages/core/src/runtime/ssrEntry.tsx
- packages/theme-default/src/logic/useUISwitch.ts
https://github.com/facebook/react/tree/main/packages/react-refresh
https://biomejs.dev/linter/rules/use-component-export-only-modules/
This is the prerequisite task for implementing the virtual module hmr, which allows the client here to be a React component that conforms to the react-refresh specification.
Or it won't trigger react-refresh
> refactor(hmr): root component should be hmr friendly

- packages/plugin-container-syntax/src/remarkPlugin.ts
- packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
- packages/plugin-container-syntax/tests/index.test.ts
Fixed an issue where the space after the link might be lost in the container syntax.
Found on Rsbuild documentation:
https://rsbuild.dev/guide/basic/css-usage#lightning-css
> fix(plugin-container): incorrect trimming in some cases

- packages/plugin-shiki/shiki.css
Improve line diff colors for `plugin-shiki` by reducing the transparency of the background.
- before:
- after:
> feat(plugin-shiki): improve line diff colors

- packages/theme-default/src/logic/useUISwitch.ts
removed feature: scrollRestoration after reloading
> fix(firefox): location too much change firefox issue

- packages/plugin-container-syntax/src/remarkPlugin.ts
- packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
- packages/plugin-container-syntax/tests/index.test.ts
Fix unexpected line breaks when using the container syntax with mdx-js.
- Input:
```md
:::tip
Line 1.
Line 2 with [link](http://example.com).
:::
```
- Current output:
- Expected output:
> fix(plugin-container): avoid unexpected line breaks

- e2e/fixtures/plugin-shiki/doc/index.mdx
- e2e/tests/plugin-shiki.test.ts
- packages/document/package.json
- packages/document/rspress.config.ts
- packages/plugin-shiki/src/shiki/pluginShiki.ts
- packages/plugin-shiki/src/shiki/transformers/add-title.ts
- packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
- pnpm-lock.yaml
introduced in https://github.com/web-infra-dev/rspress/pull/2046
should add it back
> fix(plugin-shiki): no code title

- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/src/runtime/ClientApp.tsx
- packages/core/src/runtime/clientEntry.tsx
in https://github.com/web-infra-dev/rspress/pull/2033, introduced a `useEffect` hook to get initialData (after rendering)
```ts
useEffect(() => {
initPageData(window.location.pathname).then(pageData => {
setData(pageData);
});
}, []);
```
1. beforeHydration, `initialData: null`
2. afterHydration, render the html
3. useEffect, get initialData and render the html again
so we get two html in the same page
1. beforeHydration, `initialData: {...}`
2. afterHydration, render the html, hydrate successfully
> fix: wrong hydration, hydrate twice

- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/guide/basic/custom-page.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/guide/basic/custom-page.mdx
Correct the meta tags generation examples. We should use the `head` front matter to generate meta tags instead of using `title` and `description`.
> docs: correct meta tags generation example

- packages/plugin-preview/static/global-components/Container.tsx
Issue from https://github.com/web-infra-dev/rspress/pull/1990.
Change className `flex` to `rp-flex`.
none
> fix(style): change flex to rp-flex

- packages/document/docs/en/_meta.json
i18n.json is used in runtime side, so I consider removed the feature of replaceing the text in _meta.json
> fix: the nav bar lowerCase

- packages/document/docs/en/_meta.json
- packages/document/docs/zh/_meta.json
Add Rspress v2 website link to v1 website.
> docs: add v2 website link to v1 website

- packages/plugin-llms/src/plugin.ts
When `config.themeConfig.locales` is not configured, `plugin-llms` will group every route under `others` instead of grouping them using root navigation. This PR fixes this behaviour by using `config.themeConfig.sidebar` & `config.themeConfig.nav` when no locales are configured.
<details>
<summary>llms.txt before</summary>
```md
> Rsbuild based static site generator
- [Built-in components](/api/client-api/api-components.md)
- [Runtime API](/api/client-api/api-runtime.md)
- [Commands](/api/commands.md)
- [Basic config](/api/config/config-basic.md)
- [Build config](/api/config/config-build.md)
- [Front matter config](/api/config/config-frontmatter.md)
- [Theme config](/api/config/config-theme.md)
- [API Overview](/api/index.md)
- [Customize search functions](/guide/advanced/custom-search.md) …
```
> fix(plugin-llms): group routes correctly without locales config

- packages/theme-default/src/components/Aside/index.tsx
- packages/theme-default/src/components/Aside/useDynamicToc.ts
1. fix the edge case, should abandon all elements with `display: none`
2. always set baseLevel = 2
before
after
> fix(theme/dynamic-toc): should abandon all elements with `display: none`.

- e2e/tests/custom-headers.test.ts
- e2e/tests/title-suffix.test.ts
- packages/core/package.json
- packages/core/src/node/constants.ts
- packages/core/src/node/ssg/renderPages.ts
- packages/core/src/runtime/App.tsx
- packages/core/src/runtime/ClientApp.tsx
- packages/core/src/runtime/ssrServerEntry.tsx
- packages/plugin-rss/static/global-components/FeedsAnnotations.tsx
- packages/runtime/package.json
- packages/runtime/src/index.ts
- packages/theme-default/package.json
- packages/theme-default/src/layout/Layout/index.tsx
- pnpm-lock.yaml
- scripts/dictionary.txt
`index.esm.js` should be `index.mjs`, we need a better react-helmet package.
https://x.com/sebastienlorber/status/1918228101743493423?s=12&t=Ffc3Msu3HnW1tEsd7H6XfQ
https://github.com/web-infra-dev/rspress/issues/2111
react-helmet-async -> @dr.pogodin/react-helmet -> @unhead/react@2.0.0 
https://unhead.unjs.io/
> chore(deps): migrate react-helmet to @unhead/react@2.0.0

- packages/core/package.json
- packages/core/rslib.config.ts
- packages/plugin-algolia/rslib.config.ts
- packages/runtime/rslib.config.ts
- packages/theme-default/.theme-entry.d.ts
- packages/theme-default/.theme-entry.js
- pnpm-lock.yaml
fix: the pkg type error in moduleResolution: node16
1. @types/unist Phantom dependency
2. node16 moduleResolution
https://lib.rsbuild.dev/config/lib/redirect#redirectdtsextension
```ts
redirect: {
dts: {
extension: true
}
}
```
close #2114
> fix: the pkg type error in moduleResolution: node16

- packages/document/docs/en/api/config/config-theme.mdx
- packages/document/docs/zh/api/config/config-theme.mdx
- packages/shared/src/types/defaultTheme.ts
- packages/theme-default/src/logic/useRedirect4FirstVisit.ts
If you set it to `only-default-lang`, the user will only be redirected when visiting the default locale.
> feat: add `localeRedirect: 'only-default-lang'` support

- packages/create-rspress/template-basic/package.json
- packages/document/theme/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/CodeButtonGroup.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/CopyCodeButton.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
`npm create rspress@beta`
before
after
> feat: upgrade create-rspress to support `npm create rspress@beta`

- .gitignore
- .prettierignore
- .vscode/settings.json
- biome.json
- packages/cli/package.json
- packages/cli/scripts/generateJsonSchema.mjs
- packages/plugin-auto-nav-sidebar/src/type.ts
- packages/plugin-auto-nav-sidebar/src/walk.ts
- pnpm-lock.yaml
1. <s>rename top level _meta.json => nav.json</s>
2. add _meta.json json schema type hint
> feat: add `_meta.json` json schema in `rspress/meta-json-schema.json`

- packages/theme-default/src/components/Aside/processTitleElement.ts
1. remove .header-anchor
2. skip ".rspress-toc-exclude" element
3. skip <a/ > element, replace a elements with their children
> feat(theme/dynamic-toc): add .rspress-toc-exclude escape hatch

- packages/core/package.json
- packages/core/src/node/initRsbuild.ts
- packages/theme-default/package.json
- pnpm-lock.yaml
Remove the unused `react-syntax-highlighter` dependency, now Rspress uses Shiki by default, see: https://github.com/web-infra-dev/rspress/pull/2122
> fix(deps): remove unused react-syntax-highlighter

- e2e/tests/plugin-api-docgen.test.ts
- packages/plugin-api-docgen/package.json
- packages/plugin-api-docgen/static/global-components/API.tsx
- pnpm-lock.yaml
should have anchor, but still no toc now in V1
Toc is implemented in rspress 2.0
https://github.com/web-infra-dev/rspress/issues/1320
> fix(plugin-api-doc-gen): plugin-api-doc-gen  should have anchor

- packages/document/rspress.config.ts
- packages/plugin-shiki/src/shiki/pluginShiki.ts
https://github.com/SoonIter/shiki/blob/f649d11c14aa31e4487a87e2cb0b547ce4f00d04/packages/rehype/src/index.ts#L30
drop the default value of langs in plugin-shiki, so langs option can be needless
> chore(plugin-shiki): add all builtin-langs in shiki

- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/en/fragments/builtin-components.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/document/docs/zh/fragments/builtin-components.mdx
updated the docs to include the change in builtin components from `Helmet` to `Head` 
n/a
> docs: replace `Helmet` with `Head`

- e2e/tests/package-manager-tabs.test.ts
- packages/theme-default/src/components/PackageManagerTabs/index.tsx
> in Rspress v2 we enable shiki by default to highlight languages in compile process, and code blocks in dynamic components can not be highlighted yet. We plan to provide a `<CodeBlockRuntime />` component to resolve this issue, tracking in https://github.com/web-infra-dev/rspress/issues/2126.
`<CodeBlockRuntime />` means that we imports the whole shiki in runtime, but the cost is indeed too high.
So we parse it in runtime manually to support shiki highlight
before
after
> fix(theme): highlight the <PackageManagerTabs /> manually

- packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
add `.rspress-sidebar-item-active` and `.rspress-nav-menu-item-active` for algolia crawler
> feat(theme): expose classname for crawler

- packages/document/theme/index.tsx
- packages/theme-default/src/components/PackageManagerTabs/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/index.tsx
- packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
chore: rename Pre -> PreWithCodeButtonGroup, the only element that differs from the original element
> chore(theme): rename Pre -> PreWithCodeButtonGroup, the only element that differs from the original element

- packages/theme-default/src/index.ts
- packages/theme-default/src/layout/DocLayout/docComponents/index.tsx
chore: export `CodeProps` to use `getCustomMDXComponent()` on the top
> chore(theme): export type `CodeProps` to use `getCustomMDXComponent()`

- packages/document/i18n.json
- packages/document/package.json
- packages/document/theme/components/ToolStack.tsx
- pnpm-lock.yaml
- Update @rstack-dev/doc-ui to 1.10.0 to add Rstest to homepage.
- This update also includes some UI and text improvements.
Related: https://github.com/rspack-contrib/rstack-doc-ui/releases
> docs: add Rstest to homepage

- e2e/fixtures/icon-file-url/docs/index.md
- e2e/fixtures/icon-file-url/package.json
- e2e/fixtures/icon-file-url/rspress.config.ts
- e2e/fixtures/icon-file-url/tsconfig.json
- e2e/tests/icon-file-url.test.ts
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/en/guide/basic/static-assets.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/docs/zh/guide/basic/static-assets.mdx
- packages/plugin-rss/src/plugin-rss.ts
- packages/shared/src/node-utils.ts
- packages/shared/src/node-utils/getIconUrlPath.ts
- packages/shared/src/types/index.ts
- pnpm-lock.yaml
So that the user can use lcoal absolute path or `data:` url as they whatever want
> feat: support `file://` protocol and `URL` for icon

- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/utils/detectReactVersion.ts
- packages/core/src/runtime/csrClientEntry.tsx
- packages/core/src/runtime/ssrClientEntry.tsx
- packages/runtime/src/Content.tsx
This PR removes React 17 compatibility code from Rspress.
Rspress 2.0 uses React 19 by default, and the minimum supported React version is 18, which means React 17 will no longer be supported.
- https://github.com/web-infra-dev/rspress/discussions/1891#discussioncomment-12475395
> perf: remove React 17 compatibility code

- .changeset/open-zebras-report.md
- e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
- e2e/tests/auto-nav-sidebar-dir-convension.test.ts
- e2e/tests/auto-nav-sidebar.test.ts
- e2e/tests/i18n.test.ts
- e2e/utils/getSideBar.ts
- packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
- packages/theme-default/src/components/Sidebar/index.tsx
The `div.rspress-sidebar-item` and the final `Link` component were initially implemented separately, causing certain cases to be overlooked, as shown in the test cases. Here's what I've done to address this issue:
1. Unified the implementation of `div.rspress-sidebar-item` and `Link` components to prevent any oversights.
2. Updated some test cases due to changes in the sidebar DOM structure.
3. Added test cases that correspond to the reproduced issue.
[issue:#2202](https://github.com/web-infra-dev/rspress/issues/2202)
> fix: sidebar type=file with data-context

- packages/plugin-shiki/src/shiki.scss
> fix(plugin-shiki/style): for force wrap style

- packages/theme-default/src/components/CodeBlockRuntime/index.tsx
`onRendered` prop for scroll operation
Lynx website: 
scroll to first highlight line on rendered
https://github.com/lynx-family/lynx-website/pull/189
> feat(CodeBlockRuntime): add onRendered prop

- packages/theme-default/src/components/Aside/useDynamicToc.ts
exclude `.rspress-toc-exclude` ancestor nodes in dynamic TOC
related #2136
> fix: exclude `.rspress-toc-exclude` ancestor nodes in dynamic TOC

- .changeset/better-eels-tap.md
- packages/plugin-container-syntax/src/remarkPlugin.ts
- packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
- packages/plugin-container-syntax/tests/index.test.ts
Fixing the bug #2220 by adding undefined protection to a part of logic in **plugin-container-syntax**.
#2220
> fix: empty blockquote crash the compiler

- packages/theme-default/index-barrel.js
- packages/theme-default/package.json
- packages/theme-default/rslib.config.ts
- packages/theme-default/src/index.ts
fix(infra): bundle size regression after migrating to bundleless dist
#2216
> fix(infra): bundle size regression after migrating to bundleless dist

- e2e/tests/inline-markdown.test.ts
- packages/theme-default/package.json
- packages/theme-default/src/components/Aside/index.tsx
- packages/theme-default/src/components/Button/index.tsx
- packages/theme-default/src/components/HomeFeature/index.tsx
- packages/theme-default/src/components/HomeHero/index.tsx
- packages/theme-default/src/components/Overview/index.tsx
- packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
- packages/theme-default/src/components/Sidebar/SidebarItem.tsx
- packages/theme-default/src/components/Sidebar/SidebarSectionHeader.tsx
- packages/theme-default/src/components/Toc/index.tsx
- packages/theme-default/src/env.d.ts
- packages/theme-default/src/index.ts
- packages/theme-default/src/logic/utils.tsx
- pnpm-lock.yaml
remove htmr dep
close https://github.com/web-infra-dev/rspress/issues/2232
> chore(deps): remove htmr dep and migrate htmr to `dangerouslySetInnerHTML`

- packages/theme-default/src/components/Tabs/index.module.scss
CSS should rely on selector priority rather than import order.
before
after
> fix(theme/style): Tabs wrong margin

- packages/core/rslib.config.ts
- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/mdx/options.ts
- packages/core/src/node/mdx/processor.ts
- packages/core/src/node/mdx/remarkPlugins/toc.ts
- packages/core/src/node/mdx/types.ts
- packages/shared/src/types/index.ts
Reduce 13% time
before
after
https://github.com/facebook/docusaurus/blob/45065e8d2b5831117b8d69fec1be28f5520cf105/packages/docusaurus-mdx-loader/src/createMDXLoader.ts#L36
> feat(mdx): add `markdown.crossCompilerCache` for speed up build process

- .changeset/vast-words-enter.md
- packages/core/src/node/ssg/renderPages.ts
MF will replace the original entry with async entry like below: 
```js
// original entry - ssrEntry.js
export {reder,routes};
// after access mf - bootstrap.js
const entry = import('ssrEntry.js');
const render = entry.then({render}=> (render));
const routes = entry.then({routes}=> (routes));
export {render, router}
```
And the ssrExport.render will be Promise.resolve(render), so need to add `await`
> feat: support async entry

- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/runtimeModule/index.ts
- packages/shared/src/types/Plugin.ts
refactor(virtual-module): migrate rspress plugin.addRuntimeModules to rsbuild-plugin-virtual-module
> refactor(virtual-module): migrate rspress plugin.addRuntimeModules to rsbuild-plugin-virtual-module

- packages/core/package.json
incorrect types for `shiki-transformers` entry
> fix: incorrect types for `shiki-transformers` entry

- e2e/fixtures/custom-headers/doc/index.mdx
- e2e/fixtures/custom-headers/index.test.ts
- packages/core/src/node/ssg/renderHead.ts
- packages/core/src/node/ssg/renderPages.ts
- packages/document/docs/en/api/config/config-frontmatter.mdx
- packages/document/docs/zh/api/config/config-frontmatter.mdx
- packages/theme-default/src/layout/Layout/index.tsx
refactor: frontmatter.head should be rendered by @unhead/react
1. perf: rerender of \<Head  />
before
after
2. `frontmatter.head` can be rendered in dev not only in build
> refactor: frontmatter.head should be rendered by @unhead/react

- packages/cli/package.json
- packages/core/package.json
- packages/core/src/node/initRsbuild.ts
- packages/plugin-llms/package.json
- packages/plugin-preview/package.json
- packages/plugin-preview/src/index.ts
- packages/shared/package.json
- pnpm-lock.yaml
- Update @rsbuild/core to 1.4.0-rc.0
- Remove `dev.progressBar: false`, now defaults to `false`.
- Simplify `dev.setupMiddlewares` usage, see https://rsbuild.rs/config/dev/setup-middlewares#devsetupmiddlewares
- https://github.com/web-infra-dev/rsbuild/releases/tag/v1.4.0-rc.0
close https://github.com/web-infra-dev/rspress/pull/2286
> chore(deps): update @rsbuild/core to 1.4.0-rc.0

- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/mdx/processor.ts
- packages/core/src/node/ssg/rsbuildPluginSSG.ts
If an error has already been generated during the compile-time process, we will not execute ssg rendering. 
This will cause the error stack to appear during compilation, rather than in the process of ssg.
close https://github.com/web-infra-dev/rspress/issues/2316
close #2329
> fix(ssg): better format of mdx compile time error in SSG

- packages/theme-default/src/components/Aside/processTitleElement.ts
This bug will only reappear during `build && preview` with ssg and hydration
> fix(theme/dynamic-toc): remove comment for props replacing in SSG

- packages/cli/src/config/loadConfigFile.ts
- packages/cli/src/index.ts
- packages/cli/tests/config/config-basic.test.ts
- packages/core/src/node/PluginDriver.ts
- packages/core/src/node/build.ts
- packages/core/src/node/dev.ts
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/route/RouteService.test.ts
- packages/core/src/node/serve.ts
feat(rsbuild)!: enable persistent cache defaultly via `performance.buildCache` push
> feat(rsbuild)!: enable persistent cache by default via `performance.buildCache`

- e2e/fixtures/plugin-typedoc/index.test.ts
- e2e/fixtures/plugin-typedoc/multi/rspress.config.ts
- e2e/fixtures/plugin-typedoc/multi/src/raw-link.ts
- packages/plugin-typedoc/src/patch.ts
`@rspress/plugin-typedoc` replacing raw external links like `https://exmaple.com` with `./https://example.com`, this pull request fixes to keep no change when raw link detected.
--
> fix(plugin-typedoc): skip patch raw links

- packages/document/docs/en/fragments/builtin-components.mdx
Documentation:
- Mention pnpm alongside yarn and bun for special install→add processing in PackageManagerTabs.
Follow up #2364.
I forgot to update document.
> docs: update PackageManagerTabs tips for pnpm

- e2e/fixtures/dynamic-toc/index.test.ts
Tests:
- Apply ‘!’ operator to textContent access in dynamic-toc tests to satisfy non-null assertions
Follow up #2363
> test: add missing non-null assertion to dynamic-toc test

- packages/theme-default/src/components/HomeFeature/index.tsx
- packages/theme-default/src/components/HomeHero/index.tsx
This PR fixes an issue where links on the landing page don't include the the basepath (set with `base` option in config). 
`routePath` passed to `HomeHero` & `HomeFeature` components never includes the base so using `withBase` from `@rspress/shared` instead of `@rspress/runtime` will cause the base to be skipped. 
n/a
> fix: use `withBase` from runtime

- packages/cli/src/index.ts
- packages/core/src/node/initRsbuild.ts
fix: other configuration except rspress.config.ts should be added to persistent cache deps
> fix(buildCache): other configuration files besides `rspress.config.ts` should be added to persistent cache deps

- packages/core/package.json
- packages/core/rslib.config.ts
- packages/core/src/node/build.ts
- packages/core/src/node/initRsbuild.ts
- packages/core/src/node/runtimeModule/runtimeConfig.ts
- packages/core/src/node/runtimeModule/siteData/index.ts
- packages/core/src/node/ssg/renderHtmlTemplate.ts
- packages/core/src/node/ssg/renderPage.ts
- packages/core/src/node/ssg/renderPageWorker.ts
- packages/core/src/node/ssg/renderPages.ts
- packages/core/src/node/ssg/rsbuildPluginCSR.ts
- packages/core/src/node/ssg/rsbuildPluginSSG.ts
- packages/core/src/runtime/env.d.ts
- packages/core/src/runtime/ssrServerEntry.tsx
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/index.ts
- pnpm-lock.yaml
- Type: `boolean | { experimentalWorker?: boolean; experimentalLoose?: boolean; }`
- Default: `true`
Whether to enable static site generation. Rspress enable it by default to generate CSR outputs and SSG outputs.
If your document site is only required to be used in CSR scenarios, you can set `ssg` to `false`, and Rspress will only generate CSR outputs.
```ts title="rspress.config.ts"
import { defineConfig } from '@rspress/core';
export default defineConfig({
ssg: false,
});
```
- Type: `boolean`
- Default: `false`
After enabled, you can use Worker to speed up the SSG process. It is suitable for large document sites and is based on [tinypool](https://github.com/tinylibs/tinypool).
- Type: `boolean`
- Default: `false`
After enabled, some errors in the SSG process will be ignored and other …
> perf(ssg): add `ssg.experimentalWorker` based on tinypool to speed up ssg process

- packages/core/src/node/runtimeModule/runtimeConfig.ts
- packages/core/src/node/ssg/renderPages.ts
- packages/core/src/node/ssg/ssgEnv.ts
- packages/core/src/runtime/ssrServerEntry.tsx
- packages/document/docs/en/api/config/config-basic.mdx
- packages/document/docs/zh/api/config/config-basic.mdx
- packages/document/rspress.config.ts
- packages/shared/src/types/defaultTheme.ts
- packages/shared/src/types/index.ts
feat(ssg): add `ssg.experimentalExcludeRoutePaths`
- Type: `(string | RegExp)[]`
- Default: `[]`
After enabled, some pages will not be rendered by SSG, and they will directly use html under CSR. This is suitable for SSG errors in large document sites bypassing a small number of pages. It is not recommended to enable this option actively.
> feat(ssg): add `ssg.experimentalExcludeRoutePaths`

- packages/core/package.json
- packages/core/src/node/runtimeModule/siteData/index.ts
- pnpm-lock.yaml
remove types reference of plugin-preview to fix tsc circular issue.
> chore: remove types reference to fix tsc circular issue

- packages/core/src/node/mdx/loader.ts
- packages/core/src/node/mdx/options.ts
- packages/core/src/node/mdx/processor.ts
- packages/core/src/node/mdx/remarkPlugins/fileCodeBlock.ts
fix(fileCodeBlock): should support hmr
> fix(fileCodeBlock): should support hmr

- packages/theme-default/src/components/Tabs/index.module.scss
Disabled vertical scrolling on the tabs to fix a bug where they would try to scroll vertically when there's nothing to scroll
To reproduce:
- Navigate to https://rspress.rs/guide/default-theme/components#tabtabs
- Hover the mouse over one of the tab links like the blue "Tab 1"
- Scroll down with the mouse wheel
- Current behavior: nothing happens
- New behavior: page scrolls down
This bug is caused by the `margin-bottom: -1px;` on the `tab` style which causes them to overflow their container. Setting the vertical scroll on `tab-list` to `hidden` fixes it
> fix(tab-list): Fix tabs scrolling when not overflowing

- .github/workflows/release.yml
- packages/cli/package.json
- packages/core/package.json
- packages/create-rspress/package.json
- packages/document/package.json
- packages/modern-plugin-rspress/package.json
- packages/plugin-api-docgen/package.json
- packages/plugin-auto-nav-sidebar/package.json
- packages/plugin-client-redirects/package.json
- packages/plugin-container-syntax/package.json
- packages/plugin-last-updated/package.json
- packages/plugin-medium-zoom/package.json
- packages/plugin-playground/package.json
- packages/plugin-preview/package.json
- packages/plugin-rss/package.json
- packages/plugin-shiki/package.json
- packages/plugin-typedoc/package.json
- packages/runtime/package.json
- packages/shared/package.json
- packages/theme-default/package.json
Enable OIDC publishing to make it easier and more secure to publish npm packages from CI.
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
- https://docs.npmjs.com/trusted-publishers
> chore: enable trusted publishing for npm packages

- README.md
- scripts/dictionary.txt
- Add version badges to the Rstack tools table, this should help users understand the current status and latest version number of each project.
- Add Rslint to the list of Rstack tools: https://github.com/web-infra-dev/rslint
> docs: add Rslint and version badges to Rstack tools table

- packages/core/src/node/initRsbuild.ts
chore(core): add runtime alias by default for multi-instance problem in monorepo
> chore(core): add runtime alias by default for multi-instance problem in monorepo

- packages/runtime/src/index.ts
export `usePage` to replace deprecated `usePageData`
> fix: export `usePage` to replace deprecated `usePageData`

- packages/theme-default/src/styles/base.css
- packages/theme-default/src/styles/index.ts
- packages/theme-default/src/styles/tailwind.css
This is a breaking change for compatibility 
https://caniuse.com/?search=%40layer
https://github.com/web-infra-dev/rspress/pull/2160
https://github.com/vuejs/vitepress/issues/4904
> feat(theme)!: add layer for base.css to support tailwind v4

- packages/theme-default/src/components/PackageManagerTabs/index.tsx
This pull request makes a small adjustment to the logic for handling package manager commands in the `PackageManagerTabs` component. The change ensures that when the `command` prop is already an object (with keys like `"yarn"`, `"pnpm"`, `"bun"`), the commands are not normalized, preserving any intentionally empty or custom values.
* Updated the `PackageManagerTabs` component to avoid normalizing commands when the `command` prop is an object with package manager keys, ensuring custom or empty commands are left unchanged.## Summary
> fix: command using object fully customize don't call normalize

- e2e/fixtures/with-base/doc/en/index.md
- e2e/fixtures/with-base/doc/en/index.mdx
- e2e/fixtures/with-base/doc/zh/index.md
- e2e/fixtures/with-base/doc/zh/index.mdx
- e2e/fixtures/with-base/index.test.ts
- packages/core/src/runtime/ClientApp.tsx
- packages/core/src/runtime/initPageData.ts
- packages/core/src/runtime/ssrServerEntry.tsx
- packages/runtime/src/index.ts
- packages/runtime/src/utils.ts
- packages/shared/src/index.ts
- packages/shared/src/runtime-utils/utils.test.ts
- packages/shared/src/runtime-utils/utils.ts
fix(core): "/base" should be rendered successfully when using `base`
When the base is set to ‘/’, `http://a.com/` and `http://a.com` point to the same page. (Browser default behavior)
However, when the base is set to ‘/base/’, `http://a.com/base/` and `http://a.com/base` actually represent different resources, but Rspress should allow access to `http://a.com/base` for compatibility, as users can deploy to /base. 
Rspress is compatible with both /base/ and /base
---
在 base 为 ‘/’ 时，`http://a.com/` 和  `http://a.com` 指向同一资源
但当 base 为 ‘/base/’ 时， `http://a.com/base/` 和 `http://a.com/base` 实际上代表着不同的资源，不过 Rspress 应该允许 `http://a.com/base` 的访问，以兼容用户可以部署到 /base 上
Rspress 兼容两种 /base/ 和 /base
For relative URL links, they are very dangerous.
We use react-router-dom, which is a lenient routing matching …
> fix(core): allow user can deploy to both `http://a.com/base/` and `http://a.com/base`

- packages/core/src/node/initRsbuild.ts
Rspack native watcher pass all rspress e2e tests. We can enable rspack native watcher in rspress by default. 
User can disable native watcher by setting RSPRESS_NATIVE_WATCHER as 'false' if we found any problems.
> feat: enable rspack native watcher by default

- packages/plugin-twoslash/src/index.ts
I forgot to add the class name. Sorry...
> fix(plugin-twoslash): Prevent the contents of the popup from being copied when copying code

- packages/plugin-twoslash/src/index.ts
- website/docs/en/plugin/official-plugins/twoslash.mdx
- website/docs/zh/plugin/official-plugins/twoslash.mdx
chore(plugin-twoslash): add hover style back
before
after
https://github.com/web-infra-dev/rspress/pull/2538#pullrequestreview-3175087980
> chore(plugin-twoslash): add hover style back

- packages/theme-default/src/styles/preflight.css
fix(theme-default/style): add `color: inherit` back
> fix(theme-default/style): add `color: inherit` back

- packages/plugin-twoslash/package.json
- packages/plugin-twoslash/src/index.ts
- packages/shared/src/runtime-utils/utils.ts
- pnpm-lock.yaml
This PR improves error handling in the Twoslash plugin.
In the development environment, it prevents builds from being interrupted by syntax errors in code blocks and logs the code blocks that cause the errors.
The following image shows an example of the improved error logging format:
> feat(plugin-twoslash): Improve error handling with enhanced logging

- packages/theme-default/src/components/Nav/NavMenuGroup.tsx
- packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
- packages/theme-default/src/components/Nav/index.module.scss
- packages/theme-default/src/components/NavHamburger/index.module.scss
- packages/theme-default/src/components/Search/index.tsx
chore(theme/style): nav group and add word-break: keep-all to navItem
before
after
before
after
> chore(theme/style): nav group and add word-break: keep-all to navItem

- packages/theme-default/src/styles/base.css
chore(theme/style): keep the html syntax in markdown original style
> chore(theme/style): keep the html syntax in markdown original style

- packages/theme-default/src/components/Badge/index.tsx
- packages/theme-default/src/components/PrevNextPage/index.tsx
- packages/theme-default/src/components/SourceCode/index.tsx
- packages/theme-default/src/components/Toc/index.tsx
1. 
2.
introducd in  (#2579) (#2600)
> fix(theme/style): some components should not be included in rp-doc

- packages/theme-default/src/components/PackageManagerTabs/index.tsx
- scripts/dictionary.txt
When using `<PackageManagerTabs>` with `exec={true}` it does not behave properly for `pnpm` and `bun`. This PR adds a new flag to distinguish between `exec` and `dlx`.
> feat(theme): add prop `dlx` to `PackageManagerTabs` for `npx` `pnpm dlx` etc
