web-infra-dev/rspress

README.md

feat: update Rspress banner

---

.changeset/new-geckos-help.md
packages/cli/src/index.ts
packages/core/src/node/dev.ts
packages/core/src/node/index.ts
packages/core/src/node/utils/detectReactVersion.ts
packages/core/src/node/utils/flattenMdxContent.ts
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-auto-nav-sidebar/src/index.ts
packages/shared/.eslintrc.cjs
packages/shared/logger.d.ts
packages/shared/modern.config.ts
packages/shared/package.json
packages/shared/src/logger.ts
pnpm-lock.yaml

1. Move logger to @rspress/shared package.
2. Refactor @rspress/cli dev logic.
3. Avoid error when _meta.json is not correct to improve DX.

fix: avoid error when _meta.json is not correct

---

packages/document/rspress.config.ts

docs: add navbar logo images

---

.changeset/forty-swans-agree.md
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json

- fix: sidebar disappear in windows
- fix: windows 系统下侧边栏消失

Release v0.0.12

---

.changeset/metal-readers-join.md
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json

- perf: preview plugin svgr
- feat: support SearchPanel component export
- feat: load babel from cdn
- feat: add playground plugin
- feat: update icon path in create-rspress
- feat: support icon absolute path
- feat: integrate @rspress/mdx-rs
- fix: runtime type missed
- fix: container syntax not work
- chore: no need to print the server bundles size
- perf: preview 插件 svgr 编译优化
- feat: 支持 SearchPanel 组件导出
- feat: 添加  playground 插件
- feat: 通过 cdn 加载 babel
- feat: 更新 create-rspress 中的图标路径
- feat: 支持 icon 配置绝对路径
- feat: 集成 @rspress/mdx-rs
- fix: runtime 目录类型丢失
- fix: 容器语法不生效
- chore: 无须输出 server bundles 的体积

Release v0.1.1

---

.changeset/fluffy-berries-exercise.md
.changeset/tender-camels-fly.md
packages/core/src/theme-default/index.ts
packages/plugin-preview/src/virtual-demo.tsx

fix: preview plugin build failed

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

Release v1.0.0-beta.0

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

Release v1.0.0-beta.1

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

Release v1.0.0-beta.2

---

.github/workflows/release-pull-request-with-modernjs.yml
.github/workflows/release-pull-request-without-modernjs.yml

chore(CI): no need to prepare monorepo tools

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

- feat: add `markdown.mdxRs` config
- feat: support enableCodesandbox
- fix: rspress/runtime alias in modernjs plugin
- chore(deps): unify rspack-plugin-virtual-module version
- chore: remove unuse peer dep

Release v1.0.0-beta.3

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

- feat: add `markdown.mdxRs` config
- feat: support enableCodesandbox
- feat: make navbar flexible
- feat: support hideNavbar config
- fix: rspress/runtime alias in modernjs plugin
- fix: delete useless import
- fix: home hero image path error when base path exists
- chore(deps): unify rspack-plugin-virtual-module version
- chore: remove unuse peer dep

Release v1.0.0-beta.4

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

- feat: add `markdown.mdxRs` config
- feat: support enableCodesandbox
- feat: make navbar flexible
- feat: support hideNavbar config
- fix: rspress/runtime alias in modernjs plugin
- fix: medium zoom not work after switching route
- fix: delete useless import
- fix: home hero image path error when base path exists
- chore(deps): unify rspack-plugin-virtual-module version
- chore: remove unuse peer dep

Release v1.0.0-beta.5

---

README.md

Add Rsbuild link to README.
https://github.com/web-infra-dev/rsbuild

docs: add Rsbuild link to README

---

.changeset/beige-deers-battle.md
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/create-rspress/CHANGELOG.md
packages/create-rspress/package.json
packages/document/CHANGELOG.md
packages/document/package.json
packages/modern-plugin-rspress/CHANGELOG.md
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/CHANGELOG.md
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/CHANGELOG.md
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-container-syntax/CHANGELOG.md
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/CHANGELOG.md
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/CHANGELOG.md
packages/plugin-medium-zoom/package.json
packages/plugin-playground/CHANGELOG.md
packages/plugin-playground/package.json
packages/plugin-preview/CHANGELOG.md
packages/plugin-preview/package.json
packages/plugin-typedoc/CHANGELOG.md
packages/plugin-typedoc/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
pnpm-lock.yaml

Release Note: https://github.com/web-infra-dev/wg/discussions/5
- feat: add `markdown.mdxRs` config
- feat: support enableCodesandbox
- feat: make navbar flexible
- feat: support hideNavbar config
- fix: rspress/runtime alias in modernjs plugin
- fix: medium zoom not work after switching route
- fix: delete useless import
- fix: home hero image path error when base path exists
- chore(deps): unify rspack-plugin-virtual-module version
- chore: modify search hooks …

Release v1.0.1

---

.changeset/rotten-ducks-leave.md
packages/core/modern.config.ts
packages/core/src/global.d.ts
packages/core/src/node/createBuilder.ts
packages/core/src/node/runtimeModule/index.ts
packages/core/src/node/runtimeModule/prismLanguages.ts
packages/core/src/node/runtimeModule/siteData.ts
packages/core/src/theme-default/layout/DocLayout/docComponents/code.tsx
packages/document/docs/en/api/config/config-build.mdx
packages/document/docs/zh/api/config/config-build.mdx
packages/shared/src/types/index.ts

[Feature]: Allow to configure prism languages

feat: add configure prism languages

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
.github/ISSUE_TEMPLATE/3-bug-report.zh-Hans.yml
.github/ISSUE_TEMPLATE/4-feature-request.zh-Hans.yml

- Add rspress to envinfo
- Update issue label

chore(workflow): add rspress to envinfo, update issue label

---

packages/document/rspress.config.ts

Configure Google Analytics for https://rspress.dev

docs: configure Google Analytics

---

CONTRIBUTING.md

https://github.com/web-infra-dev/rspress/issues/258

feat: fill contributing-guild about debug

---

packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx

fix: :pencil2: fixed typo

---

.changeset/chatty-beers-hope.md
packages/rspress-theme-default/src/theme-default/layout/DocLayout/index.tsx

style: overview page

---

.changeset/fluffy-yaks-eat.md
packages/shared/src/utils/index.ts

fix: remove base logic should only work in the leading path

---

.changeset/eight-jobs-relate.md
packages/rspress-theme-default/src/theme-default/components/HomeHero/index.tsx

fix: hero.actions does not handle empty array situations

---

.changeset/selfish-paws-think.md
e2e/tests/auto-nav-sidebar.test.ts
packages/rspress-theme-default/src/theme-default/logic/useSidebarData.ts

fix: sidebar incorrect in custom-link

---

.changeset/lemon-socks-cover.md
packages/rspress-theme-default/src/theme-default/components/PackageManagerTabs/index.tsx

fix: handling the case where command is an invalid value

---

.changeset/tiny-zoos-yell.md
packages/plugin-preview/src/codeToDemo.ts
packages/plugin-preview/static/global-components/Container.scss
packages/plugin-preview/static/global-components/common/index.scss
packages/plugin-preview/static/global-components/common/mobile-operation.tsx
packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx

fix: preview plugin style problem

---

.changeset/wild-sheep-return.md
packages/theme-default/src/layout/DocLayout/docComponents/img.tsx
packages/theme-default/src/layout/DocLayout/docComponents/index.tsx

Add base path for img src in md(x) file

fix: add base path for img in md(x)

---

.changeset/eighty-suits-attack.md
packages/document/docs/en/guide/basic/static-assets.mdx
packages/document/docs/zh/guide/basic/static-assets.mdx
packages/runtime/src/utils.ts
packages/theme-default/src/layout/DocLayout/docComponents/img.tsx

fix: image link crash in dev

---

.changeset/angry-icons-smoke.md
CONTRIBUTING.md
packages/document/docs/en/api/config/config-theme.mdx
packages/document/docs/en/guide/advanced/extend-build.mdx

As the title states
No related issues

doc: correct some mistakes in docs

---

.changeset/fair-experts-cough.md
packages/core/src/node/initRsbuild.ts

fix: tsx file in node_modules cannot be compiled

---

.changeset/hungry-eggs-enjoy.md
packages/theme-default/src/components/Sidebar/index.tsx

fix: compatible with scrollbar in firefox

---

.changeset/early-mugs-melt.md
packages/theme-default/src/components/HomeHero/index.tsx

feat: support multiline hero text

---

packages/core/index.html
packages/theme-default/src/layout/Layout/index.tsx

fix: html lang attribute

---

packages/document/docs/en/guide/basic/deploy.mdx

Adds Kinsta Static Site Hosting deployment guide

docs: Adds Kinsta Static Site Hosting

---

.changeset/little-ghosts-vanish.md
packages/runtime/src/utils.ts
packages/shared/src/utils/index.ts
packages/theme-default/src/components/Link/index.tsx

fix: overview page links cannot click

---

.changeset/weak-rings-know.md
packages/document/docs/zh/guide/basic/deploy.mdx

Translate deploy document to chinese version.
https://github.com/web-infra-dev/rspress/issues/337

feat: Translate deploy document to chinese version

---

.changeset/two-books-sparkle.md
packages/core/src/node/runtimeModule/prismLanguages.ts
packages/core/src/node/runtimeModule/siteData/index.ts
packages/document/docs/en/plugin/official-plugins/_meta.json
packages/document/docs/en/plugin/official-plugins/shiki.mdx
packages/document/docs/zh/plugin/official-plugins/_meta.json
packages/document/docs/zh/plugin/official-plugins/shiki.mdx
packages/document/package.json
packages/document/rspress.config.ts
packages/plugin-shiki/.eslintrc.cjs
packages/plugin-shiki/CHANGELOG.md
packages/plugin-shiki/LICENSE
packages/plugin-shiki/README.md
packages/plugin-shiki/modern.config.ts
packages/plugin-shiki/package.json
packages/plugin-shiki/shiki.css
packages/plugin-shiki/src/.eslintrc.cjs
packages/plugin-shiki/src/index.ts
packages/plugin-shiki/src/modern-app-env.d.ts
packages/plugin-shiki/src/rehypePlugin.ts
packages/plugin-shiki/tests/.eslintrc.cjs
packages/plugin-shiki/tests/tsconfig.json
packages/plugin-shiki/tsconfig.json
packages/plugin-shiki/vitest.config.ts
packages/shared/src/types/index.ts
packages/shared/src/utils/index.ts
packages/theme-default/src/layout/DocLayout/docComponents/code.tsx
pnpm-lock.yaml

Support the shiki highlight for code blocks.
Implement #211

feat: support shiki in rspress

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/3-bug-report.zh-Hans.yml

Change to use codesandbox template: https://codesandbox.io/s/github/web-infra-dev/rspress-codesandbox-template

chore: update issue template

---

.changeset/beige-bottles-mate.md
packages/theme-default/src/layout/DocLayout/docComponents/code.tsx

fix: copy code invalid in shiki mode

---

packages/document/docs/zh/api/config/config-theme.mdx

docs: Update config-theme.mdx

---

.changeset/wild-buttons-build.md
packages/theme-default/src/logic/useSidebarData.ts

Fix https://github.com/web-infra-dev/rspress/issues/360

fix: sidebar weird behaviour

---

.changeset/great-pots-enjoy.md
packages/plugin-shiki/src/rehypePlugin.ts
packages/theme-default/src/layout/DocLayout/docComponents/code.tsx
packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss

fix: line highlight and code title not work in shiki mode

---

packages/core/modern.config.ts
packages/shared/modern.config.ts

I think we can simpify the build config in repo, remove some unuse line to understand easily

chore: simplify buildConfig

---

.changeset/fast-news-swim.md
packages/core/src/node/build.ts

fix: support pure esm project

---

.changeset/healthy-lemons-vanish.md
packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss

文档中链接在小屏的样式优化
without `word-break: break-all;`
with it

文档中链接在小屏的样式优化

---

.github/workflows/bench-pr.yaml

chore: add pr bench yaml

---

.changeset/kind-grapes-marry.md
packages/document/docs/en/plugin/system/plugin-api.mdx
packages/document/docs/zh/plugin/system/plugin-api.mdx

docs: Sync documents for the config of plugin

---

CONTRIBUTING.md

docs: add benchmark in CONTRIBUTING docs

---

.changeset/flat-badgers-pump.md
packages/document/rspress.config.ts
packages/document/tsconfig.json
packages/theme-default/src/layout/DocLayout/docComponents/code.tsx
packages/theme-default/src/layout/DocLayout/docComponents/link.tsx

fix: blank line in code block when open line numbers

---

.changeset/silver-ducks-join.md
packages/core/src/node/route/RouteService.test.ts
packages/core/src/node/route/RouteService.ts

fix: normalize route optimize

---

.changeset/strong-flowers-speak.md
packages/shared/src/utils/index.test.ts
packages/shared/src/utils/index.ts

fix: clean urls should handle the urls ending with /

---

.changeset/polite-timers-confess.md
packages/theme-default/src/components/Link/index.tsx
packages/theme-default/src/logic/utils.ts

fix: mailto link in docs cannot jump

---

packages/core/package.json
pnpm-lock.yaml

Support uppercase image extname
Fix #395

chore: bump mdx-rs

---

.changeset/curly-crabs-tickle.md
packages/shared/src/utils/index.ts

fix: add default param for isExternalUrl

---

.changeset/dry-beans-sit.md
packages/core/src/node/runtimeModule/siteData/extractPageData.ts

fix: skip code blocks in search index

---

.changeset/twelve-stingrays-bathe.md
packages/document/docs/en/guide/advanced/custom-theme.mdx
packages/document/docs/zh/guide/advanced/custom-theme.mdx
packages/theme-default/src/components/LocalSideBar/index.tsx
packages/theme-default/src/components/Sidebar/index.tsx
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/layout/Layout/index.tsx

feat: add sidebar slots

---

.changeset/heavy-rocks-raise.md
packages/theme-default/src/components/Sidebar/index.tsx

chore: optimize sidebar group title color

---

.changeset/calm-eagles-listen.md
packages/shared/package.json

fix: license for shared package

---

packages/core/package.json
pnpm-lock.yaml

fix: header anchor and toc id is inconsistent

---

packages/document/docs/en/guide/basic/use-mdx.mdx
packages/document/docs/zh/guide/basic/use-mdx.mdx

docs: remove warning about custom-id

---

.changeset/nice-dots-confess.md
packages/core/src/node/build.ts

fix: disable minify in ssr build

---

.changeset/long-singers-promise.md
packages/document/docs/en/fragments/internal-components.mdx
packages/document/docs/zh/fragments/internal-components.mdx

docs: update the document for LastUpdated and PrevNextPage component

---

README.md
packages/cli/README.md
packages/document/rspress.config.ts

Fix discord invitation link.
https://github.com/web-infra-dev/rspress/issues/456

docs: fix discord invitation link

---

.changeset/curvy-impalas-swim.md
packages/shared/package.json
pnpm-lock.yaml

chore(@rspress/shared): remove globby

---

.changeset/witty-pandas-sniff.md
packages/runtime/src/index.ts

feat: add useSearchParams hook in rspress/runtime

---

.changeset/hungry-ads-rule.md
packages/plugin-api-docgen/src/index.ts

chore(plugin-api-docgen): disable mdxRs by default

---

.changeset/empty-laws-laugh.md
packages/core/modern.config.ts
packages/core/package.json
packages/core/src/node/initRsbuild.ts
pnpm-lock.yaml

chore(core): move tailwindcss from dependencies to devDependencies

---

.changeset/fuzzy-boxes-sin.md
e2e/fixtures/modern-js/modern.config.ts
packages/modern-plugin-rspress/src/features/lanchDoc.ts
packages/modern-plugin-rspress/src/types.ts

fix(modern-plugin): deprecate some config and optimize sidebar and locale

---

.changeset/wild-pumpkins-wonder.md
packages/theme-default/src/styles/code.css

fix: class selector in code block

---

.changeset/soft-yaks-explode.md
packages/document/docs/en/guide/advanced/custom-theme.mdx
packages/document/docs/zh/guide/advanced/custom-theme.mdx
packages/theme-default/src/components/Nav/index.tsx
packages/theme-default/src/layout/Layout/index.tsx

feat: add after nav menu slot

---

.changeset/thirty-rocks-brake.md
packages/theme-default/src/components/Search/SearchPanel.tsx

fix: failed to submit search when rendering with react@16

---

packages/core/src/node/initRsbuild.ts
packages/core/src/node/mdx/loader.ts
packages/document/docs/en/api/config/config-build.mdx
packages/document/docs/en/fragments/mdx-rs.mdx
packages/document/docs/zh/api/config/config-build.mdx
packages/document/docs/zh/fragments/mdx-rs.mdx
packages/shared/src/types/index.ts

https://github.com/web-infra-dev/rspress/issues/488

feat: enable mdx-rs compiler according to the filepath

---

.changeset/ten-hairs-admire.md
packages/theme-default/src/components/Search/logic/util.ts

fix: normalize text case for number

---

.changeset/shiny-zebras-leave.md
packages/document/docs/en/guide/advanced/custom-search.mdx
packages/document/docs/zh/guide/advanced/custom-search.mdx
packages/theme-default/src/components/Search/SearchPanel.tsx
packages/theme-default/src/components/Search/logic/types.ts

feat: support custom render type in onSearch hook

---

.changeset/smooth-pugs-kneel.md
packages/shared/src/runtime-utils/index.ts
packages/theme-default/src/components/Nav/menuDataHooks.tsx

fix: doc sidebar when cleanUrls is enabled

---

.changeset/twenty-pens-swim.md
e2e/tests/i18n.test.ts
e2e/tests/nav-link-item-without-suffix.test.ts
e2e/tests/nav-link-item.test.ts
packages/theme-default/src/components/Nav/NavMenuGroup.tsx
packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
packages/theme-default/src/components/Search/index.tsx

feat: add class name for nav menu item and search button

---

.changeset/gold-trains-dress.md
packages/core/src/runtime/App.tsx

fix(runtime): ignore case in runtime

---

.changeset/cold-dots-learn.md
packages/cli/src/index.ts
packages/cli/src/update.ts
packages/document/docs/en/api/commands.mdx
packages/document/docs/zh/api/commands.mdx

https://github.com/web-infra-dev/rspress/issues/509

feat(cli): add update command

---

.changeset/warm-bobcats-destroy.md
packages/core/index.html
packages/core/src/node/build.ts
packages/core/src/node/constants.ts

Add about html head meta generator.

feat: html head meta generator

---

.changeset/dull-glasses-shave.md
packages/theme-default/src/layout/DocLayout/docComponents/table.tsx

fix: table width overflow sometimes

---

.changeset/tricky-papayas-scream.md
packages/modern-plugin-rspress/src/features/lanchDoc.ts

fix(modern-plugin): support custom root

---

.vscode/extensions.json
.vscode/settings.json
biome.json
e2e/fixtures/modern-js/package.json
package.json
packages/core/package.json
packages/create-rspress/src/index.ts
packages/create-rspress/src/utils.ts
packages/plugin-api-docgen/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/runtime/package.json
packages/theme-default/package.json
pnpm-lock.yaml

use biome as formatter
// SKIP

feat: introduce biome to rspress

---

.vscode/settings.json
package.json
pnpm-lock.yaml

Add prettier formatter for md(x) files
#549

feat: add prettier for md(x) files

---

.changeset/real-tigers-glow.md
packages/theme-default/src/components/LocalSideBar/index.scss
packages/theme-default/src/components/LocalSideBar/index.tsx
packages/theme-default/src/components/Toc/index.css
packages/theme-default/src/components/Toc/index.tsx
packages/theme-default/src/logic/useHiddenNav.ts

feat: support toc in mobile device

---

packages/document/docs/en/plugin/system/write-a-plugin.mdx
packages/document/docs/zh/plugin/system/write-a-plugin.mdx

docs: typo fix of "write-a-plugin.mdx"

---

packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx

docs: fix typo

---

packages/core/src/node/mdx/loader.ts

fix: frontmatter is injected by default

---

packages/theme-default/src/components/Button/index.module.scss
packages/theme-default/src/components/HomeHero/index.module.scss
packages/theme-default/src/components/HomeHero/index.tsx
packages/theme-default/src/components/Nav/index.module.scss

style: optimize home hero button style

---

packages/document/docs/en/guide/basic/deploy.mdx
packages/document/docs/zh/guide/basic/deploy.mdx

docs: add deploy to Zeabur guide

---

.changeset/tough-pets-glow.md
packages/cli/src/index.ts

perf(cli): config.root conditional judgment

---

.changeset/great-donuts-compete.md
packages/plugin-playground/src/cli/remarkPlugin.ts
packages/plugin-playground/src/web/ast.ts
packages/plugin-playground/src/web/runner.tsx

fix: playground cannot work with name import alias

---

.changeset/curly-bottles-own.md
packages/modern-plugin-rspress/src/features/lanchDoc.ts
packages/modern-plugin-rspress/src/features/normalizeOptions.ts
packages/modern-plugin-rspress/src/types.ts

feat(modern-plugin): support defaultRenderMode

---

.changeset/rare-ways-remain.md
packages/document/docs/en/api/config/config-theme.mdx
packages/document/docs/zh/api/config/config-theme.mdx
packages/theme-default/src/logic/useAppearance.ts

fix: theme global vars does not work

---

.changeset/hip-tables-complain.md
packages/document/components/Benchmark/index.module.scss
packages/modern-plugin-rspress/static/global-components/Overview.module.scss
packages/plugin-container-syntax/container.css
packages/plugin-preview/static/global-components/common/index.scss
packages/theme-default/src/components/Aside/index.css
packages/theme-default/src/components/Button/index.module.scss
packages/theme-default/src/components/LocalSideBar/index.scss
packages/theme-default/src/components/Nav/NavMenuGroup.tsx
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/Overview/index.module.scss
packages/theme-default/src/components/PrevNextPage/index.module.scss
packages/theme-default/src/components/Search/index.module.scss
packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
packages/theme-default/src/components/Sidebar/SidebarItem.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/Tabs/index.module.scss
packages/theme-default/src/components/Toc/index.css
packages/theme-default/src/styles/code.css
packages/theme-default/src/styles/scrollbar.css
packages/theme-default/src/styles/vars.css

feat: expose radius css variable

---

.changeset/kind-adults-bathe.md
packages/theme-default/src/components/Nav/NavMenuGroup.tsx

fix(theme-default): fix incorrect css variable name

---

README.md
packages/cli/README.md

Update discord server expired invites with new permanant ones

chore(discord): updated links - now permanant links 

---

.changeset/config.json

chore: update e2e dep version when fixed

---

.changeset/kind-cars-grin.md
packages/plugin-preview/src/index.ts

fix(plugin-preview): support rspress restart

---

packages/theme-default/src/components/NavHambmger/index.tsx

patch(theme-default): added label to hamburger btn for accessibility

---

.changeset/config.json
.changeset/thin-ducks-divide.md
packages/theme-default/src/index.ts

feat: add DocLayout export

---

packages/document/docs/en/plugin/official-plugins/preview.mdx
packages/document/docs/zh/plugin/official-plugins/preview.mdx

docs(preview): update preview plugin options

---

.changeset/khaki-olives-confess.md
.changeset/shiny-forks-clean.md
.changeset/slimy-dogs-happen.md
.changeset/sour-meals-enjoy.md
.changeset/spotty-needles-clap.md
.changeset/wise-rivers-deny.md
e2e/tests/modern-js.test.ts
packages/core/src/node/mdx/loader.ts
packages/core/src/node/runtimeModule/index.ts
packages/core/src/node/runtimeModule/siteData/extractPageData.ts
packages/core/src/node/runtimeModule/siteData/normalizeThemeConfig.ts
packages/core/src/node/utils/flattenMdxContent.ts
packages/core/src/runtime/App.tsx
packages/plugin-auto-nav-sidebar/src/index.ts
packages/plugin-auto-nav-sidebar/src/walk.ts
packages/shared/src/types/defaultTheme.ts
packages/theme-default/src/components/Sidebar/SidebarItem.tsx
packages/theme-default/src/components/Sidebar/index.tsx

fix: sidebar label & toc hmr not work

---

packages/theme-default/src/components/Nav/index.tsx

fix: respect search flag on mobile devices

---

.changeset/cuddly-horses-doubt.md
packages/plugin-auto-nav-sidebar/src/walk.ts
packages/shared/src/runtime-utils/index.ts

Fix #667 
TODO: add a square-with-arrow icon for external link, welcome your PR!

fix: support external link in nav

---

.changeset/old-kids-rescue.md
packages/core/src/node/initRsbuild.ts

fix(core): use alias to support custom theme, instead of detect

---

.changeset/chilled-moons-listen.md
packages/document/docs/en/fragments/internal-components.mdx
packages/document/docs/en/guide/default-theme/components.mdx
packages/document/docs/zh/fragments/internal-components.mdx
packages/document/docs/zh/guide/default-theme/components.mdx
packages/theme-default/src/components/Steps/index.module.scss
packages/theme-default/src/components/Steps/index.tsx
packages/theme-default/src/index.ts

feat(internal-components): New Steps Component!

---

.changeset/early-flies-glow.md
packages/core/src/node/constants.ts
packages/core/src/node/utils/flattenMdxContent.ts

fix(core): remove global to avoid ambiguity in non-greedy match in flat mdx

---

.changeset/warm-lions-care.md
packages/theme-default/src/layout/DocLayout/docComponents/code/CopyCodeButton.tsx
packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx

chore: replace omitted svg import statement

---

packages/core/src/node/initRsbuild.ts

This is not neccessary.https://github.com/web-infra-dev/rspress/pull/686/files#diff-c3ceee9eb7c9e951e561766a1fefdd19afce9f8b51ff185184eae6c6ed23c280R187-R188

chore: it should remove extensions in #686

---

.changeset/few-beans-love.md
packages/core/src/node/utils/flattenMdxContent.ts

fix: add semicon judgement in flattenMdxContent

---

.changeset/smooth-masks-sniff.md
packages/core/src/node/utils/flattenMdxContent.ts

fix(core): replace all import info in mdx

---

README.md

docs(README):  add graphs contributors

---

.changeset/early-apples-lick.md
packages/theme-default/src/logic/useFullTextSearch.ts

fix: useFullTextSearch hook not work

---

.changeset/five-hounds-punch.md
packages/plugin-container-syntax/container.css
packages/theme-default/src/styles/vars.css

chore: optimize dark mode style

---

packages/core/package.json
pnpm-lock.yaml

Fix https://github.com/web-infra-dev/mdx-rs/issues/19

fix: repeated quote in toc

---

biome.json

chore: ignore history dir

---

.changeset/stale-pots-breathe.md
packages/plugin-preview/src/remarkPlugin.ts

fix(preview): keep code element src prop if it is not a relative path

---

.changeset/new-chicken-melt.md
packages/document/docs/en/plugin/official-plugins/preview.mdx
packages/document/docs/zh/plugin/official-plugins/preview.mdx
packages/plugin-preview/src/index.ts
packages/plugin-preview/src/types.ts

feat(preview): add support for custom iframe buildConfig

---

README.md

Improve contributor graph query params.
Before:
After:

 docs: improve contributor graph query params

---

.changeset/smooth-cycles-run.md
packages/plugin-preview/package.json
packages/plugin-preview/static/global-styles/entry.css
pnpm-lock.yaml

fix(preview): add theme to preview plugin dep and import theme css

---

.changeset/silly-pens-suffer.md
packages/core/src/node/runtimeModule/siteData/normalizeThemeConfig.ts
packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
packages/plugin-auto-nav-sidebar/src/type.ts
packages/plugin-auto-nav-sidebar/src/walk.ts
packages/shared/src/types/defaultTheme.ts
packages/theme-default/src/components/Sidebar/SidebarSectionHeader.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/Sidebar/index.tsx

feat: support section header in _meta.json

---

.changeset/thick-cheetahs-bow.md
packages/core/package.json
packages/core/src/node/mdx/loader.ts
packages/core/src/node/mdx/remarkPlugins/toc.ts
packages/core/src/node/runtimeModule/siteData/index.ts
packages/theme-default/src/components/Aside/index.tsx
packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
packages/theme-default/src/components/Sidebar/SidebarItem.tsx
packages/theme-default/src/components/Sidebar/SidebarSectionHeader.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/Toc/index.tsx
packages/theme-default/src/logic/utils.ts
packages/theme-default/src/styles/code.css
pnpm-lock.yaml

implement #719 
`mdx-rs` change: https://github.com/web-infra-dev/mdx-rs/pull/23

feat: support inline markdown in sidebar

---

package.json

upgrade, and the lockfileVersion will be 6.0

chore: update packgae manager version

---

.changeset/lazy-radios-love.md
packages/plugin-preview/package.json
packages/plugin-preview/src/index.ts
packages/plugin-preview/src/remarkPlugin.ts
packages/plugin-preview/src/virtual-module.ts
packages/plugin-preview/static/global-components/Device.tsx
pnpm-lock.yaml

After #734 ,remove virtual module plugin

fix(preview): remove virtual module plugin and use pageMeta in mdx loader

---

.changeset/great-buttons-dress.md
packages/theme-default/src/layout/DocLayout/index.module.scss

fix(theme): adjust rspress doc max width

---

.changeset/nice-items-live.md
packages/modern-plugin-rspress/static/global-components/Overview.tsx
packages/modern-plugin-rspress/static/global-components/arrow-right.js

fix(modern-plugin): pre transform svg to component

---

.changeset/hungry-bags-eat.md
packages/cli/src/index.ts

fix: i18n json change will not trigger rebuild

---

packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx

Fix lint issue in pre.tsx (I should update to latest code before merging https://github.com/web-infra-dev/rspress/pull/753)

chore: fix lint issue in pre.tsx

---

packages/theme-default/src/components/SocialLinks/index.module.scss

chore: vertical align icons

---

.changeset/quiet-plums-appear.md
packages/theme-default/src/components/Search/SearchPanel.tsx
packages/theme-default/src/components/Search/SuggestItem.tsx
packages/theme-default/src/components/Tabs/index.tsx

fix(theme): only scroll panel when item is unvisible

---

.changeset/smart-rockets-sleep.md
packages/theme-default/src/components/Sidebar/SidebarItem.tsx
packages/theme-default/src/logic/useRerender.ts

Fix #770 https://github.com/web-infra-dev/rsbuild/issues/1798

fix: sidebar text not update when navigate to other nav item (#770)

---

README.md

Add the badges and quality to README.
Rendered: https://github.com/web-infra-dev/rspress/blob/3c6ea6dbb490f7804c161711657dc339e3dd0d08/README.md

docs: add badges and quality to README

---

.changeset/tasty-bears-crash.md
packages/core/src/node/PluginDriver.ts

If you configure locales in theme Config, it will report an error.
And the types nav and sidebar are optional.

fix(PluginDriver): nav and sidebar add ?

---

.changeset/fifty-pans-drum.md
packages/plugin-api-docgen/src/index.ts

fix(api-docgen): support match double label api comp

---

.changeset/stale-rockets-knock.md
packages/core/src/runtime/App.tsx
packages/core/src/runtime/global.d.ts

fix: custom theme color not work

---

.changeset/rude-ravens-collect.md
packages/theme-default/src/logic/utils.ts

chore: optimize nav experience in pad device

---

.changeset/young-apples-occur.md
packages/core/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Fix https://github.com/mdx-js/mdx/pull/2252

chore: update mdx to 2.3.0

---

packages/document/docs/en/fragments/internal-components.mdx
packages/document/docs/zh/fragments/internal-components.mdx
packages/theme-default/src/components/SideBar/SidebarDivider.tsx
packages/theme-default/src/components/SideBar/SidebarGroup.tsx
packages/theme-default/src/components/SideBar/SidebarItem.tsx
packages/theme-default/src/components/SideBar/SidebarSectionHeader.tsx
packages/theme-default/src/components/SideBar/index.module.scss
packages/theme-default/src/components/SideBar/index.tsx

docs: add hero and overview component

---

.changeset/neat-roses-attend.md
packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/Sidebar/index.tsx

chore: remove parent sidebar group highlight

---

packages/document/docs/en/guide/default-theme/i18n.mdx
packages/document/docs/zh/guide/default-theme/i18n.mdx

Remove duplicated list in markdown.

docs: remove duplicated list

---

.changeset/tasty-bears-crash.md

chore: fix major changeset

---

.changeset/strange-months-glow.md
packages/plugin-preview/src/index.ts

fix(preview): add user builderPlugin to iframe builder

---

.changeset/breezy-points-visit.md
packages/cli/src/index.ts
packages/document/docs/en/api/commands.mdx

fix(cli): fix relevant typo

---

.changeset/red-lions-unite.md
packages/theme-default/src/logic/utils.ts

fix(theme): replace angle brackets in inline markdown

---

packages/document/docs/en/guide/basic/ssg.mdx
packages/document/docs/zh/guide/basic/ssg.mdx
packages/plugin-playground/src/web/editor.tsx

Fix broken Rsbuild links in the document.

docs: fix broken Rsbuild links

---

.changeset/wet-ears-suffer.md
packages/core/src/node/runtimeModule/siteData/index.ts
packages/document/docs/en/api/config/config-basic.mdx
packages/document/docs/zh/api/config/config-basic.mdx
packages/shared/src/types/index.ts
packages/theme-default/src/components/Nav/NavBarTitle.tsx

feat: support logo text config

---

.changeset/purple-flies-kiss.md
packages/plugin-preview/src/index.ts

which make iframe.position valid.

fix(preview): replace iframePosition with iframe.position

---

.changeset/lazy-timers-provide.md
packages/core/src/node/runtimeModule/siteData/index.ts

fix(core): remove searchHooks in siteData

---

.changeset/nice-sloths-invent.md
packages/core/src/runtime/clientEntry.tsx
packages/theme-default/src/components/Nav/NavBarTitle.tsx
packages/theme-default/src/components/SvgWrapper/index.tsx
packages/theme-default/src/components/SwitchAppearance/index.tsx

fix: icon/logo display error in dark mode when refresh page

---

.changeset/ninety-tables-begin.md
packages/theme-default/src/components/Overview/index.tsx

feat(theme): render code in overview component

---

.changeset/metal-onions-hammer.md
packages/theme-default/src/styles/code.css

chore(theme): optimize code style in sidebar

---

packages/document/docs/en/api/config/config-build.mdx
packages/document/docs/en/guide/advanced/extend-build.mdx
packages/document/docs/zh/api/config/config-build.mdx
packages/document/docs/zh/guide/advanced/extend-build.mdx

Improve extend build guide, add some examples for Google analytics and open graph meta tags.

docs: improve extend build guide

---

.changeset/thin-houses-flash.md
packages/theme-default/src/components/Nav/NavBarTitle.tsx
packages/theme-default/src/components/SwitchAppearance/index.tsx
packages/theme-default/src/logic/utils.ts

fix: avoid flash of navbar images (logo and theme icon)

---

.github/workflows/release-nightly.yml
.github/workflows/release-pull-request-with-modernjs.yml
.github/workflows/release-pull-request-without-modernjs.yml
.github/workflows/release.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
packages/document/docs/en/guide/basic/deploy.mdx
packages/document/docs/zh/guide/basic/deploy.mdx

Try to fix the CI issue:
https://github.com/web-infra-dev/rspress/actions/runs/8567848099/job/23480458440?pr=909

chore(workflow): bump actions/setup-node v4

---

.changeset/thick-lobsters-run.md
packages/document/docs/en/plugin/official-plugins/_meta.json
packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
packages/document/docs/en/plugin/official-plugins/overview.mdx
packages/document/docs/zh/plugin/official-plugins/_meta.json
packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
packages/document/docs/zh/plugin/official-plugins/overview.mdx

@rspress/plugin-api-docgen is undocumentated.

docs(plugins): add @rspress/plugin-api-docgen

---

packages/core/src/node/initRsbuild.ts

Add builtin rsbuild plugins before third party plugins (added by `rspressConfig.builderConfig.plugins`).
- before:
- after:

fix: add builtin rsbuild plugins before thrid party plugins

---

.changeset/modern-olives-swim.md
e2e/fixtures/plugin-rss/doc/blog/bar.md
e2e/fixtures/plugin-rss/doc/blog/foo.md
e2e/tests/plugin-rss.test.ts
packages/document/docs/en/plugin/official-plugins/rss.mdx
packages/document/docs/zh/plugin/official-plugins/rss.mdx
packages/plugin-rss/src/internals/lang.ts
packages/plugin-rss/src/internals/type.ts
packages/plugin-rss/src/options.ts
packages/plugin-rss/src/plugin-rss.ts
packages/plugin-rss/src/type.ts

feat(plugin-rss): sort rss items by publishing date in decreasing order

---

packages/core/src/node/runtimeModule/siteData/index.ts

Previously in `siteDataVMPlugin` we modify the siteData object to deal with some issues?
But it's a shallow copy, the config will be used in other runtime module like `searchHookVMPlugin`.
In below codes, searchHooks has been set undefined, which cause `searchHookVMPlugin` inject an empty module.
https://github.com/web-infra-dev/rspress/blob/8b0649b731f5751947e70be0c8245d1f92dd5bf6/packages/core/src/node/runtimeModule/siteData/index.ts#L31
https://github.com/web-infra-dev/rspress/blob/8b0649b731f5751947e70be0c8245d1f92dd5bf6/packages/core/src/node/runtimeModule/siteData/index.ts#L105
https://github.com/web-infra-dev/rspress/blob/8b0649b731f5751947e70be0c8245d1f92dd5bf6/packages/core/src/node/runtimeModule/siteData/index.ts#L120-L122

fix: avoid unexpected changes to searchHooks

---

.changeset/serious-seals-brush.md

chore: add release changeset

---

packages/plugin-auto-nav-sidebar/src/walk.ts

fix: log error when scan sidemeta

---

packages/document/docs/en/api/config/config-basic.mdx
packages/document/docs/en/guide/default-theme/multi-version.mdx

added english documentation for `versioned` search.
#947

docs: versioned search

---

packages/modern-plugin-rspress/src/lanchDoc.ts

Fix 
If we add some assets in public.

fix(modern-plugin): improve ignore for auto sidebar

---

packages/document/docs/zh/plugin/official-plugins/playground.mdx

docs: fix plugin-playground typo

---

packages/document/docs/en/plugin/official-plugins/playground.mdx

the same as https://github.com/web-infra-dev/rspress/pull/990

docs: fix Runner typo

---

packages/theme-default/src/components/NavHambmger/index.module.scss
packages/theme-default/src/components/NavScreen/index.module.scss
packages/theme-default/src/components/Search/index.module.scss
packages/theme-default/src/layout/DocLayout/docComponents/code/index.module.scss

fix: button background color style

---

.changeset/plenty-birds-matter.md
packages/theme-default/src/components/HomeHero/index.tsx

style: use items-center in hero block

---

.changeset/neat-rabbits-hide.md
packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
packages/theme-default/src/styles/code.css
packages/theme-default/src/styles/vars.css

style: optimize inline code and link style

---

packages/core/src/node/initRsbuild.ts
packages/core/src/node/utils/detectReactVersion.ts

fix: client compile error when set react-dom/server alias

---

packages/core/package.json
packages/theme-default/src/logic/utils.ts
pnpm-lock.yaml

Fixed the issue of the right sidebar not being displayed.
closes: #952

fix(theme-default): display sidebar emphasis text

---

packages/theme-default/src/components/PackageManagerTabs/index.tsx
packages/theme-default/src/components/Tabs/index.tsx

[Feature]: Syncing PackageManagerTabs and Tabs Choices
closes: #937

feat(theme-default): sync tab choices

---

packages/theme-default/src/components/Aside/index.tsx
packages/theme-default/src/logic/utils.ts

feat: support tooltip when hover aside item

---

packages/shared/src/runtime-utils/index.ts
packages/theme-default/src/components/Nav/menuDataHooks.tsx

fix(theme-default): changing language and version on 404 page does nothing

---

packages/core/src/runtime/App.tsx
packages/theme-default/src/layout/NotFountLayout/index.tsx

fix(theme-default): 404 page doesn't back to home of current lang and version

---

packages/core/package.json
pnpm-lock.yaml

chore(deps): bump @rspress/mdx-rs to 0.5.4

---

.changeset/five-eels-smoke.md
packages/modern-plugin-rspress/src/lanchDoc.ts

fix: module doc should scan _meta.json

---

packages/document/docs/en/guide/basic/deploy.mdx
packages/document/docs/zh/guide/basic/deploy.mdx

使用现有的配置，github action在运行时会有很多warning，因此进行更新

docs: update deploy.mdx to use node 20、pnpm 8

---

packages/plugin-auto-nav-sidebar/src/utils.ts

fix: detect file error when file is public resource

---

packages/core/src/node/runtimeModule/prismLanguages.ts
packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
packages/core/tests/md.test.ts
packages/core/tests/prismLanguages.test.ts

test(core): add unit test for prismLanguages

---

.changeset/dull-panthers-rescue.md

chore: add changeset for 1.21.0 release

---

packages/core/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/mdx-rs/issues/41

fix(deps): bump mdx-rs 0.5.7 to trim when collect title in compile

---

packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/layout/DocLayout/index.module.scss

fix(theme-default): the serial number of the two-digit number will become one digit. 10. -> 1.

---

packages/theme-default/src/components/Search/SearchPanel.tsx

do not display no search result when search not completed

fix: do not display no search result when search not completed

---

.changeset/purple-ways-march.md

chore: add 1.21.1 changeset

---

e2e/fixtures/modern-js/modern.config.ts
e2e/fixtures/modern-js/tsconfig.build.json
e2e/fixtures/modern-js/tsconfig.json

fix: tsconfig in modernjs e2e fixtures

---

packages/shared/src/types/index.ts
packages/theme-default/src/components/Search/SearchPanel.tsx

- add search.loading options for remote search
- remove  1s of search index loading for local search

feat: add search.loading options for remote search

---

packages/theme-default/src/components/Tabs/index.tsx

Correct the props type of `Tabs` and `Tab` to match the implementation.

fix(Tabs): correct the props type

---

packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/core/src/node/route/RouteService.test.ts
packages/core/src/node/runtimeModule/siteData/normalizeThemeConfig.ts
packages/core/src/node/utils/detectReactVersion.ts
packages/core/src/node/utils/getASTNodeImport.ts
packages/core/src/runtime/App.tsx
packages/modern-plugin-rspress/static/global-components/arrow-right.js
packages/plugin-api-docgen/src/docgen.ts
packages/plugin-api-docgen/src/index.ts
packages/plugin-preview/src/utils.ts
packages/theme-default/src/components/SocialLinks/LinkContent.tsx
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/logic/sideEffects.ts

chore: biome format

---

packages/theme-default/src/components/LocalSideBar/index.scss
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/Sidebar/index.tsx

fix(theme-default): sidebar scrollbar height error on ios safari and mask is invalid

---

e2e/tests/custom-id.test.ts
e2e/tests/replace-rules.test.ts
package.json

chore: enable biome format in lint-staged

---

packages/document/docs/en/guide/advanced/custom-theme.mdx
packages/document/docs/zh/guide/advanced/custom-theme.mdx

docs: default theme export

---

.changeset/warm-balloons-rush.md

chore: add 1.22.0 changeset

---

e2e/fixtures/i18n/doc/en/_meta.json
e2e/fixtures/i18n/doc/en/api/index.mdx
e2e/fixtures/i18n/doc/zh/_meta.json
e2e/fixtures/i18n/doc/zh/api/index.mdx
e2e/tests/i18n.test.ts
packages/theme-default/src/components/Overview/index.tsx

fix page crash when switch lang in api

fix: page crash when switch lang in api

---

packages/plugin-container-syntax/container.css

style: modify link style in container

---

packages/plugin-container-syntax/container.css

chore: optimize css syntax

---

packages/theme-default/src/components/Search/SearchPanel.tsx

fix some issues in multiple search origin
- Can not use keyboard to control choose search result
- Incorrect state change when search keywords change

fix: multi tab search

---

.changeset/forty-pumpkins-rhyme.md

chore: add 1.23.0 changeset

---

.changeset/young-boats-obey.md

chore: add 1.23.1 changeset

---

e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
e2e/fixtures/auto-nav-sidebar/doc/api/config/_meta.json
e2e/fixtures/auto-nav-sidebar/doc/api/config/config-frontmatter.mdx
e2e/tests/auto-nav-sidebar.test.ts
packages/document/docs/en/api/config/config-frontmatter.mdx
packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
packages/document/docs/zh/api/config/config-frontmatter.mdx
packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
packages/plugin-auto-nav-sidebar/src/type.ts
packages/plugin-auto-nav-sidebar/src/utils.ts
packages/plugin-auto-nav-sidebar/src/walk.ts
packages/shared/src/types/defaultTheme.ts
packages/shared/src/types/index.ts
packages/theme-default/src/components/Sidebar/SidebarGroup.tsx

feat: support inject context when generate sidebar

---

packages/document/package.json

Fixed stack overflowing for ecosystem ci
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/9477766179/job/26113078564#step:6:612

chore: fix rspack-ecosystem-ci

---

e2e/fixtures/custom-headers/package.json
e2e/fixtures/custom-headers/rspress.config.ts
e2e/tests/custom-headers.test.ts
packages/document/docs/zh/api/config/config-basic.mdx
packages/document/docs/zh/api/config/config-frontmatter.mdx
pnpm-lock.yaml

docs: add head config doc in zh

---

.changeset/large-chicken-punch.md

chore: add 1.24.0 changeset

---

packages/document/package.json

fixed in https://github.com/web-infra-dev/rspack/pull/6783

chore: remove RUST_MIN_STACK env

---

packages/core/src/node/build.ts
packages/document/docs/404.mdx
packages/theme-default/src/layout/Layout/index.tsx

feat: generate 404.html by default

---

packages/document/documate.json
packages/document/package.json
packages/document/rspress.config.ts

see https://github.com/web-infra-dev/rspress/pull/1089

docs: remove usued documate config

---

.changeset/cuddly-moons-eat.md

chore: add 1.25.0 changeset

---

.changeset/tender-stingrays-dream.md

chore: add 1.25.1 changeset

---

packages/runtime/src/utils.ts
packages/theme-default/src/layout/DocLayout/docComponents/prisim-theme.ts
packages/theme-default/src/styles/base.css

style: enhance color of code token inserted/deleted

---

.changeset/tall-squids-watch.md
e2e/fixtures/custom-headers/rspress.config.ts
e2e/tests/custom-headers.test.ts
packages/core/src/node/utils/renderHead.ts

fix generated head tag have a extra brace

fix: generated head tag have a extra brace

---

README.md

Remove underlines between badges:

docs: remove underlines between badges

---

packages/core/src/node/initRsbuild.ts

perf(core): parallel the alias fetch

---

packages/theme-default/src/components/HomeFeature/index.module.scss
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/layout/HomeLayout/index.css
packages/theme-default/src/styles/vars.css

- before:
- after:
- before:
- after:
- before:
- after:

feat: improve menu item hover style and card background color

---

packages/document/docs/zh/index.md
packages/theme-default/src/components/HomeHero/index.tsx
packages/theme-default/src/layout/HomeLayout/index.tsx

fix(theme-default): homepage hero link

---

.changeset/calm-numbers-do.md
package.json
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

* fix(theme-default): homepage hero link by @shulaoda in https://github.com/web-infra-dev/rspress/pull/1247
* fix(deps): bump rsbuild 1.0.0-alpha.9 by @chenjiahan in https://github.com/web-infra-dev/rspress/pull/1250
**Full Changelog**: https://github.com/web-infra-dev/rspress/compare/v1.26.0...v1.26.1

Release v1.26.1

---

packages/document/theme/index.css
packages/theme-default/src/components/HomeHero/index.module.scss
packages/theme-default/src/layout/HomeLayout/index.css

Add theme vars for customizing home page:
- mask color
- hero text width
- hero image width

feat: add theme vars for customizing home page

---

packages/theme-default/src/components/HomeFeature/index.tsx
packages/theme-default/src/components/HomeHero/index.tsx
packages/theme-default/src/layout/HomeLayout/index.tsx

fix(theme-default): features link in the homepage does not contain the base path

---

.changeset/afraid-cars-cover.md

chore: add 1.26.2 changeset

---

packages/document/docs/en/api/config/config-build.mdx
packages/document/docs/en/plugin/system/plugin-api.mdx
packages/document/docs/zh/api/config/config-build.mdx
packages/document/docs/zh/plugin/system/plugin-api.mdx

Add some example for Rsbuild configuration.

docs: add example for Rsbuild configuration

---

packages/document/docs/en/guide/basic/custom-page.mdx
packages/document/docs/zh/guide/basic/custom-page.mdx

Translate custom tags guide to Chinese
https://github.com/web-infra-dev/rspress/pull/1207

docs: translate custom tags guide

---

README.md

docs: add Rslib links

---

packages/document/package.json
packages/document/theme/components/ToolStack.tsx
packages/document/theme/index.tsx
pnpm-lock.yaml

bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

---

.changeset/friendly-insects-raise.md

chore: add 1.28.0 changeset

---

packages/document/rspress.config.ts

docs: enable strict SSG

---

.changeset/rotten-pillows-destroy.md

chore: add 1.28.1 changeset

---

packages/core/src/node/initRsbuild.ts
packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
packages/theme-default/src/global.d.ts

fix: use `__webpack_public_path__` for search index url

---

packages/document/package.json
pnpm-lock.yaml

Reverts web-infra-dev/rspress#1378
styles need to be adapted.

Revert "chore(deps): update dependency @rstack-dev/doc-ui to ^1.3.2"

---

packages/theme-default/src/components/HomeFeature/index.tsx

support render html in feature icon
https://github.com/web-infra-dev/rspress/discussions/1393

feat: support render html in feature icon

---

.changeset/lucky-boxes-clap.md

chore: add changeset

---

.changeset/popular-pugs-develop.md

chore: add changeset for releasing

---

.github/workflows/release.yml

Switch to renovate, see https://github.com/web-infra-dev/modern.js/pull/6242

chore: remove release trigger modern update

---

packages/document/docs/en/plugin/community-plugins/overview.mdx
packages/document/docs/zh/plugin/community-plugins/overview.mdx
packages/document/package.json
packages/document/rspress.config.ts
pnpm-lock.yaml

Enable the sitemap plugin and add it to the community plugin list.

docs: enable sitemap plugin

---

packages/core/src/node/runtimeModule/siteData/extractPageData.ts
packages/core/src/node/runtimeModule/siteData/index.ts
packages/plugin-rss/src/feed.ts
packages/shared/src/types/index.ts
packages/theme-default/src/logic/useEditLink.ts

XML file generation
RSS Render
#1405

feat: support RSS html feedline

---

packages/core/src/node/initRsbuild.ts

optimize the performance, a little bit

perf: do not emit assets in SSR

---

packages/theme-default/src/components/Nav/NavBarTitle.tsx

fix: use `Link` for `NavBarTitle`

---

.changeset/pink-dryers-cross.md
packages/document/docs/en/guide/advanced/custom-theme.mdx
packages/document/docs/zh/guide/advanced/custom-theme.mdx
packages/theme-default/src/components/LocalSideBar/index.tsx
packages/theme-default/src/components/Nav/index.tsx
packages/theme-default/src/components/Sidebar/index.tsx
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/layout/Layout/index.tsx

feat: support replacement nav title

---

e2e/tests/auto-nav-sidebar.test.ts
packages/core/src/node/runtimeModule/siteData/index.ts
packages/document/docs/en/api/config/config-frontmatter.mdx
packages/document/docs/zh/api/config/config-frontmatter.mdx
packages/theme-default/src/components/Sidebar/SidebarGroup.tsx

Add some named classnames for `Sidebar` component for better selection of css.

feat: add named className for sidebar component

---

.changeset/wise-planes-flow.md
packages/core/src/node/PluginDriver.ts

fix: only reduce iterator when plugin exists

---

packages/document/docs/en/guide/start/introduction.mdx
packages/document/docs/zh/guide/start/introduction.mdx

https://docusaurus.io/blog/releases/3.6#docusaurus-faster

docs: modify Docusaurus related

---

packages/plugin-api-docgen/static/global-components/API.scss
packages/plugin-api-docgen/static/global-components/API.tsx

fix(plugin-api-docgen): Avoid style pollution

---

packages/core/package.json
pnpm-lock.yaml

Remove unused `@loadable/component` dependency.

fix(deps): remove unused @loadable/component

---

package.json
packages/plugin-rss/src/internals/node.ts
pnpm-lock.yaml

Bump pnpm from v8 to v9, fix a type issue.

chore(deps): bump pnpm from v8 to v9

---

.husky/pre-commit
package.json
pnpm-lock.yaml

bump husky v9
close https://github.com/web-infra-dev/rspress/pull/1302

chore(deps): bump husky v9

---

packages/theme-default/src/logic/useHiddenNav.ts

https://github.com/web-infra-dev/rspress/issues/1588

fix(theme): nav will not be displayed when scrolling to the top(#1588)

---

.github/ISSUE_TEMPLATE/bug-report.en-US.yml
.github/ISSUE_TEMPLATE/feature-request.en-US.yml

> Issues types allow you to classify and manage your issues with a shared and consistent language across all repositories in the organization, such as bugs or tasks.
https://github.com/orgs/community/discussions/139933

chore(workflow): set Issue types

---

e2e/tests/plugin-shiki.test.ts
packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx

fix: add code wrapping support for shiki highlighting

---

.changeset/old-rings-warn.md

chore: release minor changeset

---

.github/workflows/bench-pr.yml
.github/workflows/release.yml

Remove all issue_comment trigger for security.

chore(CI): remove issue_comment trigger

---

CONTRIBUTING.md
package.json
pnpm-lock.yaml
scripts/generateReleasePr.mjs

chore(CI): modify release steps

---

.github/workflows/release.yml

chore(CI): use inputs.branch to checkout

---

package.json

chore(deps): bump pnpm v10

---

.changeset/config.json
pnpm-lock.yaml
pnpm-workspace.yaml

chore(infra): modify changeset config to ignore private packages

---

packages/document/docs/en/guide/start/getting-started.mdx
packages/document/docs/zh/guide/start/getting-started.mdx

docs: add bun to init project guide

---

e2e/fixtures/github-alert-mdxjs/doc/index.mdx
e2e/fixtures/github-alert-mdxrs/doc/index.mdx
e2e/tests/github-alert-mdxjs.test.ts
e2e/tests/github-alert-mdxrs.test.ts
packages/core/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspress/pull/1745#issuecomment-2586543862

feat: support nested container syntax in component in mdx-rs

---

packages/cli/package.json
packages/core/package.json
packages/plugin-preview/package.json
packages/shared/package.json
pnpm-lock.yaml

Bump @rsbuild/core 1.2.0-beta.1, see https://github.com/web-infra-dev/rsbuild/releases

chore(deps): bump @rsbuild/core 1.2.0-beta.1

---

README.md

update Rslib description in README.md

chore: update Rslib description in README.md

---

.nvmrc
package.json

- update pnpm 10.2.0 to fix https://github.com/pnpm/pnpm/issues/8978
- update Node.js to v23.7.0 in `.nvmrc`, which enable latest version of corepack to fix netlify error caused by https://github.com/nodejs/corepack/issues/612
- https://github.com/pnpm/pnpm/releases/tag/v10.2.0

chore(deps): update pnpm v10.2.0 and Node.js v23.7.0 for development

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.41.0

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.41.1

---

CONTRIBUTING.md

remove benchmarking chapter in CONTRIBUTING.md

chore: remove benchmarking chapter in CONTRIBUTING.md

---

packages/core/rslib.config.ts

Remove unnecessary externals declarations.

chore(core): clean Rslib config

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.41.2

---

packages/document/docs/en/api/config/config-theme.mdx
packages/document/docs/en/plugin/official-plugins/last-updated.mdx
packages/document/docs/zh/api/config/config-theme.mdx
packages/document/docs/zh/plugin/official-plugins/last-updated.mdx
packages/shared/src/types/defaultTheme.ts

Initially, I assumed the feature relied on the file's mtime. However, I observed that mtime wasn't consistently updated after file modifications. While the upload time derived from `git` appears reasonable, I recommend documenting this behavior for clarity.

docs: update lastUpdated  need commit

---

packages/core/src/node/build.ts
packages/core/src/node/mdx/loader.ts
packages/core/src/node/runtimeModule/i18n.ts
packages/core/src/node/utils/checkLanguageParity.ts
packages/core/src/node/utils/detectReactVersion.ts
packages/core/src/node/utils/flattenMdxContent.ts
packages/plugin-api-docgen/src/docgen.ts
packages/shared/src/node-utils/loadFrontMatter.ts

should emit the full error with error.stack

refactor: should emit the detailed error stack

---

packages/theme-default/src/components/NavScreen/index.tsx

before
https://github.com/user-attachments/assets/a1e94dfa-41a0-4ab5-a665-6314296a92a2

fix(ui): SwitchApperance CLS, a flash when switching to dark mode

---

packages/theme-default/src/components/Aside/index.tsx

revert some changes of https://github.com/web-infra-dev/rspress/pull/1856
after further investigation, 
1. why scroll to the middle content when navigating to other page? 
` history.scrollRestoration = 'auto'`
https://github.com/web-infra-dev/rspress/pull/1181
2. why revert `setTimeout` related code?
there is a TOC highlight bug
https://github.com/user-attachments/assets/32d61e32-69e9-4f52-8f48-b9c0f84f3013
3. interesting things
https://github.com/web-infra-dev/rspress/blob/48df322887efa2975ac4feb0d80ae48ea4522acf/packages/theme-default/src/logic/sideEffects.ts#L182 
these codes are useless 😄
we currently all the scroll behavior is in 
https://github.com/web-infra-dev/rspress/blob/48df322887efa2975ac4feb0d80ae48ea4522acf/packages/theme-default/src/components/Aside/index.tsx#L69-74
should …

fix(ui): for TOC highlight, revert `setTimeout` set unbinding changes

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.41.3

---

packages/theme-default/src/components/Search/SearchPanel.tsx

Before:
https://github.com/user-attachments/assets/700d8293-f98a-40e0-a443-d7b8625f25c8
After:
https://github.com/user-attachments/assets/a5fafd76-8877-48a7-846d-27c3996374c0
fix: https://github.com/web-infra-dev/rspress/issues/1861

fix(ui): prevent key events from triggering during composition

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.42.0

---

e2e/fixtures/search-code-blocks/doc/index.mdx
e2e/tests/search-code-blocks.test.ts
e2e/utils/search.ts
packages/core/src/node/runtimeModule/siteData/extractPageData.ts

fix(search): should search JSX element code block
close https://github.com/web-infra-dev/rspress/issues/1864

fix(search): should search JSX element code block

---

packages/core/src/node/route/RouteService.test.ts

https://github.com/rspack-contrib/path-serializer.git
#1868

test(infra): use path-serializer

---

e2e/fixtures/modern-js/package.json
packages/cli/src/index.ts
packages/core/package.json
packages/core/src/node/build.ts
packages/core/theme.css
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/theme-default/package.json

1. update `"files"` list, remove src and useless files
2. bundle package.json with namedImport
3. remove `"jsnext: source"` field

perf(size): 🔥remove package.json useless field and bundle named package.json

---

.changeset/fluffy-seals-invite.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.42.1

---

packages/plugin-api-docgen/src/docgen.ts
packages/plugin-api-docgen/src/index.ts
packages/plugin-api-docgen/src/locales.ts
packages/plugin-api-docgen/src/types.ts

add Russian support
https://github.com/web-infra-dev/rspress/issues/1872

fix(plugin-api-docgen): add Russian support

---

packages/document/docs/en/api/config/config-build.mdx
packages/document/docs/en/guide/advanced/extend-build.mdx
packages/document/docs/zh/api/config/config-build.mdx
packages/document/docs/zh/guide/advanced/extend-build.mdx

Improve Rsbuild plugin guides
resolve https://github.com/rspack-contrib/rsbuild-plugin-yaml/issues/10

docs: improve Rsbuild plugin guides

---

packages/core/package.json
packages/document/package.json
packages/document/rspress.config.ts
packages/plugin-algolia/LICENSE
packages/plugin-algolia/README.md
packages/plugin-algolia/package.json
packages/plugin-algolia/rslib.config.ts
packages/plugin-algolia/src/env.d.ts
packages/plugin-algolia/src/index.ts
packages/plugin-algolia/tests/tsconfig.json
packages/plugin-algolia/tsconfig.json
packages/plugin-client-redirects/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-shiki/package.json
pnpm-lock.yaml

1. init the @rspress/plugin-algolia pkg
empty now, add content in next pr
2. fix the "module" field which points to empty file

feat(plugin-algolia): init plugin-algolia

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.0

---

.github/workflows/lint.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml

Update the workflows to support 1.x branch.
This will ensure that the workflows can be triggered when we need to submit some PRs that target the 1.x branch.

chore: update workflows to support 1.x branch

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml
scripts/generateReleasePr.mjs

Release v2.0.0-alpha.0

---

e2e/tests/hide-nav-bar.test.ts
packages/theme-default/src/components/LocalSideBar/index.scss
packages/theme-default/src/components/LocalSideBar/index.tsx
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/NavHamburger/index.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/layout/DocLayout/index.module.scss
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/layout/Layout/index.tsx
packages/theme-default/src/logic/utils.ts

fix: display outline correctly on >=960px <=1280px screen width

---

packages/plugin-api-docgen/src/docgen.ts
packages/plugin-api-docgen/src/index.ts
packages/plugin-api-docgen/src/locales.ts
packages/plugin-api-docgen/src/types.ts

Co-authored-by: SoonIter <sooniter@gmail.com>

fix(plugin-api-docgen): add Russian support (#1890)

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.1

---

e2e/tests/hide-nav-bar.test.ts
packages/theme-default/src/components/LocalSideBar/index.scss
packages/theme-default/src/components/LocalSideBar/index.tsx
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/NavHamburger/index.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/layout/DocLayout/index.module.scss
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/layout/Layout/index.tsx
packages/theme-default/src/logic/utils.ts

This reverts commit b21f5af8c7b35f8d720d0332952e46237b67f1b5.
https://github.com/web-infra-dev/rspress/pull/1929

fix: Revert "fix: display outline correctly on >=960px <=1280px screen width (#1914)"

---

.changeset/1741592309550-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rspress/pull/1930
https://github.com/web-infra-dev/rspress/pull/1929
close https://github.com/web-infra-dev/rspress/issues/1924

Release v2.0.0-alpha.1

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.2

---

e2e/tests/hide-nav-bar.test.ts
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/NavHamburger/index.module.scss
packages/theme-default/src/components/Overview/index.module.scss
packages/theme-default/src/components/Overview/index.tsx
packages/theme-default/src/components/Sidebar/index.module.scss
packages/theme-default/src/components/SidebarMenu/index.scss
packages/theme-default/src/components/SidebarMenu/index.tsx
packages/theme-default/src/layout/DocLayout/index.module.scss
packages/theme-default/src/layout/DocLayout/index.tsx
packages/theme-default/src/layout/Layout/index.tsx
packages/theme-default/src/logic/utils.ts
packages/theme-default/src/styles/vars.css

close #1540
related #1914
---
I aslo added `--rp-content-padding-x` and `--rp-content-padding-y` css variables so that the aside can be responsive their changes.

fix: rework sidebar menu responsive issues

---

packages/cli/src/index.ts

fix(cli): should catch build errors

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.3

---

packages/core/src/node/mdx/options.ts
packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts

fix(mdxjs): not need to add base on normalizing links with base enabled

---

packages/core/src/node/serve.ts

feat: expose builder preview result for programming usage

---

.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
packages/core/rslib.config.ts
packages/core/src/node/build.ts

https://github.com/web-infra-dev/rspress/issues/1951 is not fixed yet

fix(deps): update react-helmet-async 2.0.0(#1951)

---

e2e/fixtures/modern-js/package.json
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml
scripts/config/package.json

small tasks for
react v19
react-dom v19
react-router-dom v7

chore(deps): update typescript 5.8.2

---

packages/plugin-preview/static/global-styles/iframe.css
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/Nav/index.tsx
packages/theme-default/src/components/SidebarMenu/index.scss
packages/theme-default/src/components/SidebarMenu/index.tsx
packages/theme-default/src/layout/DocLayout/index.module.scss
packages/theme-default/src/layout/DocLayout/index.tsx

https://github.com/web-infra-dev/rspress/issues/1540#issuecomment-2720302738
cc @Timeless0911

fix: improve reported responsive issues

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.5

---

packages/theme-default/src/layout/DocLayout/index.tsx

related https://github.com/web-infra-dev/rspress/issues/1540#issuecomment-2726465563
cc @chenjiahan

fix: overview page overflow

---

packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss

Add link icon for external links, referenced from https://lynxjs.org/.

feat(style): add link icon for external links

---

.changeset/1742268020817-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.3

---

packages/theme-default/src/components/DocFooter/index.tsx
packages/theme-default/src/logic/usePrevNextPage.ts

https://github.com/callstack/repack/blob/2eb2c88921caac4bf3e648b1f92e74f0f644268d/website/theme/index.tsx#L97

fix(theme/PrevNextPage): should be hidden when text is undefined or `""`

---

packages/core/package.json
packages/core/src/node/mdx/options.ts
packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
packages/core/tests/__snapshots__/md.test.ts.snap
packages/core/tests/md.test.ts
packages/shared/src/node-utils/getNodeAttribute.ts
pnpm-lock.yaml

related #1979
cc @Timeless0911 @chenjiahan

fix: normalize jsx img src attribute correctly

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.7

---

.changeset/1742442914124-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.4

---

packages/theme-default/src/components/Aside/index.tsx
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/Overview/index.module.scss
packages/theme-default/src/components/SidebarMenu/index.scss
packages/theme-default/src/components/SidebarMenu/index.tsx
packages/theme-default/src/components/Toc/index.tsx
packages/theme-default/src/layout/DocLayout/index.tsx
pnpm-lock.yaml

fix: continue work on responsive styling issues

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.8

---

packages/document/docs/en/api/config/config-frontmatter.mdx
packages/document/docs/en/guide/basic/use-mdx.mdx
packages/document/docs/zh/api/config/config-frontmatter.mdx
packages/document/docs/zh/guide/basic/use-mdx.mdx

Improve the clarity of the font matter documentation by standardizing the terminology and adding helpful links.

docs: enhance front matter documentation

---

packages/core/src/node/logger/hint.ts

chore: add break statement to hintThemeBreakingChange function

---

packages/core/src/node/mdx/options.ts
packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
packages/core/src/node/route/RouteService.ts
packages/core/src/node/route/normalizeRoutePath.test.ts
packages/core/src/node/route/normalizeRoutePath.ts

fix(mdxjs): add `version` and `lang` part when normalizing links

---

packages/core/src/node/mdx/rehypePlugins/headerAnchor.ts
packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/core/src/node/runtimeModule/globalStyles.ts

refactor: improve header anchor logic and simplify URL validation

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.9

---

.changeset/1742805735940-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.6

---

packages/plugin-api-docgen/src/index.ts

fix(plugin-api-docgen): fallback to en, and should report warning msg when no replacing

---

packages/modern-plugin-rspress/src/launchDoc.ts
packages/plugin-api-docgen/src/index.ts

chore: improve preview mode handling in launchDoc function

---

packages/theme-default/src/components/HomeHero/index.tsx
packages/theme-default/src/components/NavHamburger/index.tsx
packages/theme-default/src/components/Search/SearchPanel.tsx

https://github.com/web-infra-dev/rspress/pull/1990

fix(theme/style): SearchPanel is not styled by tailwind

---

.changeset/1742963831878-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.7

---

packages/theme-default/src/components/Nav/NavMenuGroup.tsx

chore(theme/a11y): a11y for lighthouse score

---

packages/core/src/node/logger/hint.ts
packages/core/tests/cli/hint.test.ts

fix(cli): polish theme namedExport breaking change hint

---

packages/core/src/runtime/clientEntry.tsx
packages/plugin-preview/static/global-components/Device.tsx
packages/runtime/src/hooks.ts
packages/runtime/src/index.ts
packages/shared/src/types/index.ts
packages/theme-default/src/components/Aside/index.tsx
packages/theme-default/src/components/Link/index.tsx
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/Nav/index.tsx
packages/theme-default/src/components/SidebarMenu/index.scss
packages/theme-default/src/index.ts
packages/theme-default/src/layout/Layout/index.tsx
packages/theme-default/src/logic/sideEffects.ts
packages/theme-default/src/logic/useUISwitch.ts
packages/theme-default/src/logic/utils.ts
packages/theme-default/src/styles/base.css
packages/theme-default/src/styles/vars.css

related https://github.com/web-infra-dev/rspress/issues/1540\#issuecomment-2765136979
cc @SoonIter @Timeless0911 
Not sure whether should and how to add related test cases.

refactor: change `setup` into `useSetup` hook for reactive `scrollPaddingTop`

---

.changeset/1743492717894-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.8

---

e2e/fixtures/i18n/doc/zh/_meta.json
packages/cli/src/index.ts
packages/core/package.json
packages/core/src/node/initRsbuild.ts
packages/core/src/node/runtimeModule/i18n.ts
packages/core/src/node/runtimeModule/index.ts
pnpm-lock.yaml

add [rsbuild-plugin-virtual-module](https://github.com/rspack-contrib/rsbuild-plugin-virtual-module)
implement hmr of virtual-module
https://github.com/web-infra-dev/rspress/pull/2033

refactor(virtual-module): i18n.json restart -> reload/hmr

---

.changeset/1744275418984-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.9

---

packages/theme-default/src/logic/useUISwitch.ts

close https://github.com/web-infra-dev/rspress/issues/2054

fix(firefox): location too much change firefox issue #2047

---

e2e/fixtures/ssg-fail-strict/rspress-csr.config.ts
e2e/tests/ssg-fail-strict.test.ts
e2e/utils/runCommands.ts
packages/core/src/node/build.ts
packages/core/src/node/logger/hint.ts
packages/core/src/runtime/clientEntry.tsx
packages/document/docs/en/api/config/config-basic.mdx
packages/document/docs/zh/api/config/config-basic.mdx
packages/shared/src/types/index.ts

1. fallback to csr at compile time is too surprising for users, so just remove it 
2. add hint 
no surprising error

feat(ssg)!: remove ssg fallback and add `ssg: false` hint

---

packages/plugin-rss/tsconfig.runtime.json
packages/theme-default/package.json
pnpm-lock.yaml

chore: remove modern-js/tsconfig

chore: remove @modern-js/tsconfig

---

.changeset/1744370544037-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.10

---

packages/core/src/node/build.ts
packages/core/src/node/dev.ts
packages/core/src/node/serve.ts
packages/core/src/node/ssg/renderPages.ts

chore: move ssg type and rename a variable
a very small change

chore: move ssg type and rename a variable

---

.changeset/1744892391718-alpha-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-alpha.12

---

.github/workflows/preview.yml

chore(infra): add pkg.pr.new

---

packages/document/rspress.config.ts

docs: migrate to docsearch new account

docs: migrate to docsearch new account

---

.github/workflows/preview.yml

chore(infra): fix the exclude filter does not work

chore(infra): fix the exclude filter does not work

---

packages/core/src/node/initRsbuild.ts
packages/core/src/node/utils/detectReactVersion.ts

fix https://github.com/web-infra-dev/web-infra-QoS/actions/runs/14585375712/job/40909847856
introduced in #2083 
use `resolver.resolve` to get 'module' instead of `require.resolve` to get 'main'

fix: reduce react-router-dom bundle size

---

.changeset/1745465744856-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.1

---

packages/document/docs/en/plugin/official-plugins/llms.mdx
packages/document/docs/zh/plugin/official-plugins/llms.mdx
packages/plugin-llms/src/plugin.ts
packages/plugin-llms/src/types.ts

feat(plugin-llms): add include option and only generate for default lang

feat(plugin-llms): add include option and only generate for default lang

---

packages/plugin-llms/src/llmsTxt.ts

chore(plugin-llms): adjust the llms-full.txt format and add url frontmatter

chore(plugin-llms): adjust the llms-full.txt format and add url frontmatter

---

.changeset/1745484667337-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.2

---

packages/plugin-api-docgen/src/index.ts

fix(plugin-api-docgen): fallback to en, and should report warning msg when no replacing (#2004)

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.12

---

packages/document/docs/en/_meta.json
packages/document/docs/zh/_meta.json

docs: add 1.x doc link

---

packages/core/package.json
packages/core/src/node/ssg/renderPages.ts
packages/core/src/runtime/App.tsx
packages/runtime/package.json
packages/runtime/src/index.ts
packages/theme-default/package.json
packages/theme-default/src/layout/Layout/index.tsx
pnpm-lock.yaml
scripts/dictionary.txt

chore(deps): migrate react-helmet-async to @dr.pogodin/react-helmet 
react-helmet-async is maintained in a low state
https://github.com/staylor/react-helmet-async/issues/239
https://github.com/web-infra-dev/rspress/pull/2073#issuecomment-2826213154

chore(deps): migrate react-helmet-async to @dr.pogodin/react-helmet

---

.changeset/1746011765581-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.3

---

e2e/utils/runCommands.ts
packages/core/src/node/initRsbuild.ts

feat!: enable lazyCompilation: true by default 
https://rsbuild.dev/config/dev/lazy-compilation

feat!: enable `dev.lazyCompilation: true` by default 

---

.changeset/1746615678526-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.4

---

packages/document/rspress.config.ts
packages/document/theme/index.tsx
packages/plugin-algolia/src/runtime/Search.css
packages/runtime/src/hooks.ts
packages/theme-default/src/components/Nav/index.module.scss
packages/theme-default/src/components/Nav/index.tsx

docs(algolia-search): use new docsearch account and optimize the dark mode

---

packages/cli/package.json
packages/core/package.json
packages/plugin-llms/package.json
packages/plugin-preview/package.json
packages/shared/package.json
pnpm-lock.yaml

related https://github.com/web-infra-dev/rspack/issues/9987
cc @chenjiahan @SoonIter @Timeless0911

chore: bump rsbuild to v1.3.17

---

packages/theme-default/src/components/Aside/processTitleElement.ts
packages/theme-default/src/components/Aside/useDynamicToc.ts

fix(theme/dynamic-toc): skip <a /> element in TOC

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.43.13

---

.changeset/1746718529158-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.5

---

e2e/tests/plugin-api-docgen.test.ts
packages/plugin-api-docgen/package.json
packages/plugin-api-docgen/static/global-components/API.tsx
pnpm-lock.yaml

fix(plugin-api-doc-gen): plugin-api-doc-gen  should have anchor (#2140)

---

e2e/fixtures/plugin-playground/doc/index.mdx
e2e/tests/plugin-playground.test.ts
packages/document/docs/en/plugin/official-plugins/playground.mdx
packages/document/docs/zh/plugin/official-plugins/playground.mdx
packages/plugin-playground/static/global-components/Playground.tsx

fix(plugin-playground): disable monaco editor ts check for supporting tsx #2028

---

e2e/tests/modern-js.test.ts
packages/document/docs/en/plugin/official-plugins/preview.mdx
packages/document/docs/zh/plugin/official-plugins/preview.mdx
packages/plugin-preview/src/generate-entry.ts
packages/plugin-preview/src/index.ts
packages/plugin-preview/src/remarkPlugin.ts
packages/plugin-preview/src/types.ts
packages/plugin-preview/static/global-components/Container.tsx
packages/plugin-preview/static/global-components/ContainerFixedPerComp.tsx
packages/plugin-preview/static/global-components/Device.scss
packages/plugin-preview/static/global-components/Device.tsx
packages/plugin-preview/static/global-components/common/index.scss

1. add `rspress-` for css className
2. add iframe.position, `'fixed-with-per-comp'`

feat(plugin-preview): add iframePostion 'fixed-with-per-comp'

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.44.0

---

packages/document/README.md

Update the website contributing guide to be consistent with other websites: https://github.com/web-infra-dev/rslib/blob/main/website/README.md

docs: update website contributing guide

---

packages/document/theme/index.tsx

docs(algolia): update index name

docs(algolia): update index name

---

packages/core/src/node/mdx/loader.ts
packages/shared/src/node-utils/loadFrontMatter.ts

fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes
close #2010

fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes

---

packages/core/src/node/mdx/loader.ts
packages/shared/src/node-utils/loadFrontMatter.ts

fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes
related #2168

fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes (#2168)

---

e2e/fixtures/plugin-shiki/doc/langAlias.mdx
e2e/fixtures/plugin-shiki/rspress.config.ts
e2e/tests/plugin-shiki.test.ts
packages/plugin-shiki/package.json
packages/shared/package.json
packages/theme-default/src/styles/base.css
pnpm-lock.yaml

support `langAlias`
https://github.com/shikijs/shiki/pull/1015
https://github.com/web-infra-dev/rspack/pull/10387

feat(plugin-shiki): upgrade to shiki@^3.4.2 to support langAlias option

---

README.md
packages/document/package.json
pnpm-lock.yaml
scripts/dictionary.txt

This PR adds a new "Rstack" section to the README files , which details the projects of the Rstack toolchain and helps users to understand its concepts and goals.
The contributors chart has been simplified to reduce unimportant information.
Same as https://github.com/web-infra-dev/rspack/pull/10424

docs: update Rstack introduction

---

e2e/fixtures/plugin-preview-fixed-with-per-comp/doc/component.jsx
e2e/fixtures/plugin-preview-fixed-with-per-comp/doc/index.mdx
e2e/fixtures/plugin-preview-fixed-with-per-comp/doc/prop.mdx
e2e/fixtures/plugin-preview-fixed-with-per-comp/package.json
e2e/fixtures/plugin-preview-fixed-with-per-comp/rspress.config.ts
e2e/fixtures/plugin-preview-fixed-with-per-comp/tsconfig.json
e2e/fixtures/plugin-preview/doc/prop.mdx
e2e/fixtures/plugin-preview/rspress.config.ts
e2e/tests/plugin-preview-fixed-with-per-comp.test.ts
packages/plugin-preview/src/index.ts
packages/plugin-preview/static/global-components/ContainerFixedPerComp.tsx
packages/plugin-preview/static/global-components/DeviceFixedPerComp.tsx
packages/plugin-preview/static/global-components/common/mobile-operation.tsx
packages/plugin-preview/static/global-components/icons/Back.tsx
packages/plugin-preview/static/global-components/useIframeUrlPerComp.ts
pnpm-lock.yaml

fix(plugin-preview): fixed-per-comp "internal" prop should work
#2152

fix(plugin-preview): fixed-per-comp "internal" prop should work

---

packages/plugin-shiki/package.json
packages/plugin-shiki/src/shiki/pluginShiki.ts

docs(plugin-shiki): update package.json description

docs(plugin-shiki): update package.json description

---

packages/theme-default/src/index.ts
packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx

fix(theme-default): export type CodeButtonGroupProps

---

packages/document/docs/en/guide/default-theme/navbar.mdx
packages/document/docs/zh/guide/default-theme/navbar.mdx

fix incorrect usage of `socialLinks`
N/A

docs: incorrect usage of `socialLinks`

---

packages/document/docs/en/guide/default-theme/navbar.mdx
packages/document/docs/zh/guide/default-theme/navbar.mdx

fix incorrect usage of `socialLinks`
#2192

docs: incorrect usage of `socialLinks` (#2192)

---

packages/plugin-algolia/src/runtime/Search.css

chore(plugin-algolia): highlight color can be changed by theme color

---

.changeset/1748334349312-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.8

---

packages/core/src/node/initRsbuild.ts
packages/core/src/node/runtimeModule/index.ts
packages/core/src/node/runtimeModule/routeList.ts
packages/core/src/node/runtimeModule/types.ts
packages/core/src/runtime/env.d.ts
packages/core/src/runtime/ssrServerEntry.tsx
packages/runtime/rslib.config.ts
packages/runtime/src/env.d.ts
packages/runtime/src/route.test.ts
packages/runtime/src/route.ts
packages/theme-default/rslib.config.ts
packages/theme-default/src/logic/getSidebarDataGroup.test.ts

refactor: remove 'virtual-routes-ssr' module, unify virtual-routes-ssr  into virtual-routes module

refactor(virtual-module): remove 'virtual-routes-ssr' module, unify virtual-routes-ssr  into virtual-routes module

---

packages/core/package.json
packages/core/src/node/initRsbuild.ts
packages/core/src/runtime/App.tsx
packages/core/src/runtime/initPageData.ts
packages/runtime/package.json
packages/theme-default/package.json
packages/theme-default/src/layout/Layout/index.tsx
packages/theme-default/src/styles/index.ts
pnpm-lock.yaml

refactor: unify all the virtual-global-styles to ensure the css order

refactor: unify all the virtual-global-styles to ensure the css order

---

packages/document/docs/en/plugin/official-plugins/algolia.mdx
packages/document/docs/zh/plugin/official-plugins/algolia.mdx

https://docsearch.algolia.com/docs/templates#rspress-template

docs: upgrade the algolia template

---

.changeset/1749009057911-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.10

---

.changeset/1749211862799-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.11

---

.changeset/1749553879583-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.12

---

.changeset/1749608554269-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.13

---

.github/renovate.json5

chore(renovate): allow to bump pnpm version automatically

chore(renovate): allow to bump pnpm version automatically

---

.changeset/1749715750245-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.14

---

README.md

docs: fix Rsbuild url in README.md

---

packages/core/src/node/mdx/rehypePlugins/__snapshots__/headerAnchor.test.ts.snap
packages/core/src/node/mdx/rehypePlugins/headerAnchor.test.ts
packages/core/src/node/mdx/rehypePlugins/headerAnchor.ts
packages/core/src/node/mdx/remarkPlugins/toc.ts
packages/plugin-api-docgen/static/global-components/API.tsx

fix(rehypeHeaderAnchor): trim anchor for better format with React Component

fix(rehypeHeaderAnchor): trim anchor for better format with React Component

---

.changeset/1750845526812-beta-release.md
package.json
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.17

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

https://github.com/web-infra-dev/rslib/releases/tag/v0.10.3
chore(deps): upgrade @rslib/core@0.10.3

chore(deps): upgrade @rslib/core@0.10.3

---

packages/cli/package.json
packages/cli/shiki-transformers.ts
packages/core/rslib.config.ts

fix: should add nav-json-schema.json

fix: should add nav-json-schema.json and expose `rspress/shiki-transformers`

---

packages/cli/package.json
packages/core/package.json
packages/plugin-llms/package.json
packages/plugin-preview/package.json
packages/shared/package.json
pnpm-lock.yaml

chore(deps): upgrade to Rsbuild@1.4.0
https://rspack.dev/blog/announcing-1-4

chore(deps): upgrade to Rsbuild@1.4.0

---

.changeset/1750936736250-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/document/rspress.config.ts
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.18

---

packages/core/src/node/auto-nav-sidebar/normalize.ts
packages/core/src/node/auto-nav-sidebar/walk.ts
packages/core/src/node/route/RoutePage.ts
packages/core/src/node/route/RouteService.ts
packages/core/src/node/route/normalizeRoutePath.ts
packages/core/src/node/utils/normalizePath.ts

refactor: move the RoutePath logic to RoutePage class

refactor: move the RoutePath logic to RoutePage class

---

.changeset/1751621081756-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.19

---

.changeset/1752031917599-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-last-updated/package.json
packages/plugin-llms/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.20

---

.changeset/1752496425985-beta-release.md
packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-llms/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.21

---

packages/core/src/node/auto-nav-sidebar/type.ts
packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx

chore(auto-nav-sidebar): update custom-link types
#2382

chore(auto-nav-sidebar): update custom-link types

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.45.0

---

packages/theme-default/src/layout/DocLayout/index.module.scss

fix(theme): aside should not cover the top buttons (#2400)

---

.changeset/1753177841865-beta-release.md
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-llms/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.22

---

packages/core/package.json
packages/core/rslib.config.ts
packages/core/src/node/initRsbuild.ts
packages/core/src/node/runtimeModule/i18n.ts
packages/plugin-llms/package.json
packages/plugin-preview/package.json
packages/shared/package.json
pnpm-lock.yaml

chore: update rsbuild 1.4.12
https://github.com/web-infra-dev/rspack/pull/11182
https://github.com/web-infra-dev/rspack/pull/11178

chore(deps): update rsbuild 1.4.12 and more accurate persistent cache

---

packages/document/docs/en/plugin/official-plugins/llms.mdx
packages/document/docs/zh/plugin/official-plugins/llms.mdx

docs(typo): update plugin-llms

docs(typo): update plugin-llms

---

packages/plugin-llms/src/llmsTxt.ts
packages/plugin-llms/src/plugin.ts

fix(plugin-llms): some md files sometimes do not emit

fix(plugin-llms): some md files sometimes do not emit

---

packages/runtime/src/hooks/useFrontmatter.ts
packages/runtime/src/hooks/useLang.ts
packages/runtime/src/hooks/useVersion.ts

refactor(theme): usePageData => usePage

refactor(theme): usePageData => usePage

---

packages/shared/package.json
packages/theme-default/package.json
packages/theme-default/rslib.config.ts
pnpm-lock.yaml

chore(infra): update css typed modules

chore(infra/script): update css typed modules

---

.changeset/1755249415566-beta-release.md
packages/core/package.json
packages/create-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-llms/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-sitemap/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.27

---

packages/core/README.md
website/rspress.config.ts

docs: upgrade readme and add npm link

docs: upgrade readme and add npm link to docsite

---

packages/core/package.json
packages/plugin-llms/package.json
packages/plugin-preview/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Clean up package.json files by removing unused dependencies that are no longer needed in the codebase.
Found by [Knip](https://knip.dev/) (Some of the results in the screenshots are misjudgments):

fix(deps): remove unused dependencies from multiple packages

---

.changeset/1755777641930-beta-release.md
packages/core/package.json
packages/create-rspress/package.json
packages/plugin-algolia/package.json
packages/plugin-api-docgen/package.json
packages/plugin-client-redirects/package.json
packages/plugin-llms/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-sitemap/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v2.0.0-beta.28

---

website/docs/en/guide/basic/use-mdx/code-blocks.mdx
website/docs/en/guide/basic/use-mdx/link.mdx
website/docs/zh/guide/basic/use-mdx/code-blocks.mdx

docs(codeblocks): polish some write style

---

packages/plugin-llms/src/normalizeMdFile.ts
packages/plugin-llms/src/plugin.ts
packages/plugin-llms/src/types.ts
website/docs/en/plugin/official-plugins/llms.mdx
website/docs/zh/plugin/official-plugins/llms.mdx

feat(plugin-llms): support mdFiles.remarkPlugins

feat(plugin-llms): support `mdFiles.remarkPlugins`

---

packages/core/src/node/runtimeModule/pageData/createPageData.ts
packages/core/src/node/runtimeModule/pageData/rsbuildPlugin.ts
packages/core/src/node/runtimeModule/types.ts
packages/core/src/runtime/env.d.ts
packages/core/src/runtime/initPageData.ts
packages/runtime/rslib.config.ts
packages/runtime/src/env.d.ts
packages/runtime/src/hooks/usePages.ts
packages/theme-default/rslib.config.ts
packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
packages/theme-default/src/env.d.ts
website/docs/en/guide/basic/use-mdx/_meta.json

fix(virtual-module): should addDependencies in virtual-module for persistent cache

fix(virtual-module): should addDependencies in virtual-module for persistent cache

---

packages/plugin-llms/src/runtime/LlmsCopyButton.module.scss
packages/plugin-llms/src/runtime/LlmsViewOptions.module.scss
packages/plugin-llms/src/runtime/LlmsViewOptions.tsx
packages/theme-default/src/layout/DocLayout/docComponents/code/index.module.scss

chore(plugin-llms): add animation to LlmsViewOptions

chore(plugin-llms): add animation to LlmsViewOptions

---

website/docs/en/guide/basic/use-mdx/code-blocks.mdx
website/docs/en/plugin/official-plugins/twoslash.mdx
website/docs/zh/guide/basic/use-mdx/code-blocks.mdx
website/docs/zh/plugin/official-plugins/twoslash.mdx

docs: polish twoslash usage doc

docs: polish twoslash usage doc

---

pnpm-lock.yaml
website/docs/en/plugin/official-plugins/twoslash.mdx
website/docs/zh/plugin/official-plugins/twoslash.mdx

docs(plugin-twoslash): fix typo

docs(plugin-twoslash): fix typo

---

website/docs/en/guide/basic/use-mdx/code-blocks.mdx
website/docs/zh/guide/basic/use-mdx/code-blocks.mdx

docs(codeblocks): add diff block

docs(codeblocks): add diff block

---

e2e/fixtures/hmr/index.test.ts

test(e2e): fix ci case sensitivity

test(e2e): fix ci case sensitivity

---

packages/plugin-playground/src/cli/index.ts
packages/plugin-playground/src/web/utils.ts

fix(plugin-playground): normalizeUrl skip protocol(#2563)

---

packages/theme-default/src/styles/base.css

use :where to en lower the css priority
[#2569](https://github.com/web-infra-dev/rspress/issues/2569)

chore(theme/style): use :where to ul and li original style

---

packages/cli/package.json
packages/core/package.json
packages/create-rspress/package.json
packages/document/package.json
packages/modern-plugin-rspress/package.json
packages/plugin-api-docgen/package.json
packages/plugin-auto-nav-sidebar/package.json
packages/plugin-client-redirects/package.json
packages/plugin-container-syntax/package.json
packages/plugin-last-updated/package.json
packages/plugin-medium-zoom/package.json
packages/plugin-playground/package.json
packages/plugin-preview/package.json
packages/plugin-rss/package.json
packages/plugin-shiki/package.json
packages/plugin-typedoc/package.json
packages/runtime/package.json
packages/shared/package.json
packages/theme-default/package.json
pnpm-lock.yaml

Release v1.45.4

---

package.json
pnpm-lock.yaml

chore(deps): upgrade nx to upgrade axios and form-data
https://github.com/web-infra-dev/rspress/security/dependabot/64

chore(deps): upgrade nx to upgrade axios and form-data

---

packages/theme-default/src/styles/index.ts
packages/theme-default/src/styles/vars.css
packages/theme-default/src/styles/vars/brand.scss
website/docs/components/CssLiveCodeEditor.tsx
website/docs/components/CssLiveCodeEditorWithTabs.tsx
website/docs/components/CssPickerEditor.tsx
website/docs/components/LiveCodeEditor.module.scss
website/docs/components/LiveCodeEditor.tsx
website/docs/en/_nav.json
website/docs/en/ui/_meta.json
website/docs/en/ui/vars.mdx
website/docs/env.d.ts
website/docs/zh/_nav.json
website/docs/zh/ui/_meta.json
website/docs/zh/ui/vars.mdx
website/rspress.config.ts

docs(ui): upgrade Rspress UI part

docs(ui): upgrade Rspress UI part

---

packages/core/src/node/build.ts
packages/core/src/node/initRsbuild.ts

fix(ssg): Prevent the risk of naming conflicts with the user folders

fix(ssg): Prevent the risk of naming conflicts with the user folders

---

packages/plugin-llms/src/normalizeMdFile.ts
packages/plugin-llms/src/plugin.ts

fix(plugin-llms): should be compilatable to user manual nav and sidebar configuration

fix(plugin-llms): should be compilatable to user manual nav and sidebar configuration
